### ISSUE TITLE
ONNX multi dynamic_axes cause error

### ISSUE THREAD

**Issue by taomiao** [NVIDIA/triton-inference-server#1040]
**Description**
for bert model, I define input dims as [ batch_size, seq_len ], batch_size and seq_len are dynamic_axes，but trtis gave [ -1 ]

**TRTIS Information**
What version of TRTIS are you using? 19.10-py3
Are you using the TRTIS container or did you build it yourself? no

**To Reproduce**
    torch.onnx.export(model,  # model being run
                      (token_ids),  # model input (or a tuple for multiple inputs)
                      f=data_path + "bert_fc_ner_opset10.onnx",  # where to save the model (can be a file or file-like object)
                      export_params=True,  # store the trained parameter weights inside the model file
                      opset_version=10,  # the ONNX version to export the model to
                      do_constant_folding=True,  # whether to execute constant folding for optimization
                      input_names=['input'],  # the model's input names
                      output_names=['output'],  # the model's output names
                      dynamic_axes={'input': {0: 'batch_size', 1: 'sequence_length'},  # variable lenght axes
                                    'output': {0: 'batch_size', 1: 'sequence_length'}})

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
I don't understand what problem you are facing. Are you getting an error from TRTIS? Does your model fail to load?

**Comment by dsandii** [comment]
I'm facing something like this as well.
I've exported a torchvision FastRCNN using ONNX.

I allowed the output nodes to have 2 dynamic axes `0: "batch_size", 1: "num_detections"`. ONNX appears to serialize it properly & the shapes seem ok when I check them.

However when I load it into TRTIS (`nvcr.io/nvidia/tensorrtserver:20.02-py3`) I get the following error:
```E0326 15:35:39.159922 1 model_repository_manager.cc:832] failed to load 'torch_rcnn' version 1: Invalid argument: model 'torch_rcnn', tensor 'boxes': for the model to support batching the shape should have at least 1 dimension and the first dimension must be -1; but shape expected by the model is [2,3,4]```

The error suggests to me that the axes are not being considered dynamic anymore.

This may be relevant, but TRTIS also appears to enforce constant folding on some initializers when I load it up. I doubt that would cause this though, right?

**Comment by deadeyegoodwin** [comment]
Can you share your model configuration file (config.pbtxt). Looks like you have specified that Triton should support batching in the model but also have a non-batching input called "boxes".

**Comment by dsandii** [comment]
So my previous comment was posted when I was operating under the assumption that the torchvision detection model API supported exporting ONNX models with multiple dynamic axes. They don't currently, so I was mistaken. That error was likely not due to TRTIS.

Regardless, this is the config I settled on trying to use.

```
name: "torch_detection_rcnn"
platform: "onnxruntime_onnx"
input [
  {
    name: "images"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 745, 1324 ]
  }
]
output [
  {
    name: "boxes"
    data_type: TYPE_FP32
    dims: [ -1, 4 ]
  },
  {
    name: "labels"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
```

I was trying to get it to use an implicit batching dimension and the explicitly dynamic num_detections dimension. I'm not sure if that's correct though.

**Comment by deadeyegoodwin** [comment]
That configuration has no max_batch_size (so max_batch_size == 0). That tells Triton that the model doesn't support dynamic batching in the way that Triton understands. Triton only supports dynamic batching where the batch dimension is the first dimension and every input and output has the batch dimension. Putting aside any non-Triton issues your model may have, as long as those data-types and shapes match what the model expects that configuration should be ok.
