### ISSUE TITLE
TRTIS failed to load 'trt model:     unexpected configuration maximum batch size 64 for 'resnet50_trt_0_gpu0', model maximum is 1 as model does not contain an implicit batch dimension nor the explicit batch-dimension of 'gpu_0/data_0' is a wildcard

### ISSUE THREAD

**Issue by mdztravelling** [NVIDIA/triton-inference-server#1105]
**Description**
I use TRTIS  inference  tensorrt model （resnet50, from TensorRT-7.0.0.11/data/resnet50/ResNet50.onnx  and use Tensorrt 7.0 convert to trt model.）, but load model failed.

E0213 08:38:03.190242 56095 model_repository_manager.cc:834] failed to load 'resnet50_trt' version 1: Invalid argument: unexpected configuration maximum batch size 64 for 'resnet50_trt_0_gpu0', model maximum is 1 as model does not contain an implicit batch dimension nor the explicit batch-dimension of 'gpu_0/data_0' is a wildcard. 
error: creating server: INTERNAL - failed to load all models

my config.pbtxt is:
```
name: "resnet50_trt"
platform: "tensorrt_plan"
max_batch_size: 64
dynamic_batching {
    preferred_batch_size: [ 8, 16, 32 ]
    max_queue_delay_microseconds: 100 
}
input [
   {   
      name: "gpu_0/data_0"
      format: FORMAT_NCHW
      data_type: TYPE_FP32
      dims: [ 3, 224, 224 ]
   }   
]
output [
   {   
      name: "gpu_0/softmax_1"
      data_type: TYPE_FP32
      dims: [ 1000 ]
   }   
]
cc_model_filenames [
   {   
      key: "6.1"
      value: "ResNet50.onnx.v7.b64.trt"
   }   
]
```

Is this error made by TRTIS or  Tensorrt 7.0 ? And how to use dynamic batch in TRTIS (20.1)?

my convert script is  （onnx -> trt）, use trt7.0:
```
EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
TRT_LOGGER = trt.Logger(trt.Logger.WARNING)

def get_engine(onnx_file_path, engine_file_path="", batch_size=64):
    """Attempts to load a serialized engine if available, otherwise builds a new TensorRT engine and saves it."""
    def build_engine():
        """Takes an ONNX file and creates a TensorRT engine to run inference with"""
        with trt.Builder(TRT_LOGGER) as builder, builder.create_network(EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
            builder.max_workspace_size = 1 << 30 
            builder.max_batch_size = batch_size 
            # Parse model file
            if not os.path.exists(onnx_file_path):
                exit(0)
            print('Loading ONNX file from path {}...'.format(onnx_file_path))
            with open(onnx_file_path, 'rb') as model:
                print('Beginning ONNX file parsing')
                parser.parse(model.read())
            print('Completed parsing of ONNX file')
            print('Building an engine from file {}; this may take a while...'.format(onnx_file_path))
            engine = builder.build_cuda_engine(network)
            print("Completed creating Engine")
            with open(engine_file_path, "wb") as f:
                f.write(engine.serialize())
            return engine
    return build_engine()
```

**TRTIS Information**
What version of TRTIS are you using?
20.1
Are you using the TRTIS container or did you build it yourself?
build it myself, use cmake

**To Reproduce**

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
For TRT models the easiest way to get the correct model configuration is to not provide a config.pbtxt and instead use --strict-model-config=false. See https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_configuration.html#generated-model-configuration

**Comment by mdztravelling** [comment]
> For TRT models the easiest way to get the correct model configuration is to not provide a config.pbtxt and instead use --strict-model-config=false. See https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_configuration.html#generated-model-configuration

thanks @deadeyegoodwin 
--strict-model-config=false can get config.pbtxt of model with batch size = 1, and  TRTIS can do inference.  config.pbtxt is as bellow: 
```
id: "inference:0"
uptime_ns: 20750459507
model_status {
  key: "resnet50_trt"
  value {
    config {
      name: "resnet50_trt"
      platform: "tensorrt_plan"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      max_batch_size: 1
      input {
        name: "gpu_0/data_0"
        data_type: TYPE_FP32
        dims: 1
        dims: 3
        dims: 224
        dims: 224
      }
      output {
        name: "gpu_0/softmax_1"
        data_type: TYPE_FP32
        dims: 1
        dims: 1000
      }
      instance_group {
        name: "resnet50_trt"
        count: 1
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "ResNet50.onnx.v7.b1.trt"
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
        ready_state_reason {
        }
      }
    }
  }
}
ready_state: SERVER_READY
```
but when load model  with  max_batch_size > 1 ,  TRTIS  occured error,  as bellow
```
0214 12:58:44.145089 40818 model_repository_manager.cc:834] failed to load 'resnet50_trt' version 1: Invalid argument: unexpected configuration maximum batch size 2 for 'resnet50_trt_0_gpu0', model maximum is 1 as model does not contain an implicit batch dimension nor the explicit batch-dimension of 'gpu_0/data_0' is a wildcard. 
error: creating server: INTERNAL - failed to load all models
```
so, how to convert an onnx model to trt7 model ? or how to load trt7 model that max_batch_size > 1  use TRTIS ?  Is there trt7 model that max_batch_size > 1 demo ?

**Comment by deadeyegoodwin** [comment]
Based in the generated config file it appears that the model has a fixed batch dimension of 1, which is why you can't set max_batch_size > 0. To set max_batch_size > 1 the model must support batching in a way that TRTIS can understand. Currently the only way that TRTIS understands is if the first dimension of every input/output is the batch dimension and that dimension has variable size (represented by -1 in TRTIS).

So why does your model have a fixed batch dimension? I don't know. Perhaps the original ONNX model does and the conversion to TensorRT didn't change that. Perhaps when you convert to TensorRT there is some way to tell it to treat the first dimension as a batch dimension (and make it -1). You should ask those TensorRT questions here: https://github.com/NVIDIA/TensorRT/issues

**Comment by mdztravelling** [comment]
> Based in the generated config file it appears that the model has a fixed batch dimension of 1, which is why you can't set max_batch_size > 0. To set max_batch_size > 1 the model must support batching in a way that TRTIS can understand. Currently the only way that TRTIS understands is if the first dimension of every input/output is the batch dimension and that dimension has variable size (represented by -1 in TRTIS).
> 
> So why does your model have a fixed batch dimension? I don't know. Perhaps the original ONNX model does and the conversion to TensorRT didn't change that. Perhaps when you convert to TensorRT there is some way to tell it to treat the first dimension as a batch dimension (and make it -1). You should ask those TensorRT questions here: https://github.com/NVIDIA/TensorRT/issues

thanks @deadeyegoodwin 
I use dynamic_axes in torch.onnx.export() funciton to convert torch model to ONNX model (batch dimension is -1), then use optimization profile convert it to trt7,  code is as below:
```
EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
TRT_LOGGER = trt.Logger(trt.Logger.WARNING)

def get_engine(onnx_file_path, engine_file_path="", batch_size=1):
    """Attempts to load a serialized engine if available, otherwise builds a new TensorRT engine and saves it."""
    def build_engine():
        """Takes an ONNX file and creates a TensorRT engine to run inference with"""
        with trt.Builder(TRT_LOGGER) as builder, builder.create_network(EXPLICIT_BATCH) as network, \
             builder.create_builder_config() as config, trt.OnnxParser(network, TRT_LOGGER) as parser:
            profile = builder.create_optimization_profile()

    
            profile.set_shape("input", (2, 3, 224, 224), (4, 3, 224, 224), (8, 3, 224, 224)) 
            config.add_optimization_profile(profile)
            builder.max_workspace_size = 1 << 26
            builder.max_batch_size = batch_size 
            # Parse model file
            if not os.path.exists(onnx_file_path):
                return None
            print('Loading ONNX file from path {}...'.format(onnx_file_path))
            with open(onnx_file_path, 'rb') as model:
                print('Beginning ONNX file parsing')
                parser.parse(model.read())

            engine = builder.build_engine(network, config)
            with open(engine_file_path, "wb") as f:
                f.write(engine.serialize())
            return engine

    return build_engine()
```
the trt7 model can be loaded in TRTIS (20.01), and config.pbtxt as bellow:
```
id: "inference:0"
uptime_ns: 12182741835
model_status {
  key: "resnet50_trt"
  value {
    config {
      name: "resnet50_trt"
      platform: "tensorrt_plan"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      max_batch_size: 8
      input {
        name: "input"
        data_type: TYPE_FP32
        dims: 3
        dims: 224
        dims: 224
      }
      output {
        name: "output"
        data_type: TYPE_FP32
        dims: 1000
      }
      instance_group {
        name: "resnet50_trt"
        count: 1
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "model.plan"
      cc_model_filenames {
        key: "6.1"
        value: "resnet50-19c8e357.pth.b8.onnx.v7.b1.trt"
      }
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
        ready_state_reason {
        }
      }
    }
  }
}
ready_state: SERVER_READY
```
But I use perf_client request TRTIS  to inference (batch dimension has has variable size ) and occured cuda out of memory,  TRTIS  log is 
```
I0216 14:22:27.334355 11186 plan_backend.cc:411] Created instance resnet50_trt_0_gpu0 on GPU 0 (6.1) with stream priority 0 and optimization profile default[0];
I0216 14:22:27.403509 11186 model_repository_manager.cc:831] successfully loaded 'resnet50_trt' version 1
Starting endpoints, 'inference:0' listening on
E0216 22:22:27.404554956   11186 socket_utils_common_posix.cc:198] check for SO_REUSEPORT: {"created":"@1581862947.404531266","description":"SO_REUSEPORT unavailable on compiling system","file":"/home/work/modanzeng/tensorrt-inference-server/builddir/grpc-repo/src/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":166}
I0216 14:22:27.406360 11186 grpc_server.cc:1971] Started GRPCService at 0.0.0.0:8030
I0216 14:22:27.406430 11186 http_server.cc:1427] Starting HTTPService at 0.0.0.0:8000
I0216 14:22:27.559839 11186 http_server.cc:1442] Starting Metrics Service at 0.0.0.0:8002
Cuda error in file src/implicit_gemm.cu at line 585: out of memory
E0216 14:38:42.059019 11186 logging.cc:43] ../rtSafe/cuda/caskConvolutionRunner.cpp (370) - Cuda Error in execute: 2 (out of memory)
E0216 14:38:42.059269 11186 logging.cc:43] FAILED_EXECUTION: std::exception
```
However the trt model which fixed batch dimension of 1 does not have GPU out of merory.
How should I solve this problem？

**Comment by deadeyegoodwin** [comment]
How much memory does your GPU have? Have you used nvidia-smi to monitor the GPU memory use as the model is loaded? How did you run perf_client? The TRT model that supports batch-size 8 will use significantly more memory than a batch-size 1 model.

**Comment by mdztravelling** [comment]
> How much memory does your GPU have? Have you used nvidia-smi to monitor the GPU memory use as the model is loaded? How did you run perf_client? The TRT model that supports batch-size 8 will use significantly more memory than a batch-size 1 model.

1) My GPU memory is 7611MiB on Tesla P4.  
2) Batch-size = 1 (fixed batch size) model used 611MiB memory and running perf-clinet memory does not increase. 
perf-client command: 
```
./bin/perf_client -m resnet50_trt -x 1 -d -c 64 -l 500 -p 5000  -i grpc -u localhost:8030 -t 1 -b 1 --max-threads=1
```
3) max-batch-size = 8 (batch dimension  has variable size (represented by -1 ) model used 827MiB memory, but when running perf-clinet  memory increase  and occured oom.
perf-client command is :
```
./bin/perf_client -m resnet50_trt -x 1 -d -c 64 -l 500 -p 5000  -i grpc -u localhost:8030 -t 1 -b 8 --max-threads=1
```

**Comment by deadeyegoodwin** [comment]
Can you share the onnx model so we can run it through your script and then try to reproduce the failure?

**Comment by mdztravelling** [comment]
> Can you share the onnx model so we can run it through your script and then try to reproduce the failure?

In this github repository https://github.com/mdztravelling/resnet_model , you can clone it. Thanks.

**Comment by CoderHam** [comment]
> In this github repository https://github.com/mdztravelling/resnet_model , you can clone it. Thanks.

I used the script above and the onnx model from this repository you provided but I do not see this Out of memory error. I am using a TITIAN V (**12GB**).

TRT reserves the shape as designated by the largest profile i.e. for the batch size of 8. Hence while running inferences, the footprint of TRT remains the same during the perf_client run for both batch size 2 and 8. As shown below.

```
install/bin/perf_client -m model_trt -p 5000 -i grpc -u localhost:8001 -t 1 -b 2
```
Concurrency: 1, throughput: **230** infer/sec, latency 8689 usec
|    0     25692      C   /opt/tensorrtserver/bin/trtserver           **1923**MiB |

```
install/bin/perf_client -m model_trt -p 5000 -i grpc -u localhost:8001 -t 1 -b 8
``` 
Concurrency: 1, throughput: **404.8** infer/sec, latency 19727 usec
|    0     25692      C   /opt/tensorrtserver/bin/trtserver           **1923**MiB |

**Comment by CoderHam** [comment]
Here is the [log.txt](https://github.com/NVIDIA/tensorrt-inference-server/files/4284286/log.txt) that contains the run with the exact command you used. It runs from concurrency 1 to 49. I do not see an increase in GPU memory consumption.

**Comment by mdztravelling** [comment]
> Here is the [log.txt](https://github.com/NVIDIA/tensorrt-inference-server/files/4284286/log.txt) that contains the run with the exact command you used. It runs from concurrency 1 to 49. I do not see an increase in GPU memory consumption.

thanks. @CoderHam 

Would you like to share your trt model which has variable batch size? 
And I use P4 GPU with 7611MiB memory. I build TRTIS with cmake.  Do you have any idea to find out what caused oom  when running trt model which has variable batch size in  my TRTIS ?

**Comment by CoderHam** [comment]
I am using the TRTIS 20.02 container. I am unsure what causes you to get the OOM error when running a TRT model with variable batch size because I am unable to produce it on my end.

**Comment by CoderHam** [comment]
You can find the model in the drive [here](https://drive.google.com/drive/folders/1McUHa8DRK4AruyICqPAqVEDyf1eNIExe?usp=sharing). Request access and I will grant it to you.
