### ISSUE TITLE
Can V2 APIs client satisfied these requirement ?

### ISSUE THREAD

**Issue by rithd** [NVIDIA/triton-inference-server#1129]
I think the http client and RESTFUL api are still too hard to use, especially for the users who hasn't some insight into TRTIS. For example, I can't infer the model by json-based http request tools (such as postman) without TRTIS client. And even though I use the python client, I also can't add parameters in requests url easily, because of the client generates the url in cpp code. 

And I mentioned that you are developing the V2 APIS, and I want to know can V2 APIS improve the usability of TRTIS client?

Thanks

**Comment by rithd** [comment]
We decide to deploy TRTIS in our microservices cluster. But I'm stuck in passing a parameter in the url for the microservice when I want to inference the model by TRTIS deployed in the microservices cluster. So could you help me that how can I pass a parameter to TRTIS in url by using the TRTIS python client? I don't want to modify the function of "InferHttpContextImpl::PreRunProcessing" and compile the cpp code.

appreciate it

**Comment by nieksand** [comment]
What is this query parameter you are trying to add to the URL?

I don't use the provided Python client and just hit the HTTP endpoint directly.  I've found it to be pretty straight forward:
1. Craft an appropriate `NV-InferRequest` specifying batch size, input tensor name, output tensor name.
2. Add your input tensor to the request body.  For a numpy array which already has the correct shape, you can just use `.asbytes()`.
3. HTTP POST to TRTIS:  `localhost:8000/api/infer/<model name>/<model ver>`
4. Check response header for errors.
5. Slurp successful output tensor from response body.  With numpy, you can use `frombuffer()` and `reshape()`.

Also handy, newer versions of TRTIS can output a list of available models in a JSON format: `http://localhost:8000/api/status?format=json`

**Comment by deadeyegoodwin** [comment]
Using the python client would require use to have an option to pass additional parameters. Of source the inference server won't understand those parameters so I am curious as to what you are trying to do.

But we are working on a version 2 of the server and client APIs so if there is a reason to allow specification of custom parameters it would be good for us to understand so we can add that support in version 2.

**Comment by rithd** [comment]
@nieksand Thanks for you help. I used to try to send HTTP request directly, but the format was binary and it was difficult for debugging...

@deadeyegoodwin I want to pass an access token in url query, and I only find the interface of passing parameters in http header instead of url query. The token is used by our microservices cluster. It would be appreciated if your v2 client can support it. Btw, could you tell me when will the version 2 http client release ：）

**Comment by deadeyegoodwin** [comment]
We will plan on adding a way to add query parameters in the V2 HTTP client.

We are working on it now and you can see that work in the src/client area. There will be an initialize V2 client that uses GRPC in the 20.03 release. On the master branch I would guess that you would have a V2 http client you could try sometime in late March.

**Comment by rithd** [comment]
@deadeyegoodwin 
Received. 
And could you add an editor in client image, I have to install vim in the contaier right now. Thanks.

**Comment by tanmayv25** [comment]
The support for providing custom url query parameters has been added to the version 2 of the http python client. Look [here](https://github.com/NVIDIA/triton-inference-server/blob/master/src/clients/python/experimental_api_v2/examples/simple_http_v2_infer_client.py#L48-L52) for example.

We will be soon adding V 2 C++ clients for the same.

**Comment by rithd** [comment]
@tanmayv25  When will the 20.05-py3(version 2) image release and I can pull it from ngc?

**Comment by nieksand** [comment]
They usually release at the end of the month, so 20.05 should be near the end of May.

**Comment by rithd** [comment]
@nieksand And 20.04 won't have the http_v2 server/client, so if I want to use it, I have to wait for end of May?

**Comment by nieksand** [comment]
You could also build an image yourself if you need it sooner:
https://github.com/NVIDIA/triton-inference-server/blob/master/docs/build.rst

**Comment by rithd** [comment]
I have built it and I found the master code doesn't look like tested. The trtis process may crash and core dumped if the json content is lilegal...

**Comment by deadeyegoodwin** [comment]
The V2 APIs are still under development so you should expect some instability (in general master is an under development branch and so doesn't have the stability of the release branches). V2 will become more stable over time leading up to the 20.05 release.

**Comment by rithd** [comment]
@deadeyegoodwin So I will get a stable V2 APIs image at the end of May？

**Comment by deadeyegoodwin** [comment]
The roadmap is described in the README and we are currently still on track for that schedule. It will be a beta release of the V2 APIs.

**Comment by rithd** [comment]
Can the 20.05 image releases on schedule? I mention that 20.04 image haven't been released.

**Comment by deadeyegoodwin** [comment]
20.05 is on track for an end-of-may release. You can always build from master right now and try out the V2 APIs. Right now master and 20.05 are mostly identical.

**Comment by rithd** [comment]
glad to hear that :)
