### ISSUE TITLE
How to use perf_client on ensemble models and sequence models

### ISSUE THREAD

**Issue by zhouxuan009** [NVIDIA/triton-inference-server#1151]
I wanted to get the performance data of ensemble models. So I used perf_client. However, When I started the example ensemble model (Preprocess + Resnet50), and used perf client, it gave me error message like

> perf_client -m preprocess_resnet50_ensemble --concurrency-range 1:4
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 4 concurrent requests
  Using synchronous calls for inference
  Stabilizing using average latency

> Request concurrency: 1
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
[ 0] INTERNAL - Failed to maintain concurrency level requested. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: [inference:0 14] INTERNAL - in ensemble 'preprocess_resnet50_ensemble', payload error for 'image_preprocess_nchw_3x224x224_inception_0_1_gpu1': (12) unable to preprocess image

Does it mean that I need to modify the perf_client code file to make it adapt to ensenble model ? Or is there anyway else to get the performance data ? I tried Server Trace but it could not test throuput. Btw, do I need to modify the perf_client code file to make it adapt to sequence model if I want to get the performance data of the sequence model?

Thank you !

**Comment by tanmayv25** [comment]
By default, perf client generates random data and use that to send concurrent requests. The error indicates the model failed to preprocess the randomly generated data. You might have to provide a realistic image input. Have a [here](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/c%2B%2B/perf_client/perf_client.cc#L443-L462). Using --input-data option specify a directory containing raw data for each input. Note, the name of the binary file containing the raw data should match with the corresponding input name of the model.

Perf client should already have all the support for sequence and ensemble models. Let us know if you have any specific requirement.

**Comment by zhouxuan009** [comment]
This custom backend image_preprocess takes a byte string of original image as input and
returns preprocessed image. How to transform the original image to string for input ?

**Comment by tanmayv25** [comment]
Have you run the inference request on TRTIS (with this model) outside perf_client? Which APIs did you use? and can you share the model config.pbtxt file?

**Comment by zhouxuan009** [comment]
I ran this [ensemble model](https://github.com/NVIDIA/tensorrt-inference-server/tree/master/src/backends/ensemble) on TRTIS and successed with [ensemble_image_client](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/c%2B%2B/examples/ensemble_image_client.cc)

I am using [preprocess_resnet50_ensemble/config.pbtxt](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/docs/examples/ensemble_model_repository/preprocess_resnet50_ensemble/config.pbtxt)

**Comment by zhouxuan009** [comment]
I ran this ensemble model
<https://github.com/NVIDIA/tensorrt-inference-server/tree/master/src/backends/ensemble>
on
TRTIS and successed with ensemble_image_client
<https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/c%2B%2B/examples/ensemble_image_client.cc>

I am using preprocess_resnet50_ensemble/config.pbtxt
<https://github.com/NVIDIA/tensorrt-inference-server/blob/master/docs/examples/ensemble_model_repository/preprocess_resnet50_ensemble/config.pbtxt>

Tanmay Verma <notifications@github.com> 于2020年3月3日周二 上午11:24写道：

**Comment by tanmayv25** [comment]
Currently, the perf_client doesn't have a way to provide image data as string. Marking this as an enhancement.

**Comment by GuanLuo** [comment]
@tanmayv25 With `input-data` option, user is already able to provide input data in the form that the model expects. In this case, I don't think perf_client should know how to preprocess data for the model, the step should be done by the user.

@zhouxuan009 It's not well-documented in the `image_preprocess` custom backend, but the input is simply the bytes of the image in the string format expected by TRTIS. In other words, "4 bytes of the image byte size + the image".

**Comment by tanmayv25** [comment]
@GuanLuo  The legacy --input-data expects binary files for non-string data types and text files for string data type. As this model expects string input we can't provide "4 bytes of the image byte size + the image" binary file.
Moreover, the image when represented as string contains whitespaces that can not be represented in the text file as we use the new line as element delimiters.
The solution is to enhance the new json specification to allow reading data from file and prepend the image size.

**Comment by tanmayv25** [comment]
Look [here ](https://github.com/NVIDIA/triton-inference-server/blob/master/qa/L0_perf_client/test.sh#L152-L164) to see how to run perf client with preprocess_resnet50_ensemble model.  

Also have a look at the discussion on #1209  for further details into image_data.json.
