### ISSUE TITLE
Any examples on stateful models?

### ISSUE THREAD

**Issue by t13m** [NVIDIA/triton-inference-server#1172]
**Is your feature request related to a problem? Please describe.**
I'm trying to run tensorrt-inference-server with some rnn-based models, but I was not able to figure out how to convert a rnn model (tensorflow model) to a STATEFUL tensorrt plan.
Is there any example of serving a stateful model with tf or onnx backend?
Any information would be appreciated.

**Comment by deadeyegoodwin** [comment]
As you likely know, you don't need to convert to TensorRT to use TRTIS. TensorRT does support RNNs but you would need to consult their documentation about how to convert to those, they also have a github where you can ask questions: https://github.com/NVIDIA/TensorRT

For a stateful model that accepts a sequence of inference requests that need to access and update a long-lived state, then you likely need to use the sequence batcher. See https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/models_and_schedulers.html#stateful-models which explains the options and should also point to some examples.

**Comment by t13m** [comment]
Thanks.
I tried using a tensorflow frozen graph (.pb) directly, and it works, but not as fast as a tensorrt plan model, even with tensorrt fp16 optimization. Is it what I should expect?

**Comment by deadeyegoodwin** [comment]
TensorRT will almost always be faster than TF, often by a large margin. Using TF-TRT integration should improve the performance of TF, but the level of performance will depend on how much of the TF graph can be optimized by TRT. You should not expected TF-TRT to outperform TRT.

**Comment by GabrieldeBlois** [comment]
For those that are looking for the source code of the examples provided under the docs/example part of the documentation, they are located under the [qa](https://github.com/triton-inference-server/server/tree/master/qa) section of the triton server github. There you can find some stateful model implementation example like [this one](https://github.com/triton-inference-server/server/blob/master/qa/L0_dyna_sequence_batcher/dyna_sequence_batcher_test.py).
