### ISSUE TITLE
Accuracy difference between implementations of example image client

### ISSUE THREAD

**Issue by dcyoung** [NVIDIA/triton-inference-server#1184]
Why is there a difference in the accuracy reported for the same image by the two example client implementations (cpp & python)?

This accuracy difference is noted in [running-the-image-classification-example](https://github.com/NVIDIA/tensorrt-inference-server/blob/92dc8c920d584af3ac6e9757c4d1de2dafa90c24/docs/quickstart.rst#running-the-image-classification-example) where the cpp client returns an accuracy of `0.723991` while the python client returns `0.778078556061` for the same image. I have verified this behavior on my own machine. Is there a difference in the implementation of each client's pre-processing that would account for the discrepancy?

**Comment by GuanLuo** [comment]
Yes, it is likely to be the pre-processing. If you are interested, you can check the raw image data after being preprocessed to see if they are different. For C++ client, there is an option to dump the preprocessed image data. For Python, you can modify the client directly.

**Comment by deadeyegoodwin** [comment]
Closing, reopen if additional questions.
