### ISSUE TITLE
TRT inference server does not start in non-GPU mode

### ISSUE THREAD

**Issue by jawacma** [NVIDIA/triton-inference-server#1203]
When starting the TFT inference server in non-GPU mode as described in https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/run.html#running-the-inference-server-on-a-system-without-a-gpu the following error occurs:

===============================
== TensorRT Inference Server ==
===============================

NVIDIA Release 20.02 (build 10247880)

Copyright (c) 2018-2019, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying
project or file.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .

2020-03-19 13:20:56.980187: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
I0319 13:20:57.082168 1 server.cc:112] Initializing TensorRT Inference Server
E0319 13:20:57.082452 1 pinned_memory_manager.cc:194] failed to allocate pinned system memory: CUDA driver version is insufficient for CUDA runtime version

**Comment by GuanLuo** [comment]
The error here should not cause the server to exit, did you see the following prompt which indicates the server is running?
```
I0319 20:55:14.551749 13656 grpc_server.cc:1940] Started GRPCService at 0.0.0.0:8001
I0319 20:55:14.551771 13656 http_server.cc:1415] Starting HTTPService at 0.0.0.0:8000
I0319 20:55:14.593518 13656 http_server.cc:1430] Starting Metrics Service at 0.0.0.0:8002

```

**Comment by jawacma** [comment]
The server did not start due to an invalid model path. However, from the memory error I thought that this was the cause.
