### ISSUE TITLE
perf_client does not support binary (image) data as TYPE_STRING?

### ISSUE THREAD

**Issue by nicklhy** [NVIDIA/triton-inference-server#1209]
**Description**
I tried to use perf_client to do a benchmark of the image_preprocess custom backend like below.
```shell
mv test.jpg model_inputs/INPUT  # the input of the model is "INPUT"
perf_client -m image_preprocess --percentile=95 --concurrency-range 4 -b 1 --input-data model_inputs
```
It crashed with an error message
```
[ 0] INVALID_ARG - input 'INPUT' requires 1 strings for each batch, but provided data has 103 strings.
```

After reading the source code of perf_client, I found it actually read the image file as text (`ReadTextFile` instead of `ReadFile`) if the image_preprocess custom backend's INPUT is TYPE_STRING. Is it a bug ?
https://github.com/NVIDIA/triton-inference-server/blob/4b2fa93cf3d4c7f56339ab64cdf2811d324f00c8/src/clients/c%2B%2B/perf_client/data_loader.cc#L53-L71

**TRTIS Information**
TRTIS 1.11.0
The docker image is built by myself.

**To Reproduce**
```shell
mv test.jpg model_inputs/INPUT  # the input of the model is "INPUT"
perf_client -m image_preprocess --percentile=95 --concurrency-range 4 -b 1 --input-data model_inputs
```

**Expected behavior**
Since the image_preprocess is an official custom backend, I expect the perf_client could measure the performance of it.

**Comment by GuanLuo** [comment]
Currently perf_client is expecting text data for string data type (see discussion [here](https://github.com/NVIDIA/triton-inference-server/issues/1151#issuecomment-594237988)), and yes, it should have handled binary data properly.

@tanmayv25 can elaborate more on the subject.

**Comment by tanmayv25** [comment]
Please have a look [here](https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-guide/docs/optimization.html#real-input-data) for the newer way of providing real data to the perf-client. Specifically, have a look at the section which describes how to pass the binary data as a base64 encoded string.


For now to make it working you would have to create the binary data "4 bytes of the image byte size + the image", convert it to the base64 encoded string, which should be later added to the field in the json. This json will then be used to generate data buffers by the perf_client.

We are going to add the following enhancements to make the process simpler:

1.  Add another key in json to directly provide the binary filename.
2. To prevent the user side responsibility of appending string data with the byte size, provide each individual element in TYPE_STRING tensor as a separate file. The perf_client will append the byte size for each element individually.

The second point would make more sense when the shape of STRING tensors are larger than [1].

**Comment by nicklhy** [comment]
@tanmayv25 Have you tried the base64 str method you mentioned above ?
I put the binary data "4 bytes of the image byte size + the image" into the json file, but the perf_client still crashed with a size mismatch error.
```
[ 0] INVALID_ARG - mismatch in the data provided. Expected: 18446744073709551615 bytes, Got: 29352 bytes ( Location stream id: 0, step id: 0)
```
After inspecting the source code, I found the code below does not work as expected:

https://github.com/NVIDIA/triton-inference-server/blob/ad90248d4e1db57921d6f03b280449cc038791e5/src/clients/c%2B%2B/perf_client/data_loader.cc#L387

Actually, `int64_t InferContext::Input::ByteSize()` returns -1 if the input is TYPE_STRING (refer to the code below), and then, the variable `batch1_byte` with type `size_t` will get a wrong value.
https://github.com/NVIDIA/triton-inference-server/blob/ad90248d4e1db57921d6f03b280449cc038791e5/src/clients/c%2B%2B/library/request.h.in#L303-L308)

I guess we should add some checks before converting the int64_t return value to a size_t variable.

**Comment by tanmayv25** [comment]
You are right. This is a bug with perf_client. I will fix it and update.
