### ISSUE TITLE
unexpected size for output

### ISSUE THREAD

**Issue by ThiagoMateo** [NVIDIA/triton-inference-server#1213]
trtis-20.02-py3

i deploy my tensorflow saved model with tf model config bellow
```
The given SavedModel SignatureDef contains the following input(s):
  inputs['input_image'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, -1, -1, 3)
      name: serving_default_input_image:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['tf_op_layer_GatherV2'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 16)
      name: StatefulPartitionedCall:0
Method name is: tensorflow/serving/predict
```

I got error that i have not seen before. Can you tell me how to fix it?
```
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
Traceback (most recent call last):
  File "client.py", line 33, in <module>
    { output_name : (InferContext.ResultFormat.RAW) }, 1))
  File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 1582, in run
    self._last_request_id = _raise_if_error(c_void_p(_crequest_infer_ctx_run(self._ctx)))
  File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 259, in _raise_if_error
    raise ex
```

my trtis config:
```
input [
    {
        name: "input_image"
        data_type: TYPE_FP32
        dims: [ -1, -1, 3 ]
    }
]
output [
   {
      name: "tf_op_layer_GatherV2"
      data_type: TYPE_FP32
      dims: [ 16 ]
      label_filename: "labels.txt"
   }                         

]
```

**Comment by GuanLuo** [comment]
What is the exception you are receiving?

**Comment by mvpel** [comment]
> What is the exception you are receiving?

It appears to be a server reply via the inference context:

`Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.`

https://github.com/NVIDIA/triton-inference-server/blob/8508e4ac1655c6155ded18185e5efcc9a286db31/src/clients/c%2B%2B/library/request_common.cc#L969

**Comment by deadeyegoodwin** [comment]
@tanmayv25 wasn't this fixed recently?

**Comment by mvpel** [comment]
> @tanmayv25 wasn't this fixed recently?

I've run into an issue with incorrect timestamps from api/status in 1.10.0, showing 6286051604966211776 milliseconds since epoch since the last inference, which is 149 million years in the future. I wonder if this is a related issue? I'll take a look at the history for request_common.cc to see if I can find the PR for the fix.

**Comment by tanmayv25** [comment]
@ThiagoMateo  Are you using gRPC or HTTP protocol for sending inference? Can you try with the other one and share your observation?

@deadeyegoodwin  This issue is different. Note the call to "_crequest_infer_ctx_run" indicates it was a synchronous inference request. We fixed a bug emitting similar error with perf_client where we were trying to get the stat of request which was asynchronous and had failed in it's execution,


> The error quoted above doesn't include any subsequent text (Request time, Send time, or Receive time), indicating that the ternary expressions are defaulting to the empty string on line 999.

This will happen when any of the tags in the marker were not captured.

**Comment by mvpel** [comment]
I got the "timer not set correctly" error from a failed run when my code inadvertently sent a text file to an ensemble workflow which was expecting a JPG of specific dimensions. So it looks like the timer message may be a red herring.

> Start: Wed Apr  1 13:10:36 2020 EDT
> Sending 2668 images to Triton server "prc-microway.twk.us.ray.com:8000"
>     for model "preprocess_5models_averageonly_ensemble" (ver: latest)...
> **Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.**
> Traceback (most recent call last):
>   File "/condor//condor_exec.exe", line 566, in <module>
>     len(input_batch))
>   File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 1589, in run
>     self._last_request_id = _raise_if_error(c_void_p(_crequest_infer_ctx_run(self._ctx)))
>   File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 260, in _raise_if_error
>     raise ex
> tensorrtserver.api.InferenceServerException: [inference:0 32] in ensemble 'preprocess_5models_averageonly_ensemble', **payload error for 'image_preprocess_nhwc_494x648x3_one255_0_0_gpu0': (12) unable to preprocess image**

**Comment by deadeyegoodwin** [comment]
Is this still an issue? Is so please reopen with summary of what is currently working incorrectly.
