### ISSUE TITLE
Incorrect last_inference_timestamp_milliseconds values in api/status output in 1.10.0

### ISSUE THREAD

**Issue by mvpel** [NVIDIA/triton-inference-server#1222]
The api/status output of our server is showing the following for last_inference_timestamp_milliseconds:

```
[pelletm]$ curl http://prc-octo.twk.us.ray.com:8000/api/status | grep last_inference_timestamp_milliseconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39848  100 39848    0     0  3590k      0 --:--:-- --:--:-        last_inference_timestamp_milliseconds: 6286059505728211776
- --        last_inference_timestamp_milliseconds: 6286059520900211776
:--        last_inference_timestamp_milliseconds: 6286059541640211776
:-- 3891k
        last_inference_timestamp_milliseconds: 6286051604966211776
        last_inference_timestamp_milliseconds: 6286059561203211776
        last_inference_timestamp_milliseconds: 6286287894451211776
        last_inference_timestamp_milliseconds: 6286014232652211776
        last_inference_timestamp_milliseconds: 6286014240827211776
        last_inference_timestamp_milliseconds: 12224534135258618432
        last_inference_timestamp_milliseconds: 6286014169034211776
[pelletm]$
```
An ensemble model incorporating the rest of the models on the server was used within the past hour.

This value is described as the number of milliseconds since the epoch:

https://github.com/NVIDIA/triton-inference-server/blob/9c8736df3e3601df8b927b0e4e438243ba2f569a/src/core/server_status.proto#L276

However, the CurrentMillis.com website indicates that it is currently about 1585068724739 milliseconds since the epoch, and 6286014240827211776 as nanoseconds, rather than milliseconds, is about 150 years in the future, and 12224534135258618432 nanoseconds is 337 years in the future. In addition, you would expect the api/status numbers to start with 158 in any case, so there's apparently some incorrect addition or multiplication going on somewhere with these values.

It's apparently not an even power of two, though, since dividing 6286051604966211776 by four, for example, results in a nanosecond timestamp from five months ago. Perhaps epoch stamps are being added together instead of an epoch plus a delta?

It seems possible that this may be related to issue #1213

I'm working to configure the server to shut itself down after it has been idle for a specified period of time, and I need correct timestamps to implement it.

**TRTIS Information**
I am using TRTIS 1.10.0 from the NGC container.

**To Reproduce**
Verify the timestamp values returned by api/status as milliseconds since epoch.

**Comment by GuanLuo** [comment]
The timestamp we are capturing is with CLOCK_MONOTONIC, thus the timestamps shown is good to calculate delta but can't be used as time since epoch. But we will fix it so that `last_inference_timestamp_milliseconds` will be time since epoch.
