### ISSUE TITLE
How to transform caffe2 .pb model files to caffe2 netdef model files ?

### ISSUE THREAD

**Issue by zhouxuan009** [NVIDIA/triton-inference-server#1239]
I have some caffe2 pretrained .pb models. However, TRTIS needs netdef model file. So how to transform caffe2 .pb model files to caffe2 netdef model files ?

**Comment by drwaltman** [comment]
The [quickstart docs](https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-guide/docs/quickstart.html) mention a `fetch_models.sh` script for prepping an example model repository.

[In this script](https://github.com/NVIDIA/triton-inference-server/blob/master/docs/examples/fetch_models.sh#L30-L35) the `predict_net.pb` and `init_net.pb` files are saved as `model.netdef` and `init_model.netdef` respectively when they are downloaded locally.  No transformation needed, just a renaming of the model files.

**Comment by zhouxuan009** [comment]
I see, thank you
