### ISSUE TITLE
TF 2.1 SavedModel Format : unexpected input format FORMAT_NONE, expecting FORMAT_NHWC or FORMAT_NCHW

### ISSUE THREAD

**Issue by viralbthakar** [NVIDIA/triton-inference-server#1240]
**Description**
I am getting `unexpected input format FORMAT_NONE, expecting FORMAT_NHWC or FORMAT_NCHW` error while Running The Image Classification Example for my custom model. 

I am using Tensorflow 2.1 for Training purposes and save the model in the `SavedModel` format of Tensorflow. I am also able to successfully start the tritonserver. The model configuration doesn't have `format` tag. 

```
input {
        name: "input"
        data_type: TYPE_FP32
        dims: 512
        dims: 512
        dims: 3
}
```

And because of this, I think I am getting that particular error while I try to execute the inference from the client-side. 

Also As mentioned [here](https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/model_repository.html#tensorflow-models), I believe if we are using SavedModel format we don't need `config.pbtxt` file.  So I am not using a custom config file. 

**TRTIS Information**
What version of TRTIS are you using?  20.02
Are you using the TRTIS container or did you build it yourself? Using TRTIS container

**To Reproduce**
Steps to reproduce the behavior.
Follow steps here for a custom image classification model : https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/quickstart.html#quickstart

Describe the models (framework, inputs, outputs), ideally include the model configuration file.
If using ensemble include the model configuration file.
```
model_status {
  key: "classifier"
  value {
    config {
      name: "classifier"
      platform: "tensorflow_savedmodel"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      max_batch_size: 1
      input {
        name: "input"
        data_type: TYPE_FP32
        dims: 512
        dims: 512
        dims: 3
      }
      output {
        name: "label_prob"
        data_type: TYPE_FP32
        dims: 1
      }
      instance_group {
        name: "classifier"
        count: 1
        kind: KIND_CPU
      }
      default_model_filename: "model.savedmodel"
      optimization {
        input_pinned_memory {
          enable: true
        }
        output_pinned_memory {
          enable: true
        }
      }
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
        ready_state_reason {
        }
      }
    }
  }
}
```

**Expected behavior**

**Comment by austingg** [comment]
@viralbthakar  you should specify the `format attribute` in the input

**Comment by viralbthakar** [comment]
@austingg Thank for the reply. I think with TF SavedModel format we don't need config.pbtxt file at all. So should I create it and add `format attribute`?

Because As mentioned [here](https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/model_repository.html#tensorflow-models), I believe if we are using SavedModel format we don't need config.pbtxt file. So I am not using a custom config file.

**Comment by deadeyegoodwin** [comment]
The image_client example relies on the format attribute to know how to pre-process and image before sending it to Triton for inferencing. The automatic configuration generation you are using cannot determine this format attribute for you. So you need to copy the automatically generated configuration, edit it to set the appropriate format, and then add it to you model repo as config.pbtxt.

**Comment by RajezMariner** [comment]
@deadeyegoodwin - how do I find the automatically generated config from the triton server?

**Comment by Jawny** [comment]
> 

You can run 
`curl localhost:8000/v2/models/<model_name>/config`

**Comment by Jawny** [comment]
> @deadeyegoodwin - how do I find the automatically generated config from the triton server?

run `curl localhost:8000/v2/models/<model_name>/config` to get the config.

**Comment by Yitiaocaigou** [comment]
> @viralbthakar you should specify the `format attribute` in the input

hi,how to specify 'format attribute'?
