### ISSUE TITLE
ONNX-exported torchvision FasterRCNN fails on inference request

### ISSUE THREAD

**Issue by dsandii** [NVIDIA/triton-inference-server#1241]
**Description**
Internal ONNX error related to dims when running an ONNX-exported `torchvision` FasterRCNN on TRTIS. Error is as follows:
```[E:onnxruntime:, sequential_executor.cc:183 Execute] Non-zero status code returned while running ReduceMax node. Name:'' Status Message: /workspace/onnxruntime/onnxruntime/core/providers/cuda/reduction/reduction_ops.cc:110 onnxruntime::common::Status onnxruntime::cuda::PrepareForReduce(onnxruntime::OpKernelContext*, bool, const std::vector<long int>&, const onnxruntime::Tensor**, onnxruntime::Tensor**, int64_t&, int64_t&, std::vector<long int>&, std::vector<long int>&, std::vector<long int>&) keepdims || dim != 0 was false. Can't reduce on dim with value of 0 if 'keepdims' is false. Invalid output shape would be produced. input_shape:{0,4}\nStacktrace: ```

**TRTIS Information**
Running container /w tag `nvcr.io/nvidia/tensorrtserver:20.02-py3`

**To Reproduce**
Model is a `torchvision.models.detection.FasterRCNN` exported as follows:
```
    outputs = ["boxes", "labels", "scores"]
    dynamic_axes_dict = {output_name: {0: "detections"}
                         for output_name in outputs}
    torch.onnx.export(model, images, os.path.join(output_dir, "model.onnx"),
                      export_params=True,        # store weights in the model file
                      do_constant_folding=True,  # const folding for optimization
                      opset_version=11,          # opset vers 11 req for maskrcnn
                      input_names=["images"],
                      output_names=outputs,
                      dynamic_axes=dynamic_axes_dict,
                      # keep_initializers_as_inputs=True,
                      verbose=True)
```

The exported model's output has been validated against the native Pytorch checkpoint model's output. Everything seems good when run locally in a `onnxruntime` session.

The TRTIS config is as follows:
```
name: "torch_detection_rcnn"
platform: "onnxruntime_onnx"
input [
  {
    name: "images"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 745, 1324 ]
  }
]
output [
  {
    name: "boxes"
    data_type: TYPE_FP32
    dims: [ -1, 4 ]
  },
  {
    name: "labels"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
```

The model is loaded by TRTIS with no complaints, but the error occurs during inference request handling.

**Expected behavior**
Given the fact that I'm able to validate the model & load it onto TRTIS just fine, I expected it to handle requests just fine.

I'm not sure where to go from here, so I had a few questions.
- Is there a particular opset we should be exporting with? I'm using 11 due to `torch` necessitating it.
- Should we be exporting it with all initializers kept as inputs? I tried this and ran into a different error that was more vague.

I'm at a bit of a roadblock so let me know if you need any more information. Also, please let me know if y'all have any suggestions for what to look into and experiment with from here.

**Comment by deadeyegoodwin** [comment]
Can you try with Triton 20.03. We updated ONNXRuntime version and opset support recently.

**Comment by dsandii** [comment]
> Can you try with Triton 20.03. We updated ONNXRuntime version and opset support recently.

Okay, thank you for letting me know about that. I'll report back with the results.

**Comment by dsandii** [comment]
@deadeyegoodwin Same results with `nvcr.io/nvidia/tritonserver:20.03-py3`.

Could this be related in any way to having a slightly older driver on baremetal? I receive this warning when loading the container.

```ERROR: This container was built for NVIDIA Driver Release 440.33 or later, but
       version 430.26 was detected and compatibility mode is UNAVAILABLE.

       [[CUDA Driver UNAVAILABLE (cuInit(0) returned 803)]]```

**Comment by deadeyegoodwin** [comment]
That means you won't have a GPU available to execute your model. That could be a problem if some layers of your model only work on GPU. For GPU support you need to have a version of the CUDA driver expected by the container. From the above message it looks like 440.33. There are some options described in the release notes: https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_20-03.html#rel_20-03

Specifically this section:

GPU Requirements
Release 20.03 supports CUDA compute capability 6.0 and higher. This corresponds to GPUs in the Pascal, Volta, and Turing families. Specifically, for a list of GPUs that this compute capability corresponds to, see CUDA GPUs. For additional support details, see Deep Learning Frameworks Support Matrix.

**Comment by deadeyegoodwin** [comment]
Is this still not working? Is so please reopen.

**Comment by dsandii** [comment]
Apologies for the delayed response. This issue should remain closed, but I just wanted to update the info here.

I believe the problem here arises from the dynamic axes (for number of detections). It appears that something in the ONNX code doesn't account for dynamic axes being potentially 0 (no detections).

I simply modified the graph before exporting to pad all output tensors to a fixed number of elements and was able to bypass this issue.
