### ISSUE TITLE
simple_perf_client inference size usage

### ISSUE THREAD

**Issue by SamChb72** [NVIDIA/triton-inference-server#1247]
**Description**
How to use the -s option?

I tried both
`root@f3bfc6910cef:/opt/tensorrtserver/qa/clients# ./simple_perf_client -u 192.168.1.245:8000 -m resnet50_netdef -l bench1
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
error: unable to run: [inference:0 83728] INVALID_ARG - unexpected shape for input 'gpu_0/data' for model 'resnet50_netdef'. Expected [3,224,224], got [1]
`
and with 3,224,224

`root@f3bfc6910cef:/opt/tensorrtserver/qa/clients# ./simple_perf_client -u 192.168.1.245:8000 -m resnet50_netdef -l bench1 -s "[3,224,224]"
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoul
Aborted (core dumped)
`
and without doublequotes
-s 3,224,224 
gives Expected [3,224,224], got [3]

**TRTIS Information**
What version of TRTIS are you using?
Are you using the TRTIS container or did you build it yourself?
v20.03
built myself
Other tests are OK
**To Reproduce**
Steps to reproduce the behavior.
Describe the models (framework, inputs, outputs), ideally include the model configuration file.
If using ensemble include the model configuration file.

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
Why are you trying to use simple_perf_client? It is not a general purpose utility but is designed specifically to run performancing testing in a couple of the CI (for example, qa/L0_simple_perf). If you are looking for a general purpose performance tool you should use perf_client which is described in the Optimization section of the documentation.
