### ISSUE TITLE
provide a way to get trtis's version info

### ISSUE THREAD

**Issue by nicklhy** [NVIDIA/triton-inference-server#1254]
**Is your feature request related to a problem? Please describe.**
When implementing some custom backends, I found it necessary to get the trtis's version info due to some api changes (i.e. CUSTOM_MEMORY_CPU_PINNED is not defined in v1.9.0). However, I could not find any version macros defined in header or source files.

"TRTIS_VERSION" and "TENSORRT_SERVER_VERSION" can be found in some CMakeLists.txt files or used as an env variable. But none of them actually works. (You can test by print theses macros in an arbitrary custom backend ".cc" file.)

**Describe the solution you'd like**
Provide a header file like "triton_version.h" with the following content
```C++
#define TRITON_VERSION_MAJOR 1
#define TRITON_VERSION_MINOR 11
// ... ...
```

**Comment by deadeyegoodwin** [comment]
If you are using Triton from a container built with our dockerfile you can use the TENSORRT_SERVER_VERSION envvar (soon to be renamed to TRITON_SERVER_VERSION). We are working on a version 3 of the custom backend API and we will make sure to include Triton version in that API.

**Comment by nicklhy** [comment]
@deadeyegoodwin  I am using a docker image built by myself and seems I missed setting TENSORRT_SERVER_VERSION in my Dockerfile. I can add it like the official one to solve my current problem.

But anyway, this option depends on outside environment than triton library itself. In case I set a wrong value, I might not notice it unless the compilation failed or runtime program crashed.
I still believe providing some version macros in a C++ header file like TensorRT is much more straightforward.

**Comment by deadeyegoodwin** [comment]
A custom backend is not bound to any particular version of Triton, so don't you need to know the triton version at runtime? It was a bug for triton to add the CUSTOM_MEMORY_CPU_PINNED enumeration without increasing the custom backend version.

We can add a version macro that you can use a build-time as well in an upcoming release.

**Comment by nicklhy** [comment]
By saying "a custom backend is not bound to any particular version of Triton" and "the custom backend version", do you mean Triton and its custom backend part can be of different versions ?

I did not know that before, but if so, I guess we may need two separate version macros like TRITON_VERSION and TRITON_CUSTOM_BACKEND_VERSION ?

**Comment by deadeyegoodwin** [comment]
The custom backend API is versioned separately from the Triton server itself. Currently there is version 1 and version 2 of the custom backend. You report what version you are using by implementing the CustomVersion function in your backend (https://github.com/NVIDIA/triton-inference-server/blob/master/src/backends/custom/custom.h#L257). If you don't provide this function Triton assumes you are a version 1 backend.

All recent versions of Triton support both version 1 and version 2 backends and going forward Triton will continue to support them. So if you create a version 2 custom backend and build the shared library you don't need to rebuild it again for the next version of Triton. In fact all you need to build a custom backend is the one custom.h file that describes the interface... you don't need any other part of Triton (but using the custom SDK can make things easier).

On a related note, we are doing a significant redesign of the custom backend API (version 3) that will be easier to use and also have more features. We will also provide much improved documentation. Version 1 and 2 will still be supported so if you have old custom backends they will still work.

**Comment by nicklhy** [comment]
Got it. Thank you for the reply !
Can I ask when are you going to release the version 3 custom backend API ?

**Comment by deadeyegoodwin** [comment]
Ideally by the 20.06 release (and will show up earlier in master of course). Keep and eye on the PRs and you should see them. I'll try to remember to update this issue when it is ready. I'm going to close this issue but feel free to ping here for updates near the end of the month (April).

**Comment by nicklhy** [comment]
@deadeyegoodwin Any updates here ?

**Comment by deadeyegoodwin** [comment]
The new backend API implementation has slipped somewhat. We plan to begin work on it in the next week or two. The preliminary API is available here: https://github.com/NVIDIA/triton-inference-server/commit/5c57c3708d3d9a2857df3d0ca5cc39864c43d478
