### ISSUE TITLE
How to to use model converted by torch2trt

### ISSUE THREAD

**Issue by ma-siddiqui** [NVIDIA/triton-inference-server#1264]
Hi, 
I have converted my torch model using https://github.com/NVIDIA-AI-IOT/torch2trt/

Please advise how can I use this model in trt inference server. I have two outputs after conversion:

1. Model_trt.pth
2. Engine.bin

Please advise, how to use any of the above model in trt inference server.

Thanks,

**Comment by GuanLuo** [comment]
I don't think the two generated files you shown are pure TensorRT files (serialized engine with `.plan` suffix). This [issue](https://github.com/NVIDIA-AI-IOT/torch2trt/issues/212) and its [repro script](https://github.com/dhkim0225/reproduce-torch2trt-issue-212/blob/master/make_engine.py) demonstrates how to generate TensorRT model from torch2trt.

Besides that, Triton Inference Server also supports PyTorch model, so you don't have to convert your model to TensorRT model. See [here](https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/model_repository.html#pytorch-models) for detail

**Comment by ma-siddiqui** [comment]
Thank you very much. Really appreciate your response. I converted the pytorch model in same way (example mentioned in your response). 

I generated two models:
1. Model_trt.pth (torch.save(model_trt.state_dict(), '/home/trt_model.pth'))


2. Engine.bin 
(with open('/home/model/my_model/1/model.plan', 'wb') as f:
f.write(model_trt.engine.serialize()))

So as per your response,  my second model can be used in Tensorrt inference server. Please confirm if my understandings are correct.

Thanks,

**Comment by GuanLuo** [comment]
Yes, you should be able to use the second file as TensorRT model in Triton Inference Server. You may want to rename the file to `model.plan` so the `config.pbtxt` file can be autofilled. See this [section](https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/model_repository.html#tensorrt-models)

**Comment by ma-siddiqui** [comment]
Thank you. Will revert in case face any issue.

**Comment by GuanLuo** [comment]
Closing. Reopen if there are following issues.
