### ISSUE TITLE
Incorrect configuration on DockerFile 

### ISSUE THREAD

**Issue by 24hours** [NVIDIA/triton-inference-server#1269]
**Description**
Build fail when running `docker build --pull -t tritonserver .`

**TRTIS Information**
master branch latest patch 
commit a189285371374368493977a0fe2f729d4ddae37d

**To Reproduce**
run `docker build --pull -t tritonserver .`
Docker will complain nvcr.io/nvidia/tensorrtserver:20.03-py3 not found 

**Expected behavior**
Build should run successfully 

https://github.com/NVIDIA/triton-inference-server/blob/master/Dockerfile#L31
should update into tritonserver:20.03-py instead of using old name, 

After editing the line, eventually this line would cause docker to fail. 
https://github.com/NVIDIA/triton-inference-server/blob/master/Dockerfile#L346

`returning non-zero status -1`

**Comment by dzier** [comment]
Thank you for bringing this to our attention. I will submit the fix. In the meantime, is there a reason you are building from master, rather than the latest release? If you checkout the `r20.03` branch and build the container, it will work successfully.

**Comment by dzier** [comment]
We have PR that will fix the issue (https://github.com/NVIDIA/triton-inference-server/pull/1275). Thank you for bringing this to our attention.

**Comment by 24hours** [comment]
I'm testing remote minio support which is not included in r20.03.
