### ISSUE TITLE
Question: Performance difference with Tensorflow Serving

### ISSUE THREAD

**Issue by turowicz** [NVIDIA/triton-inference-server#1270]
**Background**

I desperately need some help moving from direct Tensorflow API calls to any inference server solution.

I'm am feeding 1080p and 720p images taken from multiple CCTV cameras in real time to the inference server and I do need the performance to be on the level of of the direct calls. The inference computer has an RTX 2070, Ryzen 3600 and 16GB of RAM. Direct Tensorflow API calls take around 60ms.

I've initially migrated to Tensorflow Serving, but even on GRPC it appears to be around **6x SLOWER** than a direct Tensorflow call from my code. I would very much like the model management benefits of using an inference server and this is why I turn to you.

I really don't understand why TF Serving is so slow but to me it seems it's a problem directly related to their implementation of GRPC, Protocol Buffers and memory management. I am using the same model from Model Zoo (Faster R-CNN Inception V2) and I get a terrible slow performance in TF Serving. I did recompile the whole stack on the target computer to ensure all CPU/GPU optimisations.

**Question: Will implementing Nvidia Triton allow me to get close to the original direct Tensorflow performance?**

Otherwise it will not make sense to use an inference server :(

cc @deadeyegoodwin @GuanLuo

**Comment by turowicz** [comment]
PS. I also tried TensorRT optimisation in FP16 mode but it gave no performance improvements for none of the approaches (direct/serving)

**Comment by nieksand** [comment]
TF Serving is a different inference server from Nvidia's Triton.  Since you're here, I assume you are talking about the latter.

Looking at Triton's metrics endpoint is probably a good starting point.

There are also quite a few docs relevant to the topic.  For instance, if the RPC overhead is killing you there is a shared memory alternative: https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/optimization.html#shared-memory

**Comment by turowicz** [comment]
I just tried the Triton examples with my data and its as fast as direct API calls. I asked this question here because I was counting somebody would tell me to go for it. I did it anyway and it works well. Working on migrating to Triton now.

**Comment by turowicz** [comment]
> TF Serving is a different inference server from Nvidia's Triton. Since you're here, I assume you are talking about the latter.

I'm aware, that's why I came here for help. TF Serving was not working for me at all and I was considering switching to Triton.

**Comment by turowicz** [comment]
@nieksand I can happily confirm that having migrated away from TF Serving and setting up Triton has improved the timings to match very closely to the direct Tensorflow API calls.

**Comment by usernameandme** [comment]
@turowicz Is this with shared memory approach?

**Comment by turowicz** [comment]
Standard kubernetes deployment with an shm mount.

**Comment by turowicz** [comment]
Also make sure to set up the grafana metrics and optimize, optimize, optimize your code.
