### ISSUE TITLE
Encountered a non-existing input blob

### ISSUE THREAD

**Issue by bezero** [NVIDIA/triton-inference-server#1271]
**Description**
`nvcr.io/nvidia/tensorrtserver:20.03-py3` uses `nvcr.io/nvidia/pytorch:20.03-py3`. Using pytorch container I am able to run inference. However, when the model is
loaded inside tritonserver it gives following error:

I0405 14:13:17.096752 1 model_repository_manager.cc:680] loading: mrcnn50:20200315
I0405 14:13:17.096906 1 model_repository_manager.cc:735] CreateInferenceBackend() 'mrcnn50' version 20200315
I0405 14:13:17.472147 1 netdef_backend.cc:207] Creating instance mrcnn50_0_gpu0 on GPU 0 (6.1) using init_model.netdef and model.netdef
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
I0405 14:13:20.752836 1 netdef_backend.cc:99] ~NetDefBackend::Context
E0405 14:13:20.766669 1 model_repository_manager.cc:840] failed to load 'mrcnn50' version 20200315: Internal: load failed for 'mrcnn50': [enforce fail at operator.cc:75] blob != nullptr. op Cast: Encountered a non-existing input blob: data
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x67 (0x7f4c13427067 in /opt/tensorrtserver/bin/../lib/pytorch/libc10.so)
frame #1: caffe2::OperatorBase::OperatorBase(caffe2::OperatorDef const&, caffe2::Workspace*) + 0x6e5 (0x7f4c69ef8d95 in /opt/tensorrtserver/bin/../lib/pytorch/libtorch_cpu.so)

**TRTIS Information**
What version of TRTIS are you using?  **20.03-py3**
Are you using the TRTIS container or did you build it yourself? **container**

**To Reproduce**
I have a caffe2 mask rcnn with resnet50 model converted to caffe2 from detectron2. I did not provide the config file for this model. To debug I run the server with the following parameters:
`trtserver --model-repository=/models --strict-model-config=false --log-verbose=1`

**Expected behavior**
I was expecting the model to be loaded and config file auto-generated.

**Comment by CoderHam** [comment]
Was the model you produced a torchscript model? The pytorch backend supports execution via the C++ Pytorch API (LibTorch) which expects a torch_script.pt model. Read [here](https://pytorch.org/tutorials/advanced/cpp_export.html).

I am assuming you can the model using the PyTorch python API and hence did not see a similar failure.

**Comment by bezero** [comment]
This is the script I am using to load model and run inside `nvcr.io/nvidia/pytorch:20.03-py3` container.
```
from caffe2.proto import caffe2_pb2
from caffe2.python import core, workspace

init_net_path = 'init_model.netdef'
predict_net_path = 'model.netdef'


device_opts = core.DeviceOption(caffe2_pb2.CPU)
init_net = caffe2_pb2.NetDef()
with open(init_net_path, 'rb') as f:
	init_net.ParseFromString(f.read())
	init_net.device_option.CopyFrom(device_opts)

predict_net = caffe2_pb2.NetDef()
with open(predict_net_path, "rb") as f:
	predict_net.ParseFromString(f.read())
	predict_net.device_option.CopyFrom(device_opts)

c2w = workspace.Predictor(init_net, predict_net)
results = c2w.run({'data': img, "im_info": im_info})
```
Does `PyTorch/Caffe2 python API` differ from `PyTorch/Caffe2 C++ API`?
As I mentioned, I did not provide `config.pbtxt` file for tritonserver but I did set `--strict-model-config=false`.

**Comment by bezero** [comment]
After manually adding config file as follows:
```
name: "mrcnn50"
platform: "caffe2_netdef"
max_batch_size: 0
input [
        {
                name: "data"
                data_type: TYPE_FP32
                dims: [1, 3, 800, 800]
        },
        {
                name: "im_info"
                data_type: TYPE_FP32
                dims: [1, 1, 3]
        }
]
output [
        {
                name: "score_nms"
                data_type: TYPE_FP32
                dims: [10, 4]
        }
]
```
The `tritonserver` now gives another error:
```
E0408 19:08:26.786333 1 model_repository_manager.cc:840] failed to load 'mrcnn50' version 20200315: Internal: load failed for 'mrcnn50': [enforce fail at operator.cc:273] op. Cannot create operator of type 'CollectRpnProposals' on the device 'CUDA'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "529" input: "531" input: "533" input: "535" input: "537" input: "530" input: "532" input: "534" input: "536" input: "538" output: "rpn_rois" name: "" type: "CollectRpnProposals" arg { name: "rpn_max_level" i: 6 } arg { name: "rpn_min_level" i: 2 } arg { name: "rpn_post_nms_topN" i: 1000 } device_option { device_type: 1 device_id: 0 }
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x67 (0x7f8a2401b067 in /opt/tensorrtserver/bin/../lib/pytorch/libc10.so)
```
To solve this I forced model to be loaded on `CPU` by adding:
```
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
```
Now the model loads as expected. My conclusions:

1. For some reason, the `tritonserver` is not able to generate the config file automatically.
2. `tritonserver` forces the model to run on `CPU` or `GPU` device. It would be helpful, if some layers are allowed to run on `CPU` and others on `GPU`.

**Comment by CoderHam** [comment]
Have a look at this: #147
Some caffe2 models have ops that can only be run on CPU. Tritionserver tries to load/run the entire model on GPU and hence fails. We have marked this as an enhancement a while back. I would recommend converting the model to a torchscript and using our libtorch backend for now.

**Comment by deadeyegoodwin** [comment]
Or you can try exporting to ONNX as another route for your model. Keep in mind that Caffe2 APIs (that Triton relies on ) are deprecated: see https://caffe2.ai/blog/2018/05/02/Caffe2_PyTorch_1_0.html.
Triton itself is going to deprecate Caffe2 support starting in 20.05 and will remove it some months later... which means that new Caffe2-specific features are unlikely to be implemented.

**Comment by bezero** [comment]
Detectron2 provides onnx conversion via [export_onnx_model](https://detectron2.readthedocs.io/modules/export.html#detectron2.export.export_onnx_model). After converting to ONNX format and loading it to inference server I get this error:
```
failed to load /models/mrcnnR50_onnx/20200315/model.onnx: Internal: onnx runtime error 1: Fatal error: AliasWithName is not a registered function/op
``` 
The conversion method has a note:
`Note that the exported model contains custom ops only available in caffe2, therefore it cannot be directly executed by other runtimes. Post-processing or transformation passes may be applied on the model to accommodate different runtimes.`

So, to make this model work, I have to provide shared libraries for each `not registered function/op`. Is this how I can make it work?

**Comment by deadeyegoodwin** [comment]
It seems that the detectron2 onnx export is not as useful as it could be because it requires you to implement some ONNX custom operations on your own (perhaps someone has already done it and shared them?).

Unfortunately, even if you had the ONNX custom operations in the format required by ONNXRuntime (https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md), Triton is not yet able to use them as it does not yet have support for ONNX custom ops. It is on our roadmap...

**Comment by bezero** [comment]
Unfortunately, I don't have custom op implementations yet.
Thank you for the help, much appreciated!
