### ISSUE TITLE
GRPC version update

### ISSUE THREAD

**Issue by maaikez** [NVIDIA/triton-inference-server#1273]
**Description**
I download the prebuilt client library to my project. I want to use the same grpc version in my project, but I have a problem with the following 'bug': https://github.com/grpc/grpc/pull/18950

If the GRPC version would be updated, this would not be a problem anymore.

**TRTIS Information**
What version of TRTIS are you using?
1.12.0 / 20.03

Are you using the TRTIS container or did you build it yourself?
I am using the prebuilt client library tar.gz file from the release page.

**To Reproduce**
Use a glibc 2.30+ on your system
Install grpc version 1.19.1, which is used in the triton inference server as well, or add it to you project and build it yourself.
Download the client library and for example with CMakeLists, create a new executable which builds simple_client.cc.
Build the project.
You will now see the error "ambiguating new declaration of 'long int gettid()'" and are not able to build.

**Expected behavior**
I would like to be able to build the project without errors.

**Comment by deadeyegoodwin** [comment]
Titan 1.12.0 / 20.03 is using GRPC 1.19.0. https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/model_configuration.html#dynamic-batcher

**Comment by deadeyegoodwin** [comment]
Also, on the master branch we have move to GRPC 1.24.0. That update will be released in the 1.13.0 / 20.05 release near the end of May (note that we will not have a 20.04 release).

**Comment by maaikez** [comment]
That's great, then it will be fixed in that release (20.05). 

Yes I downloaded the client package of 20.03 built with 1.19.1, which is giving these errors.
