### ISSUE TITLE
Model loaded but  no input

### ISSUE THREAD

**Issue by ma-siddiqui** [NVIDIA/triton-inference-server#1276]
Hi,
I converted model and successfully loaded in inference server r20.03. I did not provide any configuration (config.pbtxt). On trt server console it does not show any input details. Only output names are shown. When I provide inputs (input_0) explicitly in config, model loading is failed with error invalid input.

Please advise how to troubleshoot it further and what is possible reason of this issue.

Thanks, 
Muhammad Ajmal Siddiqui

**Comment by GuanLuo** [comment]
What is the framework of your model? If you are using `--strict-model-config=false` to let Triton autofill the model config, the resulting config is depending on how much information the framework can provide. See [detail](https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/model_configuration.html#generated-model-configuration)

**Comment by ma-siddiqui** [comment]
Actually,  I converted model using torch2trt and cuda engine is being used as tensorrt_plan. Output nodes are shown but input nodes are not visible.

**Comment by ma-siddiqui** [comment]
Now facing the errors below:

[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_0
[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_1

Any thougts?

Thanks,
Muhammad Ajmal Siddiqui

**Comment by GuanLuo** [comment]
I think the model is not converted properly, I would suggest to open a ticket against torch2trt to verify.
