### ISSUE TITLE
unexpected shape for output  when output is 4 dims

### ISSUE THREAD

**Issue by CColten** [NVIDIA/triton-inference-server#1284]
trtis-19.10-py3

config is :
input [
    {
        name: "image_tensor"
        data_type: TYPE_FP32
        dims: [ -1, -1, 3 ]
    }
]
output [
   {
      name: "softmax_tensor"
      data_type: TYPE_FP32
      dims: [ 1, -1, -1, 2 ]
   } 
]

I run, the error is : 
failed to update context stat : [inference:0 20] ....  unexpected shape for output "softmax_tensor", model configuration shape is [1,-1,-1,2] , inference shape is [1,1280,720,2] 

i had tested 3 dims outpu, all are right. when load 4 dims output model, it 
occured

**Comment by deadeyegoodwin** [comment]
I think that the error message may be confusing. Can you share the model so that we can reproduce?

**Comment by CColten** [comment]
> I think that the error message may be confusing. Can you share the model so that we can reproduce?

thanks for your reply.
sorry for that , the model is in company-internal network， cannot share.

now, i have changed the network's output to 3 dims , that is ok.  

later, if i train in local , will share.
