### ISSUE TITLE
Spammy dynamic batching logs on 20.03

### ISSUE THREAD

**Issue by nieksand** [NVIDIA/triton-inference-server#1291]
**Description**
I'm running a validation script which pokes Triton sequentially with single requests.  Though I have dynamic batching of 4, the batches will never fill up and I expect the max delay to be hit.

For each request, I'm seeing the following output:
```
E0409 12:22:11.984376 1 dynamic_batch_scheduler.cc:571] Wait: 24949393 us
E0409 12:22:12.045072 1 dynamic_batch_scheduler.cc:571] Wait: 24936214 us
E0409 12:22:12.096045 1 dynamic_batch_scheduler.cc:571] Wait: 24934490 us
E0409 12:22:12.146333 1 dynamic_batch_scheduler.cc:571] Wait: 24937375 us
E0409 12:22:12.202828 1 dynamic_batch_scheduler.cc:571] Wait: 24922845 us
E0409 12:22:12.260220 1 dynamic_batch_scheduler.cc:571] Wait: 24929760 us
E0409 12:22:12.316441 1 dynamic_batch_scheduler.cc:571] Wait: 24928040 us
E0409 12:22:12.365843 1 dynamic_batch_scheduler.cc:571] Wait: 24973537 us
```

This level of detail seems more appropriate for verbose logging, not normal logging.

**Triton Information**
Triton 20.03 from NGC.

**To Reproduce**
Turn on dynamic batching, supply less input than full batch so max batch time is hit.

I happen to be using a TensorRT model with the following config:
```
platform: "tensorrt_plan"
dynamic_batching {
    preferred_batch_size: [ 4 ]
    max_queue_delay_microseconds: 25000
}
```

This is how I launched Triton:
```
docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 --gpus all -p8000:8000 -p8001:8001 -p8002:8002 -v /data/workspace/cape/models/sp2_trt/:/models/ -it nvcr.io/nvidia/tritonserver:20.03-py3 trtserver --model-store=/models/ --strict-model-config=false
```

**Expected behavior**
I would only expect dynamic batcher timing info if log-verbose is enabled.

**Comment by tanmayv25** [comment]
It should be fixed by [this ](https://github.com/NVIDIA/triton-inference-server/pull/1252) commit.
