### ISSUE TITLE
TRITON cannot access MINIO

### ISSUE THREAD

**Issue by maondra** [NVIDIA/triton-inference-server#1295]
**Description**
I did setup MINIO server and set policy on bucket to public. I have verified the access (event without secret key).

example setup MINIO:
`docker run -p 9000:9000 --name minio1 -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" -v /home/model_bucket:/data minio/minio server /data`

I am able to connect to MINIO using MINIO client:
`docker run -it --entrypoint=/bin/sh minio/mc`
`mc config host add minio http://xx.xxx.x.xxx:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY --api S3v4`

`mc --debug ls minio` //command works fine - list my buckets
I did setup public permission for my bucket:
`mc policy set download minio/inference/`

Works fine, I can access server using curl. (no secret key)

I tried to run TRITON:
`nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 -p8000:8000 -p8001:8001 -p8002:8002 nvcr.io/nvidia/tritonserver:20.03-py3 trtserver --model-repository=s3://xx.xxx.x.xxx:9000/inference/`

Error message:
`I0409 23:40:33.851714 1 server.cc:120] Initializing Triton Inference Server
error: creating server: INTERNAL - Could not get MetaData for bucket with name xx.xxx.x.xxx:9000
Failed to load. `

I have verified the connection to minio from 2 desktops (works fine).

Based on the documentation MINIO should be supported.

**Triton Information**
nvcr.io/nvidia/tritonserver:20.03-py3

Are you using the Triton container or did you build it yourself?
Container

**Expected behavior**
Connect to MINIO and sync models.

**Comment by CoderHam** [comment]
The error above describes a failure to recognize that the url is a MINIO s3 url. The above issue was resolved when we fixed the s3_regex to detect MINIO buckets from
`s3_regex("s3://([a-z]+):([0-9]+)/([0-9a-z.-]+)(((/[0-9a-zA-Z.-_]+)*)?)")` to
`s3_regex("s3://([0-9a-zA-Z-.]+):([0-9]+)/([0-9a-z.-]+)(((/[0-9a-zA-Z.-_]+)*)?)"` in this PR: https://github.com/NVIDIA/triton-inference-server/pull/1175

**Comment by deadeyegoodwin** [comment]
Fixed by #1175.
