### ISSUE TITLE
unable to load model 'face_graphdef', configuration expects 1 inputs, model provides at most 0

### ISSUE THREAD

**Issue by zhangluustb** [NVIDIA/triton-inference-server#1297]
unable to load model 'face_graphdef', configuration expects 1 inputs, model provides at most 0

**Triton Information**
20.03-py3
container

**Steps to reproduce the behavior.**
1 download face feature.pb model
2 config
name: "face_graphdef"
platform: "tensorflow_graphdef"
max_batch_size: 4
input [
  {
    name: "IteratorGetNext"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 112, 96, 3 ]
  }
]
output [
  {
    name: "l2_normalize"
    data_type: TYPE_FP32
    dims: [ 128 ]
  }
]
3 trtserver --model-repository=/models

**error:**
E0410 10:20:53.438208 823 model_repository_manager.cc:840] failed to load 'face_graphdef' version 1: Invalid argument: unable to load model 'face_graphdef', configuration expects 1 inputs, model provides at most 0

this error indicate that my PB model or the config has bug?
**Expected behavior**
successfully loaded 'face_graphdef' version 1

**Comment by deadeyegoodwin** [comment]
The error indicates that the model does not appear to have any inputs. For a graphdef that means that Triton could not find any placeholder nodes in the graph. Are you able to load this graphdef by using the TF python APIs directly?

**Comment by zhangluustb** [comment]
> The error indicates that the model does not appear to have any inputs. For a graphdef that means that Triton could not find any placeholder nodes in the graph. Are you able to load this graphdef by using the TF python APIs directly?

Thank you for your replying. I have tested on tensorflow python API and c++ API, they did good. In Triton server i just modified the extension format "pb" to "graphdef". Is that right?

**Comment by zhangluustb** [comment]
find the reason. 
tensorflow_backend_tf.cc:856
`if (node.op() == "Placeholder") {`
only support input node with Placeholder op.
I just convert graphdef to savemodel, it works.
