### ISSUE TITLE
How to send HTTP request to resnet50_netdef model using curl?

### ISSUE THREAD

**Issue by AliAzG** [NVIDIA/triton-inference-server#1305]
Hi.
I need to send an image to `resnet50_netdef` model and get response using HTTP and curl, but I don't how! I already saw these links:
#280 and https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-guide/docs/http_grpc_api.html#inference
yet, I don't know how they work.
my server is ready and I can send request from client docker and have response from there, but I made a request like this:
`curl -X POST localhost:8000/api/infer/resnet50_netdef -H "Content-Type: application/octet-stream" -H 'NV-InferRequest: batch_size: 1 input { name: "input" } output { name: "output" cls { count: 1 } }' --data-binary "@a_binary_image"`
but nothing happens!
I don't know exactly what this phrase mean: `NV-InferRequest: batch_size: 1 input { name: "input" } output { name: "output" cls { count: 1 } }` and how this can vary for different models?
can you give a hint or maybe an example for this model so I can understand how it works?
Thanks.

**Comment by deadeyegoodwin** [comment]
The NV_InferRequest header is the protobuf text of the request protobuf from src/core/api.proto. Most or all of the examples have a -v flag that you can use that should dump out the HTTP request/response that they are sending which should give you more examples to look at.

But if you want to be more forward looking you should look to be using the new V2 HTTP/REST protocol which will be available in the 20.05 release and become the only supported one in the 20.06 release (via the current schedule that you can read about here: https://github.com/NVIDIA/triton-inference-server#roadmap. There are pointers to the KFServing page describing the new JSON-based HTTP/REST protocol (at least the core part, Triton has several extensions that we will be posting the docs for soon). Right now on master the new HTTP/REST V2 protocol is supported at alpha quality. You can try it by using --api-version=2 when you start the server.
