### ISSUE TITLE
the return value of the function named 'parse_model_http' in  v2_image_client.py

### ISSUE THREAD

**Issue by rithd** [NVIDIA/triton-inference-server#1326]
line 164:

return (input_metadata['name'], output_metadata['name'], c, h, w,
            "FORMAT_NHWC", input_metadata['datatype'])

Why does it return "FORMAT_NHWC" instead of "input_config['format']"

**Comment by GuanLuo** [comment]
@CoderHam Can you take a look? I think it is a bug, the gRPC counterpart uses `input_config[format]`.

**Comment by CoderHam** [comment]
Fixed by #1342
