### ISSUE TITLE
Got a problem in autofilling model config

### ISSUE THREAD

**Issue by rithd** [NVIDIA/triton-inference-server#1328]
Here is the log of autofilling a tf-savedmodel model. And finally the server cannot be started because of this model. It is a non-batching model and the input shape is [].

I0417 10:05:20.585237 22393 autofill.cc:140] TensorFlow SavedModel autofill: OK:
I0417 10:05:20.585270 22393 model_config_utils.cc:307] autofilled config: name: "inception_flower"
platform: "tensorflow_savedmodel"
input {
  name: "myInput"
  data_type: TYPE_STRING
  dims: 1
  reshape {
  }
}
output {
  name: "myOutput"
  data_type: TYPE_FP32
  dims: -1
  dims: 5
}
default_model_filename: "model.savedmodel"

E0417 10:05:20.596050 22393 model_repository_manager.cc:1570] model input cannot have empty reshape for non-batching model for inception_flower

**Comment by GuanLuo** [comment]
What Triton version are you using? It seems like the max_batch_size field is not auto-filled...

**Comment by rithd** [comment]
r20.05.And here is my model.

https://bj-cmri.bj.bcebos.com/inception_v3.zip

**Comment by deadeyegoodwin** [comment]
Do you mean r20.03? r20.05 is not released yet and the README clearly states it is not useable.

**Comment by rithd** [comment]
both r20.03 and r19.12 occured this problem

**Comment by rithd** [comment]
Have you downloaded the model? The storage service costs money so I will remove it if you have downloaded it :) @deadeyegoodwin @GuanLuo

**Comment by GuanLuo** [comment]
@rithd Sorry for not following up with the issue, I have downloaded the model and will look into it.

**Comment by GuanLuo** [comment]
I tried to print out the model I/O of the model and it seems like the input has no shape. Is the input a scalar? If so, you will need to wrap it to a tensor as Triton doesn't support scalar input.

```
TF input: myInput; rank: 0; dims: []
TF output: myOutput; rank: 2; dims: [-1 5 ]
```

**Comment by rithd** [comment]
The input is a raw image with the shape of [], and it doesn't support batch inference. So the Triton's  feature reshape is inefficiency in this situation?

**Comment by GuanLuo** [comment]
Correct, because Triton doesn't support scalar input. The reshape to [] only works for model that supports batching, as in that case the input is still a tensor (i.e. full shape is `[batch_size]`).

**Comment by rithd** [comment]
So if my model have a image input, either the image input have at least 3 dims ( hwc or chw) , or the model can support batching with the input of a raw image if I want to deploy it in Triton?

**Comment by rithd** [comment]
And i also have a question, whether the "format" field is necessary for Triton's model config? If the user already know the order of c,h,w?

**Comment by GuanLuo** [comment]
You just need to modify your model to accept a tensor instead of a scalar as input, there is a custom backend for image preprocessing and its model [config](https://github.com/NVIDIA/triton-inference-server/blob/master/docs/examples/ensemble_model_repository/image_preprocess_nchw_3x224x224_inception/config.pbtxt) for input is similar to your model's.

the format is optional

**Comment by rithd** [comment]
Get it, thx
