### ISSUE TITLE
Is there a Rest API version of Triton Client ?

### ISSUE THREAD

**Issue by whatdhack** [NVIDIA/triton-inference-server#1329]
**Description**
The python client works  fine on Ubuntu  after some non-pip installs (e.g.  riton-inference-server/src/clients/python/api_v1/library/tensorrt-clients/python/tritongrpcclient-1.12.0-py3-none-linux_x86_64.whl). But does not work on other Linux such as Fedora etc.  Seeing the following error. Such platform dependent issues  could be avoided if the Rest API is exposed  and documented, 

```
libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Triton Information**
What version of Triton are you using? 20.3

Are you using the Triton container or did you build it yourself? Container

**To Reproduce**
Try the Python client on a RedHat type of Linux.  It is coming from the following shared object.

```
triton-inference-server/src/clients/python/api_v1/library/tensorrt-clients/lib/librequest.so
```

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
Should not see a low level library issue on Jupyter Notepad.

**Comment by deadeyegoodwin** [comment]
If you look in the Roadmap section (recently updated) of the README you will see the progress and plan for Triton 2.0.0. Triton 2 includes a new HTTP/REST protocol that is JSON-based and also new python clients that are "pure python" and so should be more universal across OSes. They are in alpha quality on master branch so you can try them now.

**Comment by whatdhack** [comment]
Sounds good.  In the meanwhile, is the following functional ? 

https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/http_grpc_api.html

**Comment by deadeyegoodwin** [comment]
Yes, the current HTTP protocol is described there (not very extensively). It is "non-standard"... one motivation to moving to the new HTTP/REST protocol is to have a more standard solution.

**Comment by whatdhack** [comment]
Agree the current Rest API syntax is pretty  unusual for parsing - it is certianly not JSON. The NV-InferResponse comes in a form as follows.  What format is it in  ?  Is there any Python package that can easily parse this ? 

```
'model_name: "model_name" model_version: 1 batch_size: 1 output { name: "output/boxes:0" raw { dims: 78 dims: 4 batch_byte_size: 1248 } } output { name: "output/labels:0" raw { dims: 78 batch_byte_size: 624 } } output { name: "output/scores:0" raw { dims: 78 batch_byte_size: 312 } }'
```
