### ISSUE TITLE
Passing S3 Credentials as Env Vars

### ISSUE THREAD

**Issue by dcyoung** [NVIDIA/triton-inference-server#1331]
**Description**
The server is able to leverage an s3 model repository if the `~/.aws` directory is provided as a mounted volume, but appears to error out if provided the same credentials as environment variables. I'm hoping this is simple user error or that an easy fix exists, as our deployments rely on kubernetes secrets injected as environment variables.

**Triton Information**
20.03

Are you using the Triton container or did you build it yourself?
provided container

**To Reproduce**
If I create the following files:
~/.aws/credentials
```
[default]
aws_access_key_id=<access_key>
aws_secret_access_key=<secret_key>
```
and
~/.aws/config
```
[default]
region=us-west-1
```
Then this works:
```bash
docker run \
--gpus all \
--rm \
--shm-size=1g \
--ulimit memlock=-1 \
--ulimit stack=67108864 \
-p8000:8000 \
-p8001:8001 \
-p8002:8002 \
-v /home/user/.aws/:/root/.aws \
nvcr.io/nvidia/tritonserver:20.03-py3 trtserver \
--api-version=2 \
--model-repository=s3://my-bucket/test-model-repository
```

However, this does not work:
```bash
docker run \
--gpus all \
--rm \
--shm-size=1g \
--ulimit memlock=-1 \
--ulimit stack=67108864 \
-p8000:8000 \
-p8001:8001 \
-p8002:8002 \
-e AWS_ACCESS_KEY_ID=<access_key> \
-e AWS_SECRET_ACCESS_KEY=<secret_key> \
-e AWS_DEFAULT_REGION=us-west-1 \
nvcr.io/nvidia/tritonserver:20.03-py3 trtserver \
--api-version=2 \
--model-repository=s3://my-bucket/test-model-repository
```
and instead produces the following error:

```bash
error: creating server: INTERNAL - Could not get MetaData for bucket with name my-bucket
```

Printing the environment shows that the env vars are correctly injected and present in the running container. That is, running

```bash
docker run \
--gpus all \
--rm \
--shm-size=1g \
--ulimit memlock=-1 \
--ulimit stack=67108864 \
-p8000:8000 \
-p8001:8001 \
-p8002:8002 \
-e AWS_ACCESS_KEY_ID=<redacted> \
-e AWS_SECRET_ACCESS_KEY=<redacted> \
-e AWS_DEFAULT_REGION=us-west-1 \
nvcr.io/nvidia/tritonserver:20.03-py3 env | grep '^AWS'
```
shows

```bash
AWS_SECRET_ACCESS_KEY=<redacted>
AWS_DEFAULT_REGION=us-west-1
AWS_ACCESS_KEY_ID=<redacted>
```

**Expected behavior**
I would expect the server to access the model repository if the credentials are provided as environment variables.

**Comment by CoderHam** [comment]
Sure, we will work allowing the user to pass S3 credentials as ENV variables. As an alternative you can use: 
```
aws configure set default.region us-west-1 && \
    aws configure set aws_access_key_id '<>' && \
    aws configure set aws_secret_access_key '<>'
```

**Comment by dcyoung** [comment]
Thanks for the quick reply! Glad to hear a solution is coming.

I'm not sure I follow the provided alternative. Could you elaborate on where you run this command, given the default entrypoint?

**Comment by CoderHam** [comment]
You can run these bash commands just before you start the trtserver so it would look like something like this:
```
...
nvcr.io/nvidia/tritonserver:20.03-py3 aws configure set default.region us-west-1 && \
aws configure set aws_access_key_id '<>' && \
aws configure set aws_secret_access_key '<>' && \
trtserver \
--api-version=2 \
...
```

**Comment by CoderHam** [comment]
Fixed by https://github.com/NVIDIA/triton-inference-server/pull/1359

**Comment by dcyoung** [comment]
Thanks!
