### ISSUE TITLE
 unable to load model  'bert', tensor 'input_ids': the model expects 1 dimensions but the model configuration specified 2 dimensions

### ISSUE THREAD

**Issue by laohur** [NVIDIA/triton-inference-server#1338]
**how to support batchsize for onnx?**

- use bert from [https://github.com/huggingface/transformers](url), 
- fellow [https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/bert#export-a-bert-model-from-pytorch](url). 

- gotten "model.onnx" with batchsize as first dim (netron).

i set `dynamic_batching {
  preferred_batch_size: [ 4, 8, 32 ]
  max_queue_delay_microseconds: 100
}` in "config.pbtxt"

wrong
`max_batch_size : 1024
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [-1, 128]
  }
]`

wrong `max_batch_size : 1024
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [1, 128]
    reshape: { shape: [-1,128 ] }  
  }
]`

ok`
max_batch_size : 1024
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [128]
  }
]`

all latest two version.

**Comment by GuanLuo** [comment]
The "ok" config you posted is how to support batch size. The `dims` in I/O is the shape that excludes batch dimension. To reiterate on your model example, the full shape of the input is [-1, 128] and you know that the first dimension is batch dimension, so your model config will be specified with `max_batch_size` to a non-zero value as the max batch size that the model should allow for one execution, and input with `dims: [128]` to specify the input dimension in each batch.

See [detail](https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/model_configuration.html)

**Comment by laohur** [comment]
> 
> 
> The "ok" config you posted is how to support batch size. The `dims` in I/O is the shape that excludes batch dimension. To reiterate on your model example, the full shape of the input is [-1, 128] and you know that the first dimension is batch dimension, so your model config will be specified with `max_batch_size` to a non-zero value as the max batch size that the model should allow for one execution, and input with `dims: [128]` to specify the input dimension in each batch.
> 
> See [detail](https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/model_configuration.html)

config.pbtxt
> name: "multibert"
platform: "onnxruntime_onnx"
max_batch_size : 1024
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ 128]
  }
]
output [
  {
    name: "last_hidden_state"
    data_type: TYPE_FP32
    dims: [ 128, 768 ]
  },
    {
    name: "pooler_output"
    data_type: TYPE_FP32
    dims: [ 768 ]
  }
]
dynamic_batching {
  preferred_batch_size: [ 4, 8, 32 ]
  max_queue_delay_microseconds: 100
}

got

> tensorrtserver.api.InferenceServerException: [inference:0 1323] unexpected shape for input 'input_ids' for model 'multibert'. Expected [128], got [1,128]


>

**Comment by GuanLuo** [comment]
How do you send the request to the server? I would check on the shape of the input sent to the server.

**Comment by laohur** [comment]
> 
> 
> How do you send the request to the server? I would check on the shape of the input sent to the server.

send[batchsize,128]. 
triton only support [128]?

**Comment by GuanLuo** [comment]
It will be helpful if you can provide a code snippet to show how do you send the request, and whether you are using the provided client library. Without further information, I can't tell whether you were sending the request as you intended. If you are using our client library, see [here](https://github.com/NVIDIA/triton-inference-server/blob/master/src/clients/python/api_v1/library/__init__.py#L1521-L1525) to check if you are forming the batch properly.

**Comment by laohur** [comment]
> provide

is there any example? it is confusing for me.

input_ids=ndarray(batchsize,128)
failed:
`        result = self.infer_ctx.run({'input_ids': (input_ids,)},
                                    {'last_hidden_state': InferContext.ResultFormat.RAW,
                                     'pooler_output': InferContext.ResultFormat.RAW}, batch_size)`

should i change input to   {'input_ids': [nd_example1,nd_example2 ]}   ?

**Comment by GuanLuo** [comment]
That is interesting, is your native number obtained by running with ONNX Runtime directly? Can you try a newer version of Triton (20.03), we had a fix to use ONNX Runtime default optimization level, which may affect the model performance.

**Comment by laohur** [comment]
> 
> 
> That is interesting, is your native number obtained by running with ONNX Runtime directly? Can you try a newer version of Triton (20.03), we had a fix to use ONNX Runtime default optimization level, which may affect the model performance.
have not download Triton (20.03) yet.
ENV: docker,tesla, cuda10.2,  bert model,ft32,
tps1: native pytorch, torch.load
tps2: onnx,  trtis server20.01+client http+dynamic batch

tps1/tps2 =10+

**Comment by deadeyegoodwin** [comment]
How are you testing your model in each case? Is the native pytorch receiving requests via HTTP?
Have you run perf_client against your model to get performance?

**Comment by laohur** [comment]
> perf_client

triton20.03，  python thread and process pool， http end2end time cost。
native30ms per request。
set various delay and batchsize，trtis reach the native speed for low concurrent。
trtis throws error asblow on process concurrent：

>  in trtis_predict
    {'outputs': InferContext.ResultFormat.RAW}, len(texts))
  File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 1589, in run
    self._last_request_id = _raise_if_error(c_void_p(_crequest_infer_ctx_run(self._ctx)))
  File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 260, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: [ 0] HTTP client failed: Timeout was reached

**Comment by deadeyegoodwin** [comment]
We can't determine what is happening from that description. And this issue is closed. Can you open a new issue and provide instructions to reproduce the error (one error per issue). When we are able to reproduce the failure we will be able to determine the problem and the fix.

**Comment by laohur** [comment]
> 
> 
> We can't determine what is happening from that description. And this issue is closed. Can you open a new issue and provide instructions to reproduce the error (one error per issue). When we are able to reproduce the failure we will be able to determine the problem and the fix.
[here](https://github.com/NVIDIA/triton-inference-server/issues/1378)

still confused about the performance。why native so fast？！triton is specific for infer!
trtis, trt，onnxruntime, torchserve,.. which perform best,especially for [nemo](https://github.com/NVIDIA/NeMo/issues/595)?
