### ISSUE TITLE
batch size >1 cann't speed in inference

### ISSUE THREAD

**Issue by loveppdog** [NVIDIA/triton-inference-server#1349]
batch size >1 and run time is just one sample time * batchsize。
It seems unuseable for batch size to speed up.
(test in triton inference19.07)

How to modify this issue?

code:

options->SetBatchSize(batchSize);
for (const auto& output : ctx->Outputs()) {
	options->AddRawResult(output);
}
FAIL_IF_ERR( ctx->SetRunOptions(*options), "unable to set inference options");

for (int i = 0; i < batchSize; i++) {
	FAIL_IF_ERR((*iterContex)->SetRaw(reinterpret_cast<uint8_t*>(&(*iterData)[0]), (*iterData).size() * sizeof(float)),"unable to set data for DATAINPUT");
				}
FAIL_IF_ERR(ctx->Run(&results), "unable to run model");

**Comment by loveppdog** [comment]
I test on 1080TI/2080TI and the same result.

**Comment by deadeyegoodwin** [comment]
You haven't given enough information for us to determine what could be going wrong. What is your model? Do you have some other reason to believe that batching should improve throughput (it usually does but is not guaranteed).

Have you tried running perf_client on your model with different batch size settings? https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/optimization.html#perf-client

**Comment by loveppdog** [comment]
I use image_client.cc with resnet50 model to test on 2080TI (code and model from trtion inference server git).  The batchsize seems unuseful just I said before.
But I see some info from internet about ResNet50 Performance(@P4+Default clock) the batchsize can speed quickly.
(https://zhuanlan.zhihu.com/p/35657027)

Pef_client use AsyncRun and can speed of course but we use the sync Run.

**Comment by deadeyegoodwin** [comment]
image_client is just an example and isn't necessarily designed to show high performance or measure performance across different configuration. You should use perf_client for that as explained in the documentation. RN50 should benefit significantly from batching, either done by the client or by using Triton's dynamic batcher.

**Comment by loveppdog** [comment]
I use perf_client to test our models with different batchsize. I find some issue:
(1)When batchsize=1 and GPU-Util shows <50%(nvidia-smi), the model will be benefit with different batchsize.
In this scene: with batchsize>1 GPU-util is just the same as batchsize=1 and not increase more obviously.
(2)When batchsize=1 and GPU-Util shows >50%, the model will not be benefit with different batchsize.

Can you explain the reason when GPU-util >50%, batchsize unuseful?
