### ISSUE TITLE
is it possible to downgrade to cuda-10.1?

### ISSUE THREAD

**Issue by qibaoyuan** [NVIDIA/triton-inference-server#1350]
My server does not support  cuda runtime 10.2 which is default in triton-server 20.03. Any idea to downgrade to cuda-10.1 and still run triton-server 20.03?

**Comment by deadeyegoodwin** [comment]
You cannot install CUDA 10.2 on your system? It is unlikely that Triton 20.03 will work on a non-10.2 system. You could try looking in the release notes for an older version of Triton that is compatible with 10.1. It looks like 19.10 might work... 
https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-10.html#rel_19-10
