### ISSUE TITLE
OOMs on enabling multiple TF MaskRCNN models with FP16 optimization

### ISSUE THREAD

**Issue by whatdhack** [NVIDIA/triton-inference-server#1351]
**Description**
OOM errors are thrown when multiple MaskRCNN models are enabled and run.

**Triton Information**
Trinton container 20.3

**To Reproduce**
Enable multile TF MaskRCNN model with FP16 optmization and start invoking them. 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
Not OOM ?

**Comment by deadeyegoodwin** [comment]
OOM when? At load time? When you run inference? Can you provide some more details.

**Comment by whatdhack** [comment]
OOM happens during inference when lots of TensorRT related nodes are created.

**Comment by deadeyegoodwin** [comment]
So it sounds like you are using a TF model and enabling TensorRT optimization on that model. TF, with or without the TRT optimization) dynamically allocates GPU memory during inference. So if you have too many model instances they may load correctly but if you try to use them all for inferencing simultaneously their dynamic memory allocation requirements will exceed GPU memory. In this case you should just see some of the inferences fail. Is that what you are seeing or are you seeing triton crash. If it is crashing can you provide the stack trace.

**Comment by whatdhack** [comment]
Here is part  of the log.  Looks like the issue is with TensorRT, not the inference server. Here is a previous study I did with TensorRT which identified a few issues  t(https://medium.com/@whatdhack/neural-network-inference-optimization-8651b95e44ee ). 

```

020-04-25 21:40:41.172714: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 1 Chunks of size 2279997440 totalling 2.12GiB
2020-04-25 21:40:41.172718: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 1 Chunks of size 2283209216 totalling 2.13GiB
2020-04-25 21:40:41.172722: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 1 Chunks of size 2605711872 totalling 2.43GiB
2020-04-25 21:40:41.172728: I tensorflow/core/common_runtime/bfc_allocator.cc:921] Sum Total of in-use chunks: 9.52GiB
2020-04-25 21:40:41.172734: I tensorflow/core/common_runtime/bfc_allocator.cc:923] total_region_allocated_bytes_: 14246195968 memory_limit_: 14246196020 available bytes: 52 curr_region_allocation_bytes_: 17179869184
2020-04-25 21:40:41.172744: I tensorflow/core/common_runtime/bfc_allocator.cc:929] Stats:
Limit:                 14246196020
InUse:                 10227049216
MaxInUse:              11236244224
NumAllocs:                   13595
MaxAllocSize:           3375890432

2020-04-25 21:40:41.172895: W tensorflow/core/common_runtime/bfc_allocator.cc:424] *********************************______********************__________***____****__******************
2020-04-25 21:40:41.172915: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger Requested amount of GPU memory (2279997440 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
2020-04-25 21:40:41.172928: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger /home/jenkins/workspace/TensorRT/helpers/rel-7.0/L1_Nightly/build/source/rtSafe/resources.h (164) - OutOfMemory Error in GpuMemory: 0
2020-04-25 21:40:41.172987: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger Out of memory error during getBestTactic: (Unnamed Layer* 0) [Shuffle]
I0425 21:40:50.414283 2644 server.cc:224] Polling model repository
```

**Comment by whatdhack** [comment]
Is there a way to find out the  memory consumption  per model  or even finer  in the inference server ?

**Comment by deadeyegoodwin** [comment]
2GB is a big allocation. I'm not sure if that is expected from your model or not but you need to follow-up at https://github.com/NVIDIA/TensorRT with an issue to hear from the TensorRT project.

As I mentioned above the memory use of a model can vary across loading and inferencing. In general Triton has no way to determine which models are using which and how much GPU memory.

**Comment by benjaminhon** [comment]
@deadeyegoodwin hope you can advice on this situation i have, im currently deciding if converting my Tensorflow models into TensorRT

My Current Situation:

i have about 20+ tensorflow graphdef models, and they are all loaded into one 2080ti. So Far everything works well, the TF backend can grow and shrink the memory when running the models

However Im considering converting the models to TensorRT for better optimizations, however i tested with just 1 model, after conversion its already 2GB. Considering this, im guessing that i can only load about 6+ TensorRT models compared to 20+ Tensorflow models.

It seems that Tensorflow can load more models because they do some internal unloading/loading in the backend? however TensorRT reserves everything at the start?

What happens if i load more TensorRT models than the GPU has, will TensorRT do some sort of scheduling such as loading/unloading the models when called?

It would greatly help before i start to convert all my other models to TensorRT

Thanks!

**Comment by deadeyegoodwin** [comment]
TF does not do internal loading and unloading. TRT allocates all memory that it needs at load time, allocating enough memory to handle the maximum batch size you specified when creating the model. That can explain why you see a 2GB memory requirement for the TRT model... what batch size are you using? If you run a request with that same batch size through Triton using the TF model  what memory allocation do you see (using nvidia-smi)? TF does allocation at request time, so if no requests are in flight it will likely use less memory than TRT.

**Comment by deadeyegoodwin** [comment]
Closing as this issue seems to be TensorRT related.

**Comment by whatdhack** [comment]
@deadeyegoodwin , thanks for the pointer. By the way,  looks like TFServe is convinced of the benefit of FP16, hence I think it will be there in the near future.  Is Triton dependent  in any way  on TFServe ?  As I understand TensoRT is just part of Triton, and Triton does not have to use TensorRT.   Hence if Trinton is not dependent on TFServe, then would there be a way to bring just FP16 to Triton ?

**Comment by deadeyegoodwin** [comment]
The benefits of fp16 for inference are well known so it would be great if they provided an option for it. By TFServe I assume you mean TFServing. Triton does not depend on it in any way... Triton directly uses the TF libraries to execute TF models. TensorRT is an independent project (https://developer.nvidia.com/tensorrt). Triton uses TensorRT library to execute TensorRT models in the say way it uses the TF (or pytorch or onnx runtime) library to execute those models.

Triton does support different optimization options via the model configuration, but a given model framework must expose a way to use that optimization. Triton does not implement a way to run a TF model... it depends on the TF framework libraries for that... so Triton cannot enable any optimization that is not supported by the framework library.
