### ISSUE TITLE
Version number 01  fails to load.

### ISSUE THREAD

**Issue by whatdhack** [NVIDIA/triton-inference-server#1366]
**Description**
Version number 01  seems to not load. Changing to 1 works. 

**Triton Information**
Container 20.03

**To Reproduce**
Should be trivial to reproduce. 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
Load  model with version number starting 0 as first digit.

**Comment by GuanLuo** [comment]
We intentionally ignore version directory with leading zeros and log warning appropriately if that occurs. The reason is to avoid ambiguity on loading versions (i.e. load "01" or "1"?)

**Comment by whatdhack** [comment]
This may sound frivolous - what is the ambiguity between the numbers 01 and 1 , unless you are treating them as strings rather then numbers ?

**Comment by GuanLuo** [comment]
Triton will treat them as numbers. With leading zeros, it is possible to have two version directories "01" and "1", and each directory has different model file. Triton sees both directories as version 1 and in such case it is not clear that which directory is the "correct" one to be loaded as version 1. By ignoring directories with leading zeros, we enforce that "1" will be loaded, and user should ensure the model file in "1" is the proper file for version 1.

**Comment by whatdhack** [comment]
Thanks  for the clarification - appreciate.
