### ISSUE TITLE
How to free GPU memory in perf_client

### ISSUE THREAD

**Issue by loveppdog** [NVIDIA/triton-inference-server#1370]
I use perf_client to test our models repository on RTX2080 (gpu mem 10989MiB) and when startup server with default way the GPU memory usage is 5000/9651MiB. 
When I perf_client with -b batchsize 32 , out of memory happens and GPU memory usage shows the 10989MiB all the time and I'll not run any example although the batchsize 1 unless restart server again.

How to free GPU memory when server is running? And Can you give me more information how to work the GPU memory? 

I know the server load models with three control modes: null/poll/ EXPLICIT. I use the default poll.

**Comment by tanmayv25** [comment]
Which framework does your models belong to? And are you using --shared-memory=cuda?

**Comment by loveppdog** [comment]
share-memory? I just run resnet50_netdef/inception_graphdef in examples by perf_client. 
I'm confused with the GPU-utils and GPU usage memory by nvidia-smi. I found the different batchsizes cannot effect the GPU-utils, why?

my triton server:19.07 and triton client sdk:19.10.

**Comment by deadeyegoodwin** [comment]
The first thing you should do is update to 20.03 for both client and server, the versions you are using are fairly old.

Depending on you model framework some GPU memory is required at load time and some each time you request and inference. How much memory is needed will depend on the batch size, larger batch sizes require more GPU memory. As to why you cannot perform inference after running out of GPU memory we need to know more about what framework you are using.

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if new information is available.
