### ISSUE TITLE
perf_client batchsize -b issue

### ISSUE THREAD

**Issue by loveppdog** [NVIDIA/triton-inference-server#1372]
I use perf_client to test our models with different batchsize. I find some issue:
(1)When batchsize=1 and GPU-Util shows <50%(nvidia-smi), the model will be benefit with different batchsize.
In this scene: with batchsize>1 GPU-util is just the same as batchsize=1 and not increase more obviously.
(2)When batchsize=1 and GPU-Util shows >50%, the model will not be benefit with different batchsize.
Can you explain the reason when GPU-util >50%, batchsize unuseful?

(our model config instance_group is default)

**Comment by deadeyegoodwin** [comment]
There could be something other than GPU utilization that is limiting your performance. Perhaps your input tensors are very large and so the bottleneck is network or PCIe bandwidth. Have you tried looking at the overhead breakdown provided by perf_client or use a profiling tool like Nsight Systems?

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if necessary.
