### ISSUE TITLE
Allow customization of cuda sync behavior

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/triton-inference-server#1385]
**Is your feature request related to a problem? Please describe.**
I use triton with multiple TensorRT models, with multiple instances each on a server with multiple GPUs, and a 20-Core Xeon CPU. When the server is under heavy load, such that all GPUs are under very high utilization, I noticed that triton also utilizes the CPU at its limit (all 40 cores with hyper threading). This seemed suspicious to me, and it turns out that the reason is the cuda synchronization behavior. When I call `cudaSetDeviceFlags(cudaDeviceScheduleBlockingSync)` the CPU load drops by 60%. Setting the event flags to `cudaEventBlockingSync | cudaEventDisableTiming` here :https://github.com/NVIDIA/triton-inference-server/blob/626689bcc1093a3fc902406a5f5dd310bd80098f/src/backends/tensorrt/plan_backend.cc#L53
reduces the CPU load by another 30-40%. With these modifications, triton can drive the four GPUs of the server close to maximum utilization with at most  900% CPU utilization (out of 40000%). 

I know these scheduling modifications have an impact on host<->device latency, but in my experiments, the overall throughput of triton is only reduced by 3-5%. 

Depending on use cases, this might be a reasonable trade off (for me it is), as it allows deployment of other CPU services on the server. Are there any drawbacks that you know of?

**Describe the solution you'd like**
Configuration flags to determine the scheduling mode and the event flags.

**Describe alternatives you've considered**
`cudaSetDeviceFlags` has to be the first thing that is called on the primary cuda context for each device. I can do this comfortably hooking the server's main function using `LD_PRELOAD`. Unfortunately I was not able to intercept the call to `cudaEventCreateWithFlags` in `plan_backend.cc` in a similar manner. (As a side node: Using the `LD_PRELOAD` trick did intercept multiple calls to `cudaEventCreateWithFlags`, but not the ones from the triton code I quoted above. Apparently there are multiple distinct copies of this function in the triton runtime? Or triton links statically to parts of `libcudart`?)

**Comment by deadeyegoodwin** [comment]
Thanks for sharing your findings. I agree that it would be good to give some control over CPU usage given the significant difference you were able to measure. We will look into it for the 20.06 release.
