### ISSUE TITLE
Reduce Docker Image Size

### ISSUE THREAD

**Issue by miguelvr** [NVIDIA/triton-inference-server#1391]
**Is your feature request related to a problem? Please describe.**
The current docker image has a whopping 6.3Gb in size. This makes it more difficult to use in situations where the image has to be pulled often (e.g. Kubernetes KNative)

**Describe the solution you'd like**
Using multi-stage builds and smaller base images (e.g. cuda-base) or even having the NVidia Triton Server built for the required framework for the user might help a lot.

**Comment by deadeyegoodwin** [comment]
Triton does use a multi-stage build (see top-level Dockerfile). ~2GB of comes from CUDA and other "base" libraries, and 3GB comes from Triton and framework backend libraries. I think we could work on cutting down the CUDA/base overhead as there are some parts of that that Triton doesn't need. As for the framework backends... Triton currently supports 5 framework backends that have significant size so pre-building all possible combinations is not possible. We do provide build Dockerfile that makes it easy to build exactly what you need.

**Comment by jeisinge** [comment]
Cool!  I was not familiar with [Docker multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) before this.

Do you all publish the intermediary Docker images from your [Dockerfile](https://github.com/NVIDIA/triton-inference-server/blob/master/Dockerfile)?  If so, it would enable relatively easy and quick builds of just the runtimes used --- no compiling, just downloading partial images, and copying the specific files over to a custom Triton image.

**Comment by deadeyegoodwin** [comment]
We are working toward a re-arch of how Triton handles backends and a simple tool that would let you re-package the Triton container to contain only the backends you need. But that is some way off.

We do not publish all the intermediate docker images.  You should be able to just edit and run the Dockerfile to include only those backends you are interested in. The documentation has a section on building Triton.
