### ISSUE TITLE
fasterrcnn_resnet50_fpn TorchScript model cannot be loaded

### ISSUE THREAD

**Issue by adamm123** [NVIDIA/triton-inference-server#1415]
**Description**
Cannot load FasterRCNN model exported to TorchScript using Triton/TensorRTServer.
Follow-up #1313

**Triton Information**
What version of Triton are you using?
`nvcr.io/nvidia/tritonserver:20.03-py3`
`nvcr.io/nvidia/tensorrtserver:20.02-py3`

Are you using the Triton container or did you build it yourself?
`container`
**To Reproduce**

Pytorch container was used for exporting a model to TorchScript, then 
corresponding Triton/TensorRTServer container was used to load exported model.
Tried software versions:
| Pytorch Container | Triton Container | Result |
|--------------------------|-----------------------|------------------------------------------- |
| nvcr.io/nvidia/pytorch:20.03-py3 | nvcr.io/nvidia/tritonserver:20.03-py3 |  Failed to load the model |
| nvcr.io/nvidia/pytorch:20.02-py3 | nvcr.io/nvidia/tensorrtserver:20.02-py3 | Failed to load the model |
| nvcr.io/nvidia/pytorch:20.01-py3 | N/A | Failed to export the model |
| nvcr.io/nvidia/pytorch:19.12-py3 | N/A | Failed to export the model |

1. Export FasterRCNN model (in Pytorch container):
```python
import torch
import torchvision

model = torchvision.models.detection.fasterrcnn_resnet50_fpn()
model = model.eval()
script = torch.jit.script(model)
script.save('model.pt')
```
2. Prepare repository and copy model into it:
```
mkdir -p models/object_detection/1
cp model.pt models/object_detection/1
```
3. Run Triton/TensorRTServer(replace <path_to_model_repository> with correct path):
```
nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/<path_to_model_repository>/models:/models nvcr.io/nvidia/tritonserver:20.03-py3 trtserver --model-repository=/models --log-verbose=1 --strict-model-config=false
```
Running server results in following error:
```
inference_server_1  | E0506 06:54:57.221317 1 model_repository_manager.cc:840] failed to load 'od' version 1: Internal: load failed for libtorch model -> 'od': 
inference_server_1  | Unknown builtin op: torchvision::_new_empty_tensor_op.
inference_server_1  | Could not find any similar ops to torchvision::_new_empty_tensor_op. This op may not exist or may not be currently supported in TorchScript.
inference_server_1  | :
inference_server_1  |   File "/opt/conda/lib/python3.6/site-packages/torchvision/ops/new_empty_tensor.py", line 16
inference_server_1  |         output (Tensor)
inference_server_1  |     """
inference_server_1  |     return torch.ops.torchvision._new_empty_tensor_op(x, shape)
inference_server_1  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
inference_server_1  | Serialized   File "code/__torch__/torchvision/ops/new_empty_tensor.py", line 3
inference_server_1  | def _new_empty_tensor(x: Tensor,
inference_server_1  |     shape: List[int]) -> Tensor:
inference_server_1  |   _0 = ops.torchvision._new_empty_tensor_op(x, shape)
inference_server_1  |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
inference_server_1  |   return _0
inference_server_1  | '_new_empty_tensor' is being compiled since it was called from 'interpolate'
inference_server_1  | Serialized   File "code/__torch__/torchvision/ops/misc.py", line 24
inference_server_1  |     align_corners: Optional[bool]=None) -> Tensor:
inference_server_1  |   _1 = __torch__.torchvision.ops.misc._output_size
inference_server_1  |   _2 = __torch__.torchvision.ops.new_empty_tensor._new_empty_tensor
inference_server_1  |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
inference_server_1  |   _3 = uninitialized(Tensor)
inference_server_1  |   if torch.gt(torch.numel(input), 0):
inference_server_1  | 'interpolate' is being compiled since it was called from 'GeneralizedRCNNTransform.resize'
inference_server_1  | Serialized   File "code/__torch__/torchvision/models/detection/transform.py", line 78
inference_server_1  |     target: Optional[Dict[str, Tensor]]) -> Tuple[Tensor, Optional[Dict[str, Tensor]]]:
inference_server_1  |     _18 = __torch__.torchvision.models.detection.transform.resize_boxes
inference_server_1  |     _19 = __torch__.torchvision.ops.misc.interpolate
inference_server_1  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
inference_server_1  |     _20 = __torch__.torchvision.models.detection.transform.resize_keypoints
inference_server_1  |     _21 = uninitialized(Tuple[Tensor, Optional[Dict[str, Tensor]]])
inference_server_1  | 'GeneralizedRCNNTransform.resize' is being compiled since it was called from 'GeneralizedRCNNTransform.forward'
inference_server_1  |   File "/opt/conda/lib/python3.6/site-packages/torchvision/models/detection/transform.py", line 47
inference_server_1  |                                  "of shape [C, H, W], got {}".format(image.shape))
inference_server_1  |             image = self.normalize(image)
inference_server_1  |             image, target_index = self.resize(image, target_index)
inference_server_1  |                                   ~~~~~~~~~~~ <--- HERE
inference_server_1  |             images[i] = image
inference_server_1  |             if targets is not None and target_index is not None:
inference_server_1  | Serialized   File "code/__torch__/torchvision/models/detection/transform.py", line 28
inference_server_1  |         pass
inference_server_1  |       image0 = (self).normalize(image, )
inference_server_1  |       _2 = (self).resize(image0, target_index, )
inference_server_1  |                                  ~~~~~~~~~~~~ <--- HERE
inference_server_1  |       image1, target_index0, = _2
inference_server_1  |       _3 = torch._set_item(images0, i, image1)
```

**Expected behavior**

Triton can run inference of a fasterrcnn_resnet50_fpn TorchScript model.

**Comment by deadeyegoodwin** [comment]
This seems to be the problem:

inference_server_1  | Unknown builtin op: torchvision::_new_empty_tensor_op.
inference_server_1  | Could not find any similar ops to torchvision::_new_empty_tensor_op. This op may not exist or may not be currently supported in TorchScript.

The model requires an operation that is not available. This issue shows a similar problem https://discuss.pytorch.org/t/fasterrcnn-resnet50-jit-trace/62337/5

@CoderHam do we need to include some torchvision library to get support for the torchvision custom operations?

**Comment by CoderHam** [comment]
The detection models use ops that are not a part of pytorch. I believe the custom layer op needs to be compiled into a shared object and linked during runtime for now.
As mentioned [here](https://discuss.pytorch.org/t/limitations-of-torch-mobile-torchscript-object-detection-segmentation/70197
): "_Basic torchvision models are supported, but specialized ops for detection are currently not included._"
You should ideally open an issue with PyTorch for the same and get their recommendation on the best approach you should take to create the custom detection ops used in your model.
Can you confirm the Pytorch version you used to create that model?

**Comment by adamm123** [comment]
**As for Python:** 
I retired exporting, loading and running inference in Python using container:
```
NVIDIA Release 20.03 (build 11122848)
PyTorch Version 1.5.0a0+8f84ded
```

1. I run container as follows:
`docker run --gpus all -it --rm -v `pwd`:/model nvcr.io/nvidia/pytorch:20.03-py3`

2. Export model:
```python 
import torch
import torchvision

model = torchvision.models.detection.fasterrcnn_resnet50_fpn()
model = model.eval()
script = torch.jit.script(model)
script.save('model.pt')
```
3. Load and run model:
```python
import torch
import torchvision 

m = torch.jit.load('model.pt')
m = m.eval()
m([torch.zeros((3,200,300))])
```
Model loads and runs successfully. However, `import torchvision` is required. If `torchvision` is not imported torchviison ops cannot be loaded (same error as when loading in Triton).

So, it is possible in Python to export Faster RCNN model to TorchScript and then to load it and run inference.

**As for Triton:**
I guess Triton is using C++ libtorch. I found these two issues in Pytorch GitHub:
- https://github.com/pytorch/vision/pull/1843
- https://github.com/pytorch/vision/issues/1849

Maybe these issues solve the problem of loading Faster RCNN in Triton?

**Comment by deadeyegoodwin** [comment]
Thanks for the information. @CoderHam can you look into if there is now some way for us to build our libtorch support to include torchvision ops. Or perhaps we will get it when we update to a newer version of pytorch?

**Comment by adamm123** [comment]
Tried with:
Pytorch container `nvcr.io/nvidia/pytorch:20.03-py3`: 
```
NVIDIA Release 20.03 (build 11122848)
PyTorch Version 1.5.0a0+8f84ded
```
and Triton container `nvcr.io/nvidia/tritonserver:20.03.1-py3`:
```
NVIDIA Release 20.03.1 (build 12830698)
```
and there is no improvement. I get the same error when loading the model.

Are there any updates on including torchvision ops in the future?

**Comment by CoderHam** [comment]
We're working on having support for torchvision ops in the next release (20.07)

**Comment by CoderHam** [comment]
As the comment [here](https://github.com/pytorch/vision/pull/1407#issuecomment-562096191) mentions, fasterrcnn expects a List[Tensor] as input instead of a Tensor. You may have to write a wrapper around it for now since the Triton backend for LibTorch only supports inputs via a single **Tensor**/vector of **Tensors** and not **List of Tensors.**  The same is confirmed [here](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/faster_rcnn.py#L28-L29). The input is expected to be a list of tensors, each tensor representing one image.  

We may work on adding support for this in the future.

For now, with the changes from #1750, models with torchvision ops will successfully load and run with Trionserver (granted they accept inputs in the form of Tensors).

**Comment by adamm123** [comment]
Thank for adding support for Torchvision ops. I was able to load the model using `nvcr.io/nvidia/tritonserver:20.07-py3` and run inference on a CPU, however inference fails when running on a GPU. I described the problem in #1870

**Comment by scamianbas** [comment]
How to write a wrapper around it ?

**Comment by rxdcxdrnine** [comment]
Same error appears in r21.05
I got the following error.

```
E0629 09:42:15.210333 1 model_repository_manager.cc:1213] failed to load 'fasterRCNN' version 1: Internal: failed to load model 'fasterRCNN': 
Unknown builtin op: torchvision::_new_empty_tensor_op.
Could not find any similar ops to torchvision::_new_empty_tensor_op. This op may not exist or may not be currently supported in TorchScript.
:
  File "/opt/conda/lib/python3.6/site-packages/torchvision/ops/new_empty_tensor.py", line 16
        output (Tensor)
    """
    return torch.ops.torchvision._new_empty_tensor_op(x, shape)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
Serialized   File "code/__torch__/torchvision/ops/new_empty_tensor.py", line 3
def _new_empty_tensor(x: Tensor,
    shape: List[int]) -> Tensor:
  _0 = ops.torchvision._new_empty_tensor_op(x, shape)
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  return _0
'_new_empty_tensor' is being compiled since it was called from 'interpolate'
Serialized   File "code/__torch__/torchvision/ops/misc.py", line 28
  _2 = __torch__.torch.nn.functional.___torch_mangle_5.interpolate
  _3 = __torch__.torchvision.ops.misc._output_size
  _4 = __torch__.torchvision.ops.new_empty_tensor._new_empty_tensor
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  if torch.gt(torch.numel(input), 0):
    _6 = _2(input, size, scale_factor, mode, align_corners, None, )
'interpolate' is being compiled since it was called from '_resize_image_and_masks'
Serialized   File "code/__torch__/torchvision/models/detection/transform.py", line 212
    target: Optional[Dict[str, Tensor]]) -> Tuple[Tensor, Optional[Dict[str, Tensor]]]:
  _71 = __torch__.torch.nn.functional.___torch_mangle_4.interpolate
  _72 = __torch__.torchvision.ops.misc.interpolate
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  _73 = torch.slice(torch.size(image), -2, 9223372036854775807, 1)
  im_shape = torch.tensor(_73, dtype=None, device=None, requires_grad=False)
'_resize_image_and_masks' is being compiled since it was called from 'GeneralizedRCNNTransform.resize'
Serialized   File "code/__torch__/torchvision/models/detection/transform.py", line 80
    target: Optional[Dict[str, Tensor]]) -> Tuple[Tensor, Optional[Dict[str, Tensor]]]:
    _19 = "This Python function is annotated to be ignored and cannot be run"
    _20 = __torch__.torchvision.models.detection.transform._resize_image_and_masks
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _21 = __torch__.torchvision.models.detection.transform.resize_boxes
    _22 = __torch__.torchvision.models.detection.transform.resize_keypoints
'GeneralizedRCNNTransform.resize' is being compiled since it was called from 'GeneralizedRCNNTransform.forward'
  File "/opt/conda/lib/python3.6/site-packages/torchvision/models/detection/transform.py", line 93
                                 "of shape [C, H, W], got {}".format(image.shape))
            image = self.normalize(image)
            image, target_index = self.resize(image, target_index)
                                  ~~~~~~~~~~~ <--- HERE
            images[i] = image
            if targets is not None and target_index is not None:
Serialized   File "code/__torch__/torchvision/models/detection/transform.py", line 29
        pass
      image0 = (self).normalize(image, )
      _2 = (self).resize(image0, target_index, )
                                 ~~~~~~~~~~~~ <--- HERE
      image1, target_index0, = _2
      _3 = torch._set_item(images0, i, image1)

```
