### ISSUE TITLE
Sending some metrics from triton container

### ISSUE THREAD

**Issue by yasirofficial** [NVIDIA/triton-inference-server#1439]
Is there a way we can send some metrics from within the triton-inference-server container to the cloud, like sending the response time metrics so that the auto-scaling mechanism can work?

**Comment by nieksand** [comment]
Triton exposes latency metrics in Prometheus format:
https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/metrics.html

In AWS, you can stick Triton in an Autoscaling Group (ASG) fronted by an Application Load Balancer (ALB).  Use the ALB metrics to trigger ASG scale up/down events.
