### ISSUE TITLE
libpytorch backend occupies more gpu memory than pytorch

### ISSUE THREAD

**Issue by oisc** [NVIDIA/triton-inference-server#1441]
**Description**
I'm tring to serve huggingface bert model with trtserver. I convert the model to TorchScript format. Found out that I can only inference at max batch size of 5 above which will result an OOM error. 

**Triton Information**
20.03 docker @ RTX 2080TI

Are you using the Triton container or did you build it yourself?
Official docker image

**To Reproduce**
1. Convert huggingface bert model with torch.jit.trace
2. using `torch.jit.load` and `with torch.no_grad() ...`, I can load and run torchscript bert model at normal batch size witout OOM
3. serve model with trtserver, I can only inference at max batch size below 5

**Expected behavior**
Inference bert at normal batch size without OOM as pytorch

**Comment by oisc** [comment]
I solve it by manual set all parameters' `requires_grad` to `False`.
Pytorch jit don't trace torchscript with `torch.no_grad()` and neither trtserver's libpytorch backend have that option.

**Comment by CoderHam** [comment]
The correct way to trace the model for inference is to set requires_grad to False prior to tracing the model. Tritonserver used to load the model and always force requires_grad to False but this is known to cause some breakage in prior Pytorch versions.
