### ISSUE TITLE
failed to build triton-client

### ISSUE THREAD

**Issue by vandesa003** [NVIDIA/triton-inference-server#1453]
Hi there, I tried to build the triton-client based on the [tutorial](https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-guide/docs/client.html).
I ran 
```
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Release
$ make -j8 trtis-clients
```
But it shows the following error:
```
[ 63%] Completed 'grpc'
[ 73%] Built target grpc
CMakeFiles/Makefile2:81: recipe for target 'CMakeFiles/trtis-clients.dir/rule' failed
make[1]: *** [CMakeFiles/trtis-clients.dir/rule] Error 2
Makefile:118: recipe for target 'trtis-clients' failed
make: *** [trtis-clients] Error 2
```
I also noticed there is one similar [issue](https://github.com/NVIDIA/triton-inference-server/issues/531), but there is no solution.
After that I also tried docker build:
```
docker build -t tritonserver_client -f Dockerfile.client .
```
But I got following error:
```
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/a0/df/635cdb901ee4a8a42ec68e480c49f85f4c59e8816effbf57d9e6ee8b3588/setuptools-46.1.3-py3-none-any.whl (582kB)
Collecting grpcio-tools
  Downloading https://files.pythonhosted.org/packages/08/1d/8519e0ea749d0c9d10367e8391b3af9f7fe58979390de857d71e958a97c5/grpcio-tools-1.28.1.tar.gz (2.0MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-85en6oes/grpcio-tools/
The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends             software-properties-common             autoconf             automake             build-essential             cmake             curl             git             libopencv-dev             libopencv-core-dev             libssl-dev             libtool             pkg-config             python3             python3-pip             python3-dev             rapidjson-dev &&     pip3 install --upgrade wheel setuptools grpcio-tools' returned a non-zero code: 1
```
At last I tried pre-built from github: `pip install tensorrtserver-1.11.0-py3-none-linux_x86_64.whl`. But after I ran `python image_client.py`, I got following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ldap_home/bohang.li/.conda/envs/pytorch1_3/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 57, in <module>
    _request = cdll.LoadLibrary(_request_path)
  File "/ldap_home/bohang.li/.conda/envs/pytorch1_3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/ldap_home/bohang.li/.conda/envs/pytorch1_3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libssl.so.1.1: cannot open shared object file: No such file or directory
```
Any suggestions or hints on this would be appreciated! Thanks!

**Comment by helloninglei** [comment]
1. for the "Built target grpc" failed ,  i think it's network issuce , u can try more times
2. from ModuleNotFoundError: No module named 'setuptools', u can add "RUN pip install setuptools" in Dockerfile.client
3. for pre-built from github can't find ibssl.so.1.1 and orther lib ,it's maybe because of different platform, i also got this issue. then it's best to build on your side.

**Comment by vandesa003** [comment]
@helloninglei Thanks for your reply. For the "Built target grpc" problem, I indeed tried a couple of times, but still got the same error.

**Comment by deadeyegoodwin** [comment]
@vandesa003 
For 1 you are not showing the actual error, you need to look farther up in the console output to see that. If you build with -j1 it will likely be easier to find.
For 2, setuptools is installed in Dockerfile.client (https://github.com/NVIDIA/triton-inference-server/blob/master/Dockerfile.client#L54) so I'm not sure why your system is not finding it. I have seen some pip3 weirdness where setuptools has to be install first, by itself, so you may need to edit Dockerfile.client in that way.
 For 3, what OS/platform are you trying to install on? The premade wheels are specifically for Ubuntu 16.04 and 18.04

**Comment by vandesa003** [comment]
> @vandesa003
> For 1 you are not showing the actual error, you need to look farther up in the console output to see that. If you build with -j1 it will likely be easier to find.
> For 2, setuptools is installed in Dockerfile.client (https://github.com/NVIDIA/triton-inference-server/blob/master/Dockerfile.client#L54) so I'm not sure why your system is not finding it. I have seen some pip3 weirdness where setuptools has to be install first, by itself, so you may need to edit Dockerfile.client in that way.
> For 3, what OS/platform are you trying to install on? The premade wheels are specifically for Ubuntu 16.04 and 18.04

Thanks @deadeyegoodwin ! I will try with -j1 for the first one.  And for the 3rd one, I installed on Ubuntu 16.04.

**Comment by nphilou** [comment]
Hey! I faced the same issue for `setuptools`:

Quick fix: 
Replace: 
`pip3 install --upgrade wheel setuptools grpcio-tools`

by:
`pip3 install --upgrade wheel setuptools && \
pip3 install --upgrade grpcio-tools`

I guess `pip3 install --upgrade grpcio-tools` needs `setuptools` but `pip3` wasn't "updated yet" after the installation of `setuptools` in the one-line command.

**Comment by nphilou** [comment]
Hey! 

Are you on the `master` branch? I had the same issue (with `setuptools`) and this commit https://github.com/NVIDIA/triton-inference-server/commit/5cb0c4ed3930c5ed37158d4b22a00d35f4797ff1
solved it.

From your logs:
`[...] && pip3 install --upgrade wheel setuptools grpcio-tools`

`pip3 install --upgrade wheel setuptools grpcio-tools` should be replaced by:

```
pip3 install --upgrade wheel setuptools && \
pip3 install --upgrade grpcio-tools
```

Technically, building `grpcio-tools` need setuptools but pip3 was not "updated yet" in the single-line command.

**Comment by vandesa003** [comment]
> Hey!
> 
> Are you on the `master` branch? I had the same issue (with `setuptools`) and this commit [5cb0c4e](https://github.com/NVIDIA/triton-inference-server/commit/5cb0c4ed3930c5ed37158d4b22a00d35f4797ff1)
> solved it.
> 
> From your logs:
> `[...] && pip3 install --upgrade wheel setuptools grpcio-tools`
> 
> `pip3 install --upgrade wheel setuptools grpcio-tools` should be replaced by:
> 
> ```
> pip3 install --upgrade wheel setuptools && \
> pip3 install --upgrade grpcio-tools
> ```
> 
> Technically, building `grpcio-tools` need setuptools but pip3 was not "updated yet" in the single-line command.

Thanks @nphilou ! I was on r20.03 branch. Finally, I fixed the problem by using a pre-built docker image. I will try your proposal afterwards if I need to build from source.
