### ISSUE TITLE
Run on Jetson

### ISSUE THREAD

**Issue by turowicz** [NVIDIA/triton-inference-server#1468]
I have a Jetson Nano that I would like to try Triton out on.

There used to be a script for building on Jetson: https://github.com/NVIDIA/triton-inference-server/pull/1072/files

Is there any way I can access it?

**Comment by turowicz** [comment]
cc @deadeyegoodwin

**Comment by turowicz** [comment]
cc @GuanLuo @CoderHam

**Comment by turowicz** [comment]
Should I just follow this guide?
https://docs.nvidia.com/metropolis/deepstream/dev-guide/index.html

It would be ideal to run this in a docker container though.

**Comment by turowicz** [comment]
Actually the Triton in the DeepStream 5.0 SDK is not the same thing. I'm after the GRPC endpoint that I can host models on.

**Comment by turowicz** [comment]
I've followed the steps in https://github.com/NVIDIA/triton-inference-server/pull/575

Unfortunately I wasn't able to compile libtensorflow_trtis on a Jetson. Any pointers to how to get the TF backend running on Jetson?

**Comment by turowicz** [comment]
I do manage to get trtis up and running, although it says no gpu is found. Is it because of tegra architecture in nano?

**Comment by turowicz** [comment]
@deadeyegoodwin I'm currently struggling with the following error:

```
E0514 17:02:53.999075 2359 model_repository_manager.cc:1519] instance group ssd_mobilenet_v2_coco_0 of model ssd_mobilenet_v2_coco has kind KIND_GPU but no GPUs are available
```

I've optimized the saved_model with TensorRT using the saved_model approach. What am I missing?

**Comment by turowicz** [comment]
After adding min-supported-compute-capability flag now I get:

```
root@ff2cab77bdc6:/opt/tensorrtserver/install/bin# LD_PRELOAD=/usr/local/cuda/lib64/stubs/libnvidia-ml.so LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib ./trtserver --model-repository=/models --strict-model-config=false --min-supported-compute-capability=5.0

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
E0514 17:08:01.063373 2117 metrics.cc:151] failed to initialize NVML: NVML_ERROR 9
I0514 17:08:01.063537 2117 server.cc:120] Initializing Triton Inference Server
W0514 17:08:01.322117 2117 autofill.cc:245] Autofiller failed to retrieve model. Error Details: Internal: unable to autofill for 'ssd_mobilenet_v2_coco', unable to find a compatible plan file.
W0514 17:08:01.322171 2117 autofill.cc:251] Proceeding with simple config for now
I0514 17:08:01.322312 2117 server_status.cc:55] New status tracking for model 'ssd_mobilenet_v2_coco'
I0514 17:08:01.322504 2117 model_repository_manager.cc:680] loading: ssd_mobilenet_v2_coco:1
E0514 17:08:01.322986 2117 model_repository_manager.cc:840] failed to load 'ssd_mobilenet_v2_coco' version 1: Internal: unable to find PLAN model 'model.plan' for ssd_mobilenet_v2_coco
error: creating server: INTERNAL - failed to load all models
```

**Comment by turowicz** [comment]
Status report: I'm going back to using the TensorFlow backend on Jetson.

Pulled the `tensorflow_sources` folder from the official NVIDIA TensorFlow container, because this is the only place you can get libtensorflow_trtis source from.

Now running `./nvbuild.sh --python3.6 --trtis` on the `l4t-base` conainer image on the Jetson itself....

**Comment by deadeyegoodwin** [comment]
We are considering official releases for jetson but don't have a timeline yet. We do have a build of Triton for jetpack 4.4 developer preview (https://developer.nvidia.com/embedded/jetpack) that includes the TensorRT, TensorFlow, ensemble and custom backends. We will work on packaging that as an alpha release and try to make it available sometime next week.

**Comment by turowicz** [comment]
@deadeyegoodwin thanks... I'm already almost done compiling the entire planet from scratch. I will have Triton with Tensoflow backend up and running on Jetson Nano today.

**Comment by turowicz** [comment]
@deadeyegoodwin BTW I am on JP 4.4

**Comment by turowicz** [comment]
Please let me know when any sort of official container image for trtis on l4t is available. Including TF backend.

**Comment by jishminor** [comment]
@turowicz I am attempting the same as you, however my end target is Xavier. Did you compile natively on Nano, or did you cross compile on x86?

**Comment by turowicz** [comment]
@jishminor I'm compiling everything on Nano. It takes ages and the process crashes, but with --noclean flag I'm at 76% of the libtensorflow_trtis build and I'm able to restart and continue.

**Comment by turowicz** [comment]
@jishminor how do you specify the docker container to run using ARM on x86? Is it as simple as enabling the qemu and simply starting with a `l4t` image?

**Comment by turowicz** [comment]
I've just had a build crash at 80% and when I tried to restart it started again from scratch... @jishminor I guess we will have to use the cross build somehow?

**Comment by turowicz** [comment]
cc @deadeyegoodwin

**Comment by jishminor** [comment]
@turowicz For multiarch builds I use buildx. [This](https://mirailabs.io/blog/multiarch-docker-with-buildx/) is a good tutorial to get started. The problem is performance really because you are using user-mode arm64 emulation to "natively" compile arm64, as opposed to truly cross compiling arm64 from an x86 build host.

**Comment by jishminor** [comment]
@turowicz Given that the only way to compile libtensorflow_trtis is via extracting the source from the dockerfile (kind of hacky), I am now just going to wait for the alpha release mentioned above, as it may not be worth the effort at this time.

**Comment by turowicz** [comment]
I've tried the cross compile but I've given up due to too many dependencies of CUDA/RT not being found on x86. Installing ARM dependencies did not help.

I'm still compiling the sources extracted from dockerfile. Yesterday it crashed at 99.9999% as the process ran out of disk space...

**Comment by deadeyegoodwin** [comment]
1.12.0 release updated with experimental Jetson/Jetpack package. https://github.com/NVIDIA/triton-inference-server/releases/tag/v1.12.0

**Comment by deadeyegoodwin** [comment]
Tar file seems to be corrupt.. let me upload it again...

**Comment by deadeyegoodwin** [comment]
Tar file is correct now. Please try and let us know how it goes.

**Comment by jishminor** [comment]
@deadeyegoodwin Any timeline for when the nvidia container registry may have a docker image ready?

**Comment by deadeyegoodwin** [comment]
We are not releasing as a container at this time but are considering it for the future. You'll have to wrap the tar file in a container yourself for now.

**Comment by turowicz** [comment]
Thank god, otherwise my compilation efforts would be pointless ;)

**Comment by jishminor** [comment]
Are there plans to release the build instructions for jetson, rather than just releasing the compiled binaries in the near future. As @turowicz pointed out earlier, there once existed a bash script showing how to build for jetson, however it seems it was moved to your private gitlab repos.

I would like to build a generic release of triton for arm64 platforms (rpi4), and the current jetson release is linked against jetson specific libraries.

**Comment by turowicz** [comment]
@jishminor what kind of performance do you expect from rpi?

**Comment by jishminor** [comment]
@turowicz My intention is to add [ArmNN](https://github.com/ARM-software/armnn) as a supported backend for triton, such that triton can be used to also inference with faster arm neon and arm mali gpu backends. In general I don't expect the raspberry pi to be able to do much with the default tensorflow cpu runtime, however ArmNN should greatly improve perf for pure cpu.

**Comment by turowicz** [comment]
:+1: for that @jishminor. That said, it's going to be a hell of a ride for you implementing this.

**Comment by jishminor** [comment]
@deadeyegoodwin Does your team plan on releasing the v2 python client libraries for Jetson anytime soon?

**Comment by CoderHam** [comment]
@jishminor we are in the process of finalizing the the V2 python libraries. Just like the last release it will be available in the form of a tar file that will contain both the client libraries and well as the server build.

**Comment by jishminor** [comment]
> Are there plans to release the build instructions for jetson, rather than just releasing the compiled binaries in the near future? As @turowicz pointed out earlier, there once existed a bash script showing how to build for jetson, however it seems it was moved to your private gitlab repos.
> 
> I would like to build a generic release of triton for arm64 platforms (rpi4), and the current jetson release is linked against jetson specific libraries, meaning it won't run on rpi4s.

@deadeyegoodwin

**Comment by deadeyegoodwin** [comment]
We can share the cmake command we use to build... but the primary effort in building is making sure the backends you want are built and available in the way that Triton requires. As describe in the docs for x86 build this is not a trivial task and it is even more difficult on ARM since some/many of the backends don't have arm build instructions. But if you just want to build a Triton on arm that only has custom backend (for example, because that is entirely in Triton and doesn't require another framework), you should be able to use a cmake like the following:

            cmake -DCMAKE_BUILD_TYPE=Release \
                  -DTRITON_ENABLE_STATS=ON \
                  -DTRITON_ENABLE_METRICS=ON \
                  -DTRITON_ENABLE_METRICS_GPU=OFF \
                  -DTRITON_ENABLE_TRACING=ON \
                  -DTRITON_ENABLE_GCS=OFF \
                  -DTRITON_ENABLE_S3=OFF \
                  -DTRITON_ENABLE_CUSTOM=ON \
                  -DTRITON_ENABLE_ENSEMBLE=ON \
                  -DTRITON_ENABLE_TENSORFLOW=OFF \
                  -DTRITON_ENABLE_TENSORRT=OFF \
                  -DTRITON_ENABLE_CAFFE2=OFF \
                  -DTRITON_ENABLE_ONNXRUNTIME=OFF \
                  -DTRITON_ENABLE_ONNXRUNTIME_TENSORRT=OFF \
                  -DTRITON_ENABLE_ONNXRUNTIME_OPENVINO=OFF \
                  -DTRITON_ENABLE_PYTORCH=OFF

TensorRT is available for ARM so if you install that first you should be able to enable TensorRT support in the build.

**Comment by jishminor** [comment]
@deadeyegoodwin Looking at the dockerfile for the x86 build, it seems that for tensorflow you take the the library `/usr/local/lib/tensorflow/libtensorflow_trtis.so.1` from the nvidia tensorflow image for x86 and use it in the final build stage. Is there an equivalent for jetpack? Looking at the files in `nvcr.io/nvidia/l4t-tensorflow:r32.4.3-tf1.15-py3` it seems that the equivalent arm64 library doesn't exist.

**Comment by deadeyegoodwin** [comment]
Right, because the TF C API is insufficient for Triton so we have to patch TF and build it ourselves. The NVIDIA TF build/container includes these patches and that is what we use. This is explained in build documentation that if you want to build your own TF you need to start with the NVIDIA TF container and build from there to get that Triton-specific library. For ARM I think it is further complicated by TF not being easy to build on ARM... but I'm not sure about that.

**Comment by jishminor** [comment]
Ah that sounds like a pain. Is the build recipe for nvidia's custom tensorflow available anywhere for x86 or jetpack?

**Comment by deadeyegoodwin** [comment]
Yes. https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/build.html#tensorflow

**Comment by thebruce87m** [comment]
I too am after a jetson based Triton server.

Actually, to take a step back, my problems are:
- Models take a long time to load
- If my app loads the model, it takes a long time to debug the app

I think my solution to this is to use the triton server, since this loads the model once then stays "up" while my app is just a client and can be closed/opened/debugged easily.

Is there any progress on having a Jetson based Docker image with the Triton server?

**Comment by deadeyegoodwin** [comment]
Docker image for jetson is still on our roadmap but not yet available. In the meantime you can  make your own docker image from the tarball release.

**Comment by turowicz** [comment]
> Docker image for jetson is still on our roadmap but not yet available. In the meantime you can make your own docker image from the tarball release.

It does work

**Comment by jishminor** [comment]
@thebruce87m I would just create a Dockerfile which wget's the jetpack triton from the releases here, unpacks it, and installs the necessary package dependencies as specified on the releases page for triton.

**Comment by egendron93** [comment]
Here is a Dockerfile that I made a few versions ago.

``` 
FROM nvcr.io/nvidia/l4t-ml:r32.4.4-py3

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        autoconf \
        automake \
        build-essential \
        cmake \
        git \
        libb64-dev \
        libre2-dev \
        libssl-dev \
        libtool \
        libboost-dev \
        libcurl4-openssl-dev \
        rapidjson-dev \
        patchelf \
        zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tritonserver

RUN wget https://github.com/triton-inference-server/server/releases/download/v2.6.0/tritonserver2.6.0-jetpack4.4.tgz && \
    tar -xzf tritonserver2.6.0-jetpack4.4.tgz && \
    rm tritonserver2.6.0-jetpack4.4.tgz

ENV LD_LIBRARY_PATH=/tritonserver/backends/tensorflow1:$LD_LIBRARY_PATH

ENTRYPOINT ["/tritonserver/bin/tritonserver"]
CMD ["--help"]

```

just for reference. let me know if it helps.

**Comment by turowicz** [comment]
> Hi ! Is there any progress on having a Jetson based Docker image with the Triton server?

Im also waiting for it.

**Comment by koenvandesande** [comment]
It is not that hard to build a Docker container with the released tarball. E.g.:
```
FROM nvcr.io/nvidia/l4t-tensorrt:r8.4.1-runtime

RUN apt-get update -y && \
    apt-get install -y curl libre2-dev libb64-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/tritonserver

RUN \
    curl -L https://github.com/triton-inference-server/server/releases/download/v2.24.0/tritonserver2.24.0-jetpack5.0.2.tgz | tar -xzf - && \
    rm -rf backends/tensorflow1 backends/tensorflow2 backends/onnxruntime backends/pytorch clients include qa test-util && \
    echo Done

ENV PATH="/opt/tritonserver/bin:${PATH}"
```

This will clean up most of the backends, and leave only the TensorRT/Python ones. Modify to your need.

**Comment by julienripoche** [comment]
I'm already using a Dockerfile similar to the one of @egendron93 and I was of course refering to an official ARM/Jetson Docker image.
