### ISSUE TITLE
Question: TRTIS Caffe2 does not support models with both CPU and GPU ops?

### ISSUE THREAD

**Issue by erickim555** [NVIDIA/triton-inference-server#147]
https://github.com/NVIDIA/tensorrt-inference-server/blob/0a73c5ce0d4c53ff55c23f05171b2c02d2c60c1d/src/servables/caffe2/netdef_bundle_c2.cc#L273-L290

Hello, I'm looking forward to using TRTIS to serve Caffe2 object detection models, specifically FRCNN-like models from Detectron: https://github.com/facebookresearch/Detectron

However, in the above lines of the TRTIS source code, it looks like TRTIS is explicitly overwriting the `device_option` field of all ops to either GPU or CPU (depending on `gpu_device` input parameter). Thus, it disallows mixing CPU and GPU ops. This is problematic, as the Detectron FRCNN models contain custom C++ CPU ops, such as the CollectAndDistributeFpnRpnProposals op: [link](https://caffe2.ai/docs/operators-catalogue.html#collectanddistributefpnrpnproposals)

Is it a fundamental TRTIS restriction that a Caffe2 model must either run purely on the GPU, or purely on the CPU? If not, then for our usecase I'll just comment out this block and build+deploy a custom TRTIS binary.

**Comment by deadeyegoodwin** [comment]
Your observation is correct. The current code is to support multi-GPU, where it is necessary to override the GPU device setting for a network to assign it to a different GPU. But as you note this can cause issues when you actually want the model to be served exactly as it is. Another use case is where you have a model that has been manually configured to use multiple GPUs. 

As a WAR you should be able to just comment out that code. TRTIS does not rely on overriding the device setting.

A proper fix is for the instance_group configuration for a model to have an option that allows you to specify that you want to model to run on the devices exactly as it is specified. I'll mark this a both a bug and an enhancement.

**Comment by erickim555** [comment]
Great, thank you for the detailed and quick answer! I'll comment out the block to unblock myself, but looking forward to a more longterm solution.

**Comment by erickim555** [comment]
(actually I don't know if leaving this closed or open is appropriate. Feel free to close this if that's proper protocol. thanks!)

**Comment by deadeyegoodwin** [comment]
@erickim555 We'll leave this open to track the issue until the long-term fix is completed.

**Comment by deadeyegoodwin** [comment]
Caffe2 is deprecated and will be removed soon. No additional enhancements are planned.
