### ISSUE TITLE
predict failed with  tensorrtserver-1.12.0

### ISSUE THREAD

**Issue by helloninglei** [NVIDIA/triton-inference-server#1471]
**Description**
my model works well with tensorrtserver 1.7.0 but failed with tensorrtserver-1.12.0 client

**Triton Information**
client:  tensorrtserver-1.12.0 
server: nvcr.io/nvidia/tritonserver:20.03-py3

Are you using the Triton container or did you build it yourself?
just use Triton container

**To Reproduce**
1. install tensorrtserver 1.7.0 predict , everything is ok
2. uninstall tensorrtserver 1.7.0 and install tensorrtserver-1.12.0 , predict failed

when run predict, will throw this error:

[ 0] input 'class/class_result' values must be specified as a list of numpy arrays or as a single 
c_void_p (representing the shared memory handle) or as a tuple of c_void_p (representing the 
shared memory handle) and list (representing the shape of the input tensor) - remaking context

**Comment by deadeyegoodwin** [comment]
We added some stricter checking to make sure the python APIs are being used correctly. It looks like your are not passing input tensor data as a list of numpy arrays. Can you share how you are invoking the inference run API in your code.

**Comment by helloninglei** [comment]
> We added some stricter checking to make sure the python APIs are being used correctly. It looks like your are not passing input tensor data as a list of numpy arrays. Can you share how you are invoking the inference run API in your code.

yes, it's working now, thanks.

![image](https://user-images.githubusercontent.com/22606004/81883119-026dc400-95c7-11ea-931d-2f8c94eaad31.png)
