### ISSUE TITLE
Enable  AMP without any  TensorRT optimization for Tensorflow  in the inference server.

### ISSUE THREAD

**Issue by whatdhack** [NVIDIA/triton-inference-server#1472]
**Is your feature request related to a problem? Please describe.**
Would be nice to be able to just enable FP16  (e.g. TF_ENABLE_AUTO_MIXED_PRECISION ) without any TensorRT optimization in the inference server. 

**Describe the solution you'd like**
Just FP16 , no other optimization

**Describe alternatives you've considered**
Running Tensorflow directly 

**Additional context**
Using TensorRT optmization appears to cause adverse issues, such as OOM,  in large networks such as MaskRCNN.  However Tensorflow with just FP16 does not have this issue.

**Comment by deadeyegoodwin** [comment]
TF_ENABLE_AUTO_MIXED_PRECISION refers to AMP which is targeted at training, not inference. Not sure if/how it would work with inference. Being an environment variable doesn't really work for a multi-model server like Triton. It would be great if TF introduced a session configuration option to select mixed precision for a model. They are working on new runtime optimizations so perhaps that is something they will add and then Triton could adopt it and expose it via the existing optimization settings in the model configuration.

**Comment by whatdhack** [comment]
I just ran some tests on a MaskRCNN Saved Model  in nvcr.io/nvidia/tensorflow:20.03-tf1-py3.  Seems to work very well for inference - requires less memory and speeds up significantly.  The following are the numbers. 

**TF_ENABLE_AUTO_MIXED_PRECISION =1, memory = 4.2GB , inference speed  0.25 sec .**
vs53 
**memory = 7.1 GB , inference speed  0.53 sec .**

**Comment by whatdhack** [comment]
@deadeyegoodwin , I took a quick look at https://github.com/NVIDIA/triton-inference-server/blob/master/src/backends/tensorflow/tensorflow_backend_tf.cc , if there is place where I can add something similar to TF_ENABLE_AUTO_MIXED_PRECISION.  What TF_ENABLE_AUTO_MIXED_PRECISION  would be equivalent to inside the tensorflow_backend code ?

**Comment by deadeyegoodwin** [comment]
I don't know of a TF configuration setting that you could use... you can look though the config protobuf to see if there is something.

**Comment by whatdhack** [comment]
@deadeyegoodwin ,  The following option is available in plain TF , works in 1.15.2 .  Is there a way to set this option in the TF library used by Triton  ?

config.graph_options.rewrite_options.auto_mixed_precision = 1

The above appears to be present in some form  in the tensorflow library linked to trtserver.  

/opt/tensorrtserver# nm /opt/tensorrtserver/bin/../lib/tensorflow/libtensorflow_trtis.so.1 | grep auto_mixed_precision
00000000024b99f0 t _GLOBAL__sub_I_auto_mixed_precision.cc

**Comment by deadeyegoodwin** [comment]
Thanks, we'll look into it.

**Comment by deadeyegoodwin** [comment]
Fixed by https://github.com/NVIDIA/triton-inference-server/pull/1680.
