### ISSUE TITLE
Onnx GPU inference on GKE not possible

### ISSUE THREAD

**Issue by pasikon** [NVIDIA/triton-inference-server#1477]
**Description**
Inference of onnx model runs on CPU on GKE because of CUDA error on Tesla T4. VM has Nvidia device driver version 418 installed which is supported according to Triton 20.02 release notes.

During the startup the output is:

```
2020-05-13 13:26:15.839881: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
I0513 13:26:15.884910 1 metrics.cc:164] found 1 GPUs supporting NVML metrics
I0513 13:26:15.890620 1 metrics.cc:173]   GPU 0: Tesla T4
I0513 13:26:15.890894 1 server.cc:112] Initializing TensorRT Inference Server
E0513 13:26:15.892677 1 pinned_memory_manager.cc:194] failed to allocate pinned system memory: CUDA driver version is insufficient for CUDA runtime version
I0513 13:26:31.772884 1 server_status.cc:55] New status tracking for model 'bert_rfe_only_onnx'
I0513 13:26:31.937199 1 model_repository_manager.cc:675] loading: bert_rfe_only_onnx:1
I0513 13:26:43.866809 1 onnx_backend.cc:189] Creating instance bert_rfe_only_onnx_0_cpu on CPU using rfe_only_model_prototype.onnx
I0513 13:26:45.587897 1 model_repository_manager.cc:829] successfully loaded 'bert_rfe_only_onnx' version 1
Starting endpoints, 'inference:0' listening on
I0513 13:26:45.594604 1 grpc_server.cc:1973] Started GRPCService at 0.0.0.0:8001
I0513 13:26:45.594708 1 http_server.cc:1443] Starting HTTPService at 0.0.0.0:8000
I0513 13:26:45.637327 1 http_server.cc:1458] Starting Metrics Service at 0.0.0.0:8002
```

**Triton Information**
20.02

Are you using the Triton container or did you build it yourself?

Triton container

**To Reproduce**
The model is Keras (Transformers) BERT-base converted to Onnx by keras-onnx, the configuration is default, do the reproduction would be to try to run it with v 418 Nvidia drivers I guess

**Expected behavior**
The inference should work on GPU

**Comment by GuanLuo** [comment]
Release 20.02 is based on CUDA 10.2.89, which requires NVIDIA driver release 440.33.01. I think you will need to upgrade the driver version you used.

Also, can you point out the place where it mentions driver version 418 is supported? It's likely a mistake on release note and we should have fixed that.

**Comment by pasikon** [comment]
https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html 

  | Release 20.03 is based on CUDA 10.2.89, which requires NVIDIA                                           driver release 440.33.01.                                                                                 However, if you are running on Tesla (for example, T4 or any                                           other Tesla board), you may use NVIDIA driver release 396,                                           384.111+, 410, 418.xx or 440.30.
-- | --

As you can see in the log I'm using the Tesla T4.

Side question: is it possible to install v 440 on GKE? I don't think so but maybe I'm missing something.

**Comment by GuanLuo** [comment]
I see, in the same line, it mentions [CUDA compatibility package](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#cuda-application-compatibility), is that installed on your system?

**Comment by pasikon** [comment]
At first I haven't had that installed, but after I did

```
RUN apt-get install cuda-compat-10.1
RUN apt-get install cuda-compat-10.0
RUN echo /usr/local/cuda-10.1/compat > /etc/ld.so.conf.d/cuda_compat-101.conf
RUN echo /usr/local/cuda-10.0/compat > /etc/ld.so.conf.d/cuda_compat-100.conf
RUN ldconfig
```

Its still not working. Maybe I install it wrong way?

**Comment by jakepoz** [comment]
I would recommend to try the following, slightly older image which should match the driver release that's on GKE: nvcr.io/nvidia/tensorrtserver:19.10-py3

**Comment by deadeyegoodwin** [comment]
Were you able to get this working? Closing, but reopen if you are still having an issue.
