### ISSUE TITLE
Allow Triton to report all health metrics at startup

### ISSUE THREAD

**Issue by JulianOrteil** [NVIDIA/triton-inference-server#1485]
**Is your feature request related to a problem? Please describe.**
It would be beneficial if Trtion would report all health metrics at bootup. Currently:

nv_inference_request_success
nv_inference_request_failure
nv_inference_count
nv_inference_exec_count
nv_inference_request_duration_us
 nv_inference_compute_duration_us
nv_inference_queue_duration_us
nv_inference_load_ratio

do not report until after the first inference request is received by the server. This causes confusion in display services like Grafana as no data is being reported.

**Describe the solution you'd like**
Could the above values report 0 when the server is started?

**Describe alternatives you've considered**
Really no alternatives to my request at this point that I've been able to think of.

**Additional context**
N/A

**Comment by deadeyegoodwin** [comment]
After starting the server what does "curl localhost:8002/metrics" show?

**Comment by JulianOrteil** [comment]
Nevermind. I think Prometheus was having a moment. Restarted the machine and they're there now.

I've seen other services do what I described above, my apologies for assuming wrong and this false report.
