### ISSUE TITLE
Running inference with Trits is much slower than running model Pytorch directly

### ISSUE THREAD

**Issue by ndhung** [NVIDIA/triton-inference-server#1500]
**Description**
Running inference with Trits is much slower than running model directly

**Triton Information**
What version of Triton are you using?
Triton 20.03 Pull from nvcr 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Python 3.6
GPU: 1660Ti

**Expected behavior**
When I run pytorch model directly, performance is about 25fps, but when running on Trion, performance is only ~9fps

**Comment by GuanLuo** [comment]
The communication between Triton and its client goes through network, so the network overhead will have impact on the inference latency. It will be more helpful to compare the results without those overhead. If you are using perf_client for profiling Triton performance, you can take a look at the request latency reported by the server, that is more meaningful when comparing with native performance.

**Comment by deadeyegoodwin** [comment]
Closing. Please provide perf_client output if you have followup questions.
