### ISSUE TITLE
How to use label_filename

### ISSUE THREAD

**Issue by turowicz** [NVIDIA/triton-inference-server#1501]
I'm trying to start using `label_filename` so I don't have to lookup class names on the client.

I've got the model loading correctly in TRTIS and it picks up the text file with class names.

How do I parse the labels from the response? I'm using TF object detection models.

cc @deadeyegoodwin @GuanLuo

**Comment by GuanLuo** [comment]
When you send your request, you can specify to return classification results, in that case, the label name will be part of the result if present.

[Here](https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/http_grpc_api.html#inference) is the request header that requests classification output if you want to construct the request by yourself. Or you can take a look at the [C++](https://github.com/NVIDIA/triton-inference-server/blob/r20.05/src/clients/c%2B%2B/api_v1/examples/image_client.cc) / [Python](https://github.com/NVIDIA/triton-inference-server/blob/r20.05/src/clients/python/api_v1/examples/image_client.py) clients that do the same using our client library.

**Comment by deadeyegoodwin** [comment]
Also be aware that Triton V2 is available starting in 20.05 release (coming soon) and in addition to classification support in the V2 client libraries there is much easier to use HTTP/REST protocol that includes support for classification: https://github.com/NVIDIA/triton-inference-server/tree/master/docs/protocol

**Comment by turowicz** [comment]
@deadeyegoodwin seems I've been expecting the wrong thing. I'm doing object detection and I thought it would return labels for each detection. What I understand now, the automatic labelling is only meant for image classification. Do you know if V2 adds support for Object Detection?

**Comment by deadeyegoodwin** [comment]
The automatic labeling is mean for output tensors where each "index" in the tensor indicates a probability and a label is attached to each index. It is not specific to image classification but your tensor must have those properties.

**Comment by kivancyuksel** [comment]
I also have this problem, the response doesn't return labels specified in `labels.txt`. I am sorry to ask this again, but I couldn't understand from the conversation (and from the given links) what I should do exactly to get these labels. `image_client.py` example seems like it doesn't do anything different than what I do, but still, I don't have labels attached to the response.
