### ISSUE TITLE
Multiple Inputs Model Failing: Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.

### ISSUE THREAD

**Issue by benjaminhon** [NVIDIA/triton-inference-server#1502]
**Description**

I get the following error when predicting a certain model using the tensorrtclient

```
# tensorrtclient logs
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
```

```
# tensorrtserver logs
http_server.cc:1214] Infer failed: unexpected size for input 'data/ph_tc', expecting 786432 bytes for model 'mribraintumor_ZL_T2Tc_deform'
```

all my models with single input works, only those with multiple inputs have this error after upgrading to 1.12

**Triton Information**
tritonserver: nvcr.io/nvidia/tritonserver:20.03-py3
tensorrtclient: v1.12.0_ubuntu1804.clients.tar.gz

**Gpu**
1080ti

**Environment**
docker-compose using runtime=nvidia
cuda 10.2

**Model config**

```
name: "mribraintumor_ZL_Tc_deform"
platform: "tensorflow_graphdef"
max_batch_size: 1
input [
   {
      name: "data/ph_t2"
      data_type: TYPE_FP32
      dims: [ 12,128,128 ] 
   },
   {
      name: "data/ph_tc"
      data_type: TYPE_FP32
      dims: [ 12,128,128 ] 
   },
   {
      name: "data/ph_mask"
      data_type: TYPE_FP32
      dims: [ 12,128,128 ] 
   }
]
output [
   {
      name: "pred_cls"
      data_type: TYPE_FP32
      dims: [ 24 ]
   }
]
```

**Comment by benjaminhon** [comment]
after enabling --log-verbose=2 i notice i got this error

```
http_server.cc:1214] Infer failed: unexpected size for input 'data/ph_tc', expecting 786432 bytes for model 'mribraintumor_ZL_T2Tc_deform'
```

its probably my side, closing

**Comment by benjaminhon** [comment]
I just realised that all my models with multiple inputs are showing this error after upgrading to 1.12.0, has there been a change in the way the models are called through the python http api?

**Comment by benjaminhon** [comment]
when i turn on verbose i get the following

```
NV-InferRequest:batch_size: 1 
input { name: "data/ph_t2" dims: 12 dims: 128 dims: 128 }
input { name: "data/ph_tc" } 
input { name: "data/ph_mask" } 
output { name: "pred_cls" }
```

why are the dims missing for the other 2 inputs? namely data/ph_tc data/ph_mask

**Comment by GuanLuo** [comment]
Can you provide the model and steps to reproduce the issue? And one thing I noticed is the input names you  sent is "in1" ... instead of "data/XXX"

**Comment by benjaminhon** [comment]
@GuanLuo yea thats was just as an example, the actual is data/ph..

**Comment by helloninglei** [comment]
@GuanLuo  we test all models , all the multiply input failed

![image](https://user-images.githubusercontent.com/22606004/82514544-9d771880-9b48-11ea-8d11-5e38737d58f8.png)

**Comment by GuanLuo** [comment]
@benjaminhon Can you send the request with verbose logging (option on creating the client context) and check if the HTTP request sent is correct? By the way, the model config specify the max_batch_size is 1, and your client code snippet are trying to send a batch of size 2, is that also a typo?

**Comment by GuanLuo** [comment]
@helloninglei The error message in your screenshot points to another issue: the server fail to send back the (failure) response, did the server segfault?

**Comment by benjaminhon** [comment]
> @benjaminhon Can you send the request with verbose logging (option on creating the client context) and check if the HTTP request sent is correct? By the way, the model config specify the max_batch_size is 1, and your client code snippet are trying to send a batch of size 2, is that also a typo?

o yes sry thats a typo, its only 1 array

**Comment by benjaminhon** [comment]
i think this there was a problem with the data partitioning, however i notice that there are some difference in the prediction results from 1.7 and 1.12, but its unrelated to this closing this issue, thanks!
