### ISSUE TITLE
Docker Error for nvcr.io/nvidia/deepstream:5.0-dp-20.04-triton

### ISSUE THREAD

**Issue by cbasavaraj** [NVIDIA/triton-inference-server#1510]
```
docker run --gpus all -it -v ~/daisyfive:/opt/nvidia/deepstream/deepstream-5.0 nvcr.io/nvidia/deepstream:5.0-dp-20.04-triton
```
produces the error
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/opt/nvidia/deepstream/deepstream-5.0/entrypoint.sh\": stat /opt/nvidia/deepstream/deepstream-5.0/entrypoint.sh: no such file or directory": unknown.
ERRO[0000] error waiting for container: context canceled 
```
The same command without the mount part works fine:
```
docker run --gpus all -it nvcr.io/nvidia/deepstream:5.0-dp-20.04-triton
```
The container is from https://ngc.nvidia.com/catalog/containers/nvidia:deepstream. I also followed the instructions from https://docs.nvidia.com/metropolis/deepstream/dev-guide/index.html successfully and ran many of the non Triton deepstream sample apps.

I am on Ubuntu 18.04 on a Google Compute Engine instance, with Tesla T4 GPU and CUDA 10.2:
`NVIDIA-SMI 440.64.00 Driver Version: 440.64.00 CUDA Version: 10.2` and `Docker version 19.03.8, build afacb8b7f0`

Appreciate any help, thanks!

**Comment by deadeyegoodwin** [comment]
This seems like a deepstream issue... but from the error message it seems like the container needs access to /opt/nvidia/deepstream/deepstream-5.0 to find its entrypoint code and start correctly, but you've mapped your own directory into that exact location... map your directory somewhere else, like "-v ~/daisyfive:/tmp/daisyfive" and you should not see the problem.

**Comment by cbasavaraj** [comment]
Thanks, you are right. T'was a stupid n00b error on my part!
