### ISSUE TITLE
Document steps for how to compile Pytorch custom-ops library for running with Triton

### ISSUE THREAD

**Issue by chauhang** [NVIDIA/triton-inference-server#1514]
**Description**
In order to a custom-ops library for a PyTorch model that can run on Trion, one needs to compile the custom-ops library with Nvidia optimized libtorch. There are no build steps described for this.

**Triton Information**
What version of Triton are you using? 
The latest Triton NGC 20.03-py3

Are you using the Triton container or did you build it yourself? 
Using the NGC container

**To Reproduce**
Steps to reproduce the behavior.

1. Compile a custom-ops library like [pytorch_scatter ](https://github.com/rusty1s/pytorch_scatter#c-api) using PyTorch official libtorch for ver 1.5
2. Create a torchscripted model that uses the custom-ops library
3. Try to start Triton with the custom ops library gives an error
```
LD_PRELOAD=libtorchscatter.so trtserver --model-store=/models --log-verbose=1
ERROR: ld.so: object 'libtorchscatter.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
4. Next I tried installing cname inside the Triton NGC by starting it on Docker CLI and compile the pytorch_scatter custom-ops using the Triton bundled libtorch. However that also did not work, same error for `missing TorchConfig.cmake file`. 

5. Next I tried to compile it using the NGC 20.03 PyTorch container and got the file compiled. 
6. With the compile file above tried to run inside Triton docker container and still got errors
```
root@325a83f7c2ec:/opt/tensorrtserver# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/tensorrtserver/lib/pytorch/libtorchscatter.so
root@325a83f7c2ec:/opt/tensorrtserver# LD_PRELOAD=libtorchscatter.so trtserver --model-store=/models --log-verbose=1

trtserver: error while loading shared libraries: libc10.so: cannot open shared object file: No such file or directory
```
7. Finally got things to work using workround steps from Triton team to use strict-model-config=false
```
root@325a83f7c2ec:/opt/tensorrtserver# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/tensorrtserver/lib/pytorch/libtorchscatter.so
LD_PRELOAD=lib/pytorch/libtorchscatter.so trtserver --model-store=/scripts/triton/pytorch/ --log-verbose=1 --strict-model-config=false
```

Note that the LD_LIBRARY_PATH needs to be set with the custom-op file in the path for things to work. 

**Expected behavior**
1. Proper build steps for compiling PyTorch custom-ops library that can work on Triton should be documented.
2. Should be able to run TorchScripted models using compiled custom-ops library on Triton without requiring Docker CLI interactive steps. This is needed for models to be able to run in production mode.

**Comment by deadeyegoodwin** [comment]
Your steps 6 and 7 seem to be confusing how to use LD_PRELOAD and LD_LIBRARY_PATH. Try:

1. Compile custom op library using the NGC 20.03 PyTorch container.
2. Use LD_PRELOAD and LD_LIBRARY_PATH to load the library into triton on startup.

```
# export LD_LIBRARY_PATH=/opt/tritonserver/lib/pytorch:$LD_LIBRARY_PATH
# LD_PRELOAD=path/to/libtorchscatter.so trtserver --model-store=/models
```

Step 2 is in the (recently  updated) documentation: https://github.com/NVIDIA/triton-inference-server/blob/master/docs/custom_operation.rst#pytorch

For step 1 it is not strictly necessary to use the NGC version of pytorch but you must make sure that you use the exact version of pytorch that matches what is in the triton container (see release notes). We can update the documentation with this information as well.
