### ISSUE TITLE
Provide steps for compiling PyTorch custom-ops library against the nightlies

### ISSUE THREAD

**Issue by chauhang** [NVIDIA/triton-inference-server#1515]
**Is your feature request related to a problem? Please describe.**
For new features that are getting added to PyTorch nightlies in the master branch, what is the mechanism to get corresponding nightlies for Nvidia optimized PyTorch so that one can compile the custom-ops library and run with Triton. At present unable to test https://github.com/lgray/pytorch_geometric/blob/jittable_geometric/examples/mnist_nn_conv_jit.py which requires the latest nightlies version of PyTorch with fix for torch.unique support (https://github.com/pytorch/pytorch/issues/37986)

**Describe the solution you'd like**
Please provide steps for how to do above

**Describe alternatives you've considered**
Could not find any other alternative

**Additional context**
Model above uses the [pytorch_geometric](https://github.com/rusty1s/pytorch_geometric) abd related libraries from [rusty1s](https://github.com/rusty1s). For your model to work in Python mode, please install latest Pytorch from the nightlies, and compile all the pytorch_geomtric libraries from source and then run the model on local first. Then try to get it to run on Triton

**Comment by deadeyegoodwin** [comment]
Triton releases monthly and uses the NGC version of pytorch that also releases monthly. Therefore Triton picks up new PyTorch changes when they make it into the NGC version of pytorch. These monthly releases are tested for stability and compatibility with the underlying CUDA, cudnn, cublas, etc. libraries.

The steps to build Triton are documented here: https://github.com/NVIDIA/triton-inference-server/blob/master/docs/build.rst. You can attempt to build triton using the master branch of pytorch and if it is successful you should be able to run your model.

**Comment by deadeyegoodwin** [comment]
Closing. Let us know if you have trouble following the build documentation.
