### ISSUE TITLE
Run on Jetson - continuation

### ISSUE THREAD

**Issue by turowicz** [NVIDIA/triton-inference-server#1517]
This topic is a continuation of #1468 with a different context.

I am trying to compile the supplied sources on Jetson Nano, but at different random stages of the build I get the error listed below. I've limited the hardware resources to `--local_resources 1024,1.0,0.95` which allowed in fact to get the build quite far (20k targets out of 28k targets). Can I get any sort of support on getting that build to succeed? It is critical for my startup's business (www.surveily.com) to have a Jetson Nano based product.

```
ERROR: /workspace/tensorflow/tensorflow-source/tensorflow/core/kernels/BUILD:3495:1: C++ compilation of rule '//tensorflow/core/kernels:matrix_square_root_op' failed (Exit 4)
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
INFO: Elapsed time: 94484.876s, Critical Path: 5745.25s
INFO: 9769 processes: 9769 local.
FAILED: Build did NOT complete successfully
cp: cannot stat 'bazel-bin/tensorflow/libtensorflow_cc.so.?': No such file or directory
cp: cannot stat 'bazel-bin/tensorflow/libtensorflow_trtis.so.?': No such file or directory
```

cc @deadeyegoodwin @jishminor @GuanLuo

**Comment by turowicz** [comment]
I trigger the build on nano in a docker container with:

```
./nvbuild.sh --python3.6 --trtis --noclean
```

**Comment by turowicz** [comment]
What combination of Bazel and GCC versions should I have? The sources indicate that the TF supplied by NVIDIA is of version 1.15.2, but the official TF docs don't mention what tools to build that version with.

**Comment by turowicz** [comment]
I am now trying to run the .tgz Jetpack package from:

https://github.com/NVIDIA/triton-inference-server/releases/tag/v1.12.0

**Comment by turowicz** [comment]
After putting it on a container with the required apt-get Trtis is up and running. Now I'm fighting to load any TF model to get it working.

**Comment by turowicz** [comment]
I have managed to load a sample object detection model from TF zoo and it does indeed work. I needed to uninstall the system GUI though.

**Comment by deadeyegoodwin** [comment]
So it seems like the experimental jetson package is working for you. Closing, reopen if you have an issue.

**Comment by turowicz** [comment]
Yes it seems to be all right. Thank you for posting the package @deadeyegoodwin !
