### ISSUE TITLE
TritonRT server on EKS not being able to read from AWS S3

### ISSUE THREAD

**Issue by mapsacosta** [NVIDIA/triton-inference-server#1529]
**Description**
No documentation on how to configure AWS S3 credentials.. metadata error when deploying TRT server on EKS:
`tensorrt-server@tensorrt-inference-server-aws-test-5b9fcf5c5b-kdp7n:/opt/tensorrtserver$ trtserver --model-store=s3://XYZ/model_repository --log-verbose=5
2020-05-21 17:14:36.366664: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
I0521 17:14:36.412387 101 metrics.cc:162] found 1 GPUs supporting NVML metrics
I0521 17:14:36.417883 101 metrics.cc:171]   GPU 0: Tesla V100-SXM2-16GB
I0521 17:14:36.418121 101 server.cc:112] Initializing TensorRT Inference Server
I0521 17:14:36.647486 101 pinned_memory_manager.cc:194] Pinned memory pool is created at '0x7fb794000000' with size 268435456
error: creating server: INTERNAL - Could not get MetaData for bucket with name XYZ`

**Triton Information**

Are you using the Triton container or did you build it yourself?
Pulling container from nvcr.io/nvidia/tensorrtserver:20.01-py3

**To Reproduce**
Create s3 bucket in AWS
Provision a Kubernetes service account with AmazonS3FullAccess 
Deploy pod with model repository pointing to that S3 bucket and Credentials/Configs mounted

`volumeMounts:
          - name: creds-volume
            mountPath: /root/.aws/credentials
            subPath: credentials
          - name: conf-volume
            mountPath: /root/.aws/config
            subPath: config`

`      volumes:
        - name: creds-volume
          secret:
            secretName: aws-credentials
        - name: conf-volume
          secret:
            secretName: aws-config`

**Expected behavior**
Server should connect and read from the S3 bucket and start up without issues

**Comment by CoderHam** [comment]
We fixed S3 support in 20.03. I would recommend using the 20.03 release. We now support passing credentials via env vars.
The earlier way we performed the check required `aws configure` to be run prior to starting the server. It is possible that it is not enough to mount the S3 credentials on the correct paths. Can you verify that you are able to access the S3 bucket from inside your container that mounts the creds/config file?

**Comment by mapsacosta** [comment]
Ah, thanks @CoderHam this explains why I struggled authenticating through environment variables (my bad) I deployed 20.05 and I no longer need to mount credential files. Closing this as solved!
