### ISSUE TITLE
regex incorrect defined for s3 path.

### ISSUE THREAD

**Issue by 24hours** [NVIDIA/triton-inference-server#1534]
**Description**
If s3 path model contain `-` then triton will report fail to obtain metadata information. 

**Triton Information**
20.05

Are you using the Triton container or did you build it yourself?
build myself

**To Reproduce**
`trtserver --model-repository=s3://minio:9000/bucket_name/model-repo`
this path will fail 

`trtserver --model-repository=s3://minio:9000/bucket_name/model_repo`
this path will work fine

the following line is the culprit 
https://github.com/NVIDIA/triton-inference-server/blob/master/src/core/filesystem.cc#L638

should be defined as `s3://([0-9a-zA-Z-.]+):([0-9]+)/([0-9a-z.-]+)(((/[0-9a-zA-Z._-]+)*)?)` instead of `s3://([0-9a-zA-Z-.]+):([0-9]+)/([0-9a-z.-]+)(((/[0-9a-zA-Z.-_]+)*)?)` note the sequence of `-` in last regex group. 

**Expected behavior**
triton should work as long as path is valid.

**Comment by CoderHam** [comment]
Thank you for bringing this to our notice. We will fix this for the next release

**Comment by CoderHam** [comment]
@24hours the bucket name itself cannot contain `_` as mentioned [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html). I can test the regex you gave me but as I understand the order of the `-` should not matter.

**Comment by 24hours** [comment]
Hi, 

You are right, bucket name cannot contain `_` it my oversight on bug reporting. 

`.-_` imply range between `.` to `_` , `._-` will match character between `.`, `-`, `_`

you may refer this answer on this https://stackoverflow.com/questions/3028642/regular-expression-for-letters-numbers-and?rq=1
