### ISSUE TITLE
perfclient shows weirdly low throughput compared to client application

### ISSUE THREAD

**Issue by data-panda** [NVIDIA/triton-inference-server#1544]
I have a model with a configuration as follows

```
...
max_batch_size: 2
input [
   {
      name: "input_1"
      data_type: TYPE_FP32
      format: FORMAT_NHWC
      dims: [ -1, -1, 1 ]
   }
]
output [
   {
      name: "conv2d_19/Sigmoid"
      data_type: TYPE_FP32
      dims: [ -1, -1, 1 ]
   }
]
instance_group [
   {
      count: 2
      kind: KIND_GPU
   }
]
...
```

I execute the perf client as follows

```shell
./perf_client -v -u localhost:8000 -m model_name --input-data random --shape input_1:912,464,1 --percentile=95
```

While performing the inference with concurrence=1, I am getting a throughput data as follows:

```
Client:
    Request count: 5
    Throughput: 1 infer/sec
    p50 latency: 1026963 usec
    p90 latency: 1030303 usec
    p95 latency: 1030303 usec
    p99 latency: 1030303 usec
    Avg HTTP time: 1007446 usec (send 985 usec + response wait 569591 usec + receive 436870 usec)
  Server:
    Request count: 6
    Avg request latency: 45210 usec (overhead 7 usec + queue 51 usec + compute 45152 usec)

Inferences/Second vs. Client p95 Batch Latency
Concurrency: 1, throughput: 1 infer/sec, latency 1030303 usec
```

This inference throughput of `1 infer/sec` is way lower than the client application that processes 996 of such image tiles in roughly 30 sec with some bits of pre and post processing that too using a python api.

```python
...
_ = infer_ctx.async_run(partial(completion_callback, user_data, idx, tile, pads),
                                            {input_name: [tile_data]},
                                            {output_name: InferContext.ResultFormat.RAW},
                                            batch_size)
...
.
.
.
...
# Wait for deferred items from callback functions
(infer_ctx_, request_id_, idx_, tile_, pads_) = user_data._completed_requests.get()
# Process results
result = infer_ctx_.get_async_run_results(request_id_)
...
```

Any thoughts on why perf_client is reporting so low numbers?

**Comment by deadeyegoodwin** [comment]
The server latency is showing that it only takes 45210 use for the server to process each request. But the time the client spends waiting for the response is > 1 second [ 1007446 usec (send 985 usec + response wait 569591 usec + receive 436870 usec) ]. 

What is the size of the output?
Is your script sending one request at  a time and waiting for the response to send the next? That is what perf_client concurrency == 1 does?
Can you share the model so we can reproduce?

**Comment by data-panda** [comment]
@deadeyegoodwin thanks for the revert and pointing me to the observation that the client spends much larger time is waiting for the response . Since I am not sure whether I can share the model openly, i performed the same test on the `resnet50_netdef` model available by following the steps given in the [docs](https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/run.html)

```shell
$ git checkout r20.03
$ cd docs/examples
$ ./fetch_models.sh
```
Running the server from a singularity container for v20.03. 

Executed the `perf_client` as follows:
```shell
./perf_client -u localhost:8000 -m resnet50_netdef --percentile=95
```
and obtained the results as follows:

```
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using p95 latency

Request concurrency: 1
  Client:
    Request count: 15
    Throughput: 3 infer/sec
    p50 latency: 322922 usec
    p90 latency: 329214 usec
    p95 latency: 329214 usec
    p99 latency: 372848 usec
    Avg HTTP time: 316797 usec (send/recv 321 usec + response wait 316476 usec)
  Server:
    Request count: 20
    Avg request latency: 6453 usec (overhead 4 usec + queue 54 usec + compute 6395 usec)

Inferences/Second vs. Client p95 Batch Latency
Concurrency: 1, throughput: 3 infer/sec, latency 329214 usec
```

This also shows a miserable throughput of `3 infer/sec` (HTTP time >> server time). As shown in the results [here](https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/optimization.html), I see that for a concurrency of 1, triton is reporting a throughput of `159 infer/sec` (*not sure about the hardware used to obtain this result*).

P.S> I am running inference on a node with 2 Tesla V100s. Here is the model config file: [link](https://github.com/NVIDIA/triton-inference-server/blob/master/docs/examples/model_repository/resnet50_netdef/config.pbtxt)

**Comment by data-panda** [comment]
Just to add to those numbers, I ran with shared memory flags to see if the number improves. Here are results:

1. `./perf_client -u localhost:8000 -m resnet50_netdef --percentile=95 --shared-memory=system`
```shell
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using p95 latency

Request concurrency: 1
  Client:
    Request count: 44
    Throughput: 8.8 infer/sec
    p50 latency: 112920 usec
    p90 latency: 113084 usec
    p95 latency: 117055 usec
    p99 latency: 121981 usec
    Avg HTTP time: 112999 usec (send/recv 0 usec + response wait 112999 usec)
  Server:
    Request count: 54
    Avg request latency: 6870 usec (overhead 7 usec + queue 75 usec + compute 6788 usec)

Inferences/Second vs. Client p95 Batch Latency
Concurrency: 1, throughput: 8.8 infer/sec, latency 117055 usec
```

2. `./perf_client -u localhost:8000 -m resnet50_netdef --percentile=95 --shared-memory=cuda`
```shell
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using p95 latency

Request concurrency: 1
  Client:
    Request count: 45
    Throughput: 9 infer/sec
    p50 latency: 112964 usec
    p90 latency: 114051 usec
    p95 latency: 114997 usec
    p99 latency: 125005 usec
    Avg HTTP time: 113130 usec (send/recv 0 usec + response wait 113130 usec)
  Server:
    Request count: 54
    Avg request latency: 6981 usec (overhead 7 usec + queue 78 usec + compute 6896 usec)

Inferences/Second vs. Client p95 Batch Latency
Concurrency: 1, throughput: 9 infer/sec, latency 114997 usec
```

As you can see the HTTP request's **response wait time** is way overpowering to make the end result meaningless. Any clues as to what is happening here?

**Comment by data-panda** [comment]
My initial thoughts were if there is something fishy with my configuration, hence I spawned a cloud VM on AWS with Tesla V100 and started the Triton Server as a docker instance 
```
docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/home/ubuntu/triton-inference-server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:20.03-py3 trtserver --model-repository=/models
``` 
and here are the results

```shell
uname@hostname:~/triton-inference-server/clients/bin$ ./perf_client -m resnet50_netdef --percentile=95
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using p95 latency

Request concurrency: 1
  Client:
    Request count: 27
    Throughput: 5.4 infer/sec
    p50 latency: 185022 usec
    p90 latency: 186256 usec
    p95 latency: 186877 usec
    p99 latency: 187092 usec
    Avg HTTP time: 185264 usec (send/recv 257 usec + response wait 185007 usec)
  Server:
    Request count: 32
    Avg request latency: 183636 usec (overhead 14 usec + queue 34 usec + compute 183588 usec)

Inferences/Second vs. Client p95 Batch Latency
Concurrency: 1, throughput: 5.4 infer/sec, latency 186877 usec
```

And I see somewhat similar results. Less throughput `5.4 infer/sec` on account of higher response wait time. This is the `resnet50_netdef` model provided in the Triton distribution (after fetching it from the web).

**Comment by data-panda** [comment]
@deadeyegoodwin David, did you or anyone else got time to look into this? Do these numbers (for `resnet50` appear realistic ?

Thanks!

**Comment by deadeyegoodwin** [comment]
We are working on a couple of releases so we haven't had a change yet. We will try to get to it soon.

**Comment by deadeyegoodwin** [comment]
Not sure what is going on. You should expect much higher numbers from resnet50 in general. Using the latest 20.03.1 release (but earlier releases should be similar in perf), running on a TitanRTX with the same resnet50_netdef model:

```
$ perf_client -m resnet50_netdef --percentile=95
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using p95 latency

Request concurrency: 1
  Client: 
    Request count: 777
    Throughput: 155.4 infer/sec
    p50 latency: 6427 usec
    p90 latency: 6716 usec
    p95 latency: 6753 usec
    p99 latency: 7627 usec
    Avg HTTP time: 6433 usec (send/recv 151 usec + response wait 6282 usec)
  Server: 
    Request count: 933
    Avg request latency: 4933 usec (overhead 6 usec + queue 34 usec + compute 4893 usec)

Inferences/Second vs. Client p95 Batch Latency
Concurrency: 1, throughput: 155.4 infer/sec, latency 6753 usec
```

That is with concurrency = 1, which is how to get min latency, not max thoughput and still seeing 155 infer/sec. For high throughput you want to use more concurrency from perf_client to have more requests in-flight (and to get large throughput increases on the server side you can turn on dynamic batcher and maybe use multiple model instances... as explained in the optimization section of the docs). But if we just increase perf_client concurrency:

```
perf_client -m resnet50_netdef --percentile=95 --concurrency-range 2
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using p95 latency

Request concurrency: 2
  Client: 
    Request count: 1052
    Throughput: 210.4 infer/sec
    p50 latency: 9496 usec
    p90 latency: 9548 usec
    p95 latency: 9563 usec
    p99 latency: 9591 usec
    Avg HTTP time: 9498 usec (send/recv 209 usec + response wait 9289 usec)
  Server: 
    Request count: 1263
    Avg request latency: 7988 usec (overhead 5 usec + queue 3254 usec + compute 4729 usec)

Inferences/Second vs. Client p95 Batch Latency
Concurrency: 2, throughput: 210.4 infer/sec, latency 9563 usec
```

**Comment by data-panda** [comment]
@deadeyegoodwin David, did you or anyone else from your team got time to look into this? Are these numbers in the same ballpark of what you would expect specially with `resnet50_netdef` model ?

**Comment by data-panda** [comment]
@deadeyegoodwin David, thanks! This is really suprising. I am running it from a docker container pulled from NGC. The version is 20.03. I downloaded the perbuilt client package from the github release page.

a) In your case, is the sever instantiated withing a docker container ?
b) Do you think pre-built library could be a possible issue here?

I don't expect any other dis-similarity between your configuration and my configuration. That's really strange!

**Comment by deadeyegoodwin** [comment]
I just used the container from NGC. Can you try running with just one instance of the model, and possibly try a TF model. There are some issues with PyTorch framework when running multiple instances but that shouldn't impact caffe2... but still worth trying.

**Comment by data-panda** [comment]
@deadeyegoodwin David, we have finally found the reason for the dismal performance and that was a proxy server settings which was slowing down the http response time. Thanks for sharing the inference throughput results at your end which helped us in finding the actual issue.

**Comment by deadeyegoodwin** [comment]
Glad you found the issue!
