### ISSUE TITLE
Docker Image Not Found

### ISSUE THREAD

**Issue by buttonman** [NVIDIA/triton-inference-server#1554]
**Description**
docker pull nvcr.io/nvidia/tritonserver:20.03-tf1-py3

nvcr.io/nvidia/tritonserver:20.03-tf1-py3 not found: manifest unknown: manifest unknown

**Triton Information**
20.03

nvcr.io/nvidia/tritonserver:20.03-py3 is working

**To Reproduce**

in document, to use Tensorflow 1.15, need a tag 20.03-tf1-py3, 

but folloing is not working
docker pull nvcr.io/nvidia/tritonserver:20.03-tf1-py3

**Comment by deadeyegoodwin** [comment]
Currently triton only supports TF1, so the nvcr.io/nvidia/tritonserver:20.03-py3 container has TF1 support. TF2 support is planned for future.

The documentation mentioning the *-tf1-* naming is for the TF container only.
