### ISSUE TITLE
max_workspace_size_bytes can't set in config.pbtxt

### ISSUE THREAD

**Issue by loveppdog** [NVIDIA/triton-inference-server#1555]
I use triton server docker 20.03.
I try to set precision_mode in config.pbtxt and can load model successful.
But if I set max_workspace_size_bytes or minimum_segment_size, it always loads failed like:
error: creating server: INTERNAL - failed to load all models
 How to solve it ? Thanks

optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters
        {
                key: "precision_mode" value: "FP16"
                key: "minimum_segment_size" value: 3
                key:"max_workspace_size_bytes" value:(11<32)
        }
   }]
}}

**Comment by deadeyegoodwin** [comment]
Run the server with --log-verbose=1 and share the console output, there may be more information in there to help determine what is happening.

**Comment by GuanLuo** [comment]
The parameter value should be in string type, so "max_workspace_size_bytes" should be an integer string
