### ISSUE TITLE
tensorflow 1.13.1 model and triton server 20.03 

### ISSUE THREAD

**Issue by loveppdog** [NVIDIA/triton-inference-server#1556]
Trtion server is 20.03.
I want to use tensorflow-tensorRT optimization by setting config.pbtxt like
optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP16" }}]
}}

But Our models are trained in tensorflow 1.13.1 and does it match triton sever 20.03? 
I need to train model in high tensorflow version? Thanks.

**Comment by deadeyegoodwin** [comment]
What happened when you did that? It is best to have TF match versions but is sometimes not required because TF has fairly good backwards compatbility. If you can't move your TF forward to the 20.03 version, you can try to find a Triton that uses TF 1.13.1. See the Triton release notes.

**Comment by deadeyegoodwin** [comment]
Closing, reopen if still having a problem.
