### ISSUE TITLE
Strange GPU usage on Jetson Nano

### ISSUE THREAD

**Issue by turowicz** [NVIDIA/triton-inference-server#1557]
I have the following characteristic of using the GPU reported by tegrastats:

![image](https://user-images.githubusercontent.com/1055391/83022273-8a25ea80-a02b-11ea-9d26-5778288958b7.png)

I would expect the usage to be constantly above certain level and never go to 0. I am doing real-time video camera analysis and I am getting some very strange behaviour, that the time seems to be slowing down in the entire system.

I am running SSD mobilenet v2 COCO with TensorRT optimizations.

Any ideas what's going on? Is this Trtis related or should I look in my code?

**Comment by deadeyegoodwin** [comment]
I don't know how to interpret those values relative to what you are expecting. Does the model run correctly at the expected performance? Or are you finding it runs slower than expected?

**Comment by turowicz** [comment]
Yes it is running as expected. I flood it with images to infer and that is the strangeness - possibly indicates that is runs on CPU, but the kind is GPU in Trtis.

**Comment by deadeyegoodwin** [comment]
I'm not familiar enough with tegrastats to say. What does CPU load look like? If you set the kind to CPU does performance or CPU load change (I would expect perf to decrease and load to increase).

**Comment by turowicz** [comment]
I will check that. Lets close the issue for now.
