### ISSUE TITLE
Compatibility of Instance Groups Setting

### ISSUE THREAD

**Issue by yasirofficial** [NVIDIA/triton-inference-server#1566]
**Is your feature request related to a problem? Please describe.**
I have the models (TFSavedModel) with a configuration to run on a specific gpu. Something like this:

```
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  },
  {
    count: 2
    kind: KIND_GPU
    gpus: [ 1, 2 ]
  }
]
```
Is there a way to support same model config on triton server while using a single-gpu machine?

**Describe the solution you'd like**
Same model config should work with single-gpu machine, running all the models on gpu 0 by default.

**Describe alternatives you've considered**

**Additional context**
Need to use same AWS S3 bucket with models with each triton server, be it a single gpu instance or multiple gpu instance

**Comment by yasirofficial** [comment]
Do we have anything like a version control or environment control for same models in Triton? Like can I specify something in a model config or the container run command to pull only specific models meant for prod, or stage or some specific version of that model without keeping the models separately (as in keeping all models on same location)

**Comment by deadeyegoodwin** [comment]
Currently when you explicit list GPUs in instance_group those GPUs must be present. There is no "soft" setting to have Triton try to map those settings to fewer GPUs.

You can use --model-control-mode=explicit and --load-model flags to load only some of the models from the repository on server startup. See the --help description and https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/model_management.html#model-management
