### ISSUE TITLE
instance_group issue 

### ISSUE THREAD

**Issue by loveppdog** [NVIDIA/triton-inference-server#1567]
Test on Triton server 20.03 and models  are trained in tensorflow1.13.1.

I want to set model1(only using GPU6) and model2(only using GPU7) because our models need large max_workspace_size_bytes to optimazation.

So I write config like:
model1:
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 6 ]
  }
]

model2:
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 7 ]
  }
]
When I Run like:
export CUDA_VISIBLE_DEVICES=6,7
trtserver --model-store=/data/  --grpc-infer-thread-count=16 --grpc-stream-infer-thread-count=16

Some issue log likes and how to fix this issue? Thanks.

Creating trt-gpu-serving-zxold-210-2003 ... done
Attaching to trt-gpu-serving-zxold-210-2003
trt-gpu-serving-zxold-210-2003    | 2020-05-28 19:19:45.059522: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
trt-gpu-serving-zxold-210-2003    | I0528 11:19:45.103087 18 metrics.cc:164] found 8 GPUs supporting NVML metrics
trt-gpu-serving-zxold-210-2003    | I0528 11:19:45.109310 18 metrics.cc:173]   GPU 0: GeForce RTX 2080 Ti
trt-gpu-serving-zxold-210-2003    | I0528 11:19:45.115843 18 metrics.cc:173]   GPU 1: GeForce RTX 2080 Ti
trt-gpu-serving-zxold-210-2003    | I0528 11:19:45.122639 18 metrics.cc:173]   GPU 2: GeForce RTX 2080 Ti
trt-gpu-serving-zxold-210-2003    | I0528 11:19:45.130587 18 metrics.cc:173]   GPU 3: GeForce RTX 2080 Ti
trt-gpu-serving-zxold-210-2003    | I0528 11:19:45.138430 18 metrics.cc:173]   GPU 4: GeForce RTX 2080 Ti
trt-gpu-serving-zxold-210-2003    | I0528 11:19:45.146622 18 metrics.cc:173]   GPU 5: GeForce RTX 2080 Ti
trt-gpu-serving-zxold-210-2003    | I0528 11:19:45.155051 18 metrics.cc:173]   GPU 6: GeForce RTX 2080 Ti
trt-gpu-serving-zxold-210-2003    | I0528 11:19:45.165410 18 metrics.cc:173]   GPU 7: GeForce RTX 2080 Ti
trt-gpu-serving-zxold-210-2003    | I0528 11:19:45.166174 18 server.cc:120] Initializing Triton Inference Server
trt-gpu-serving-zxold-210-2003    | E0528 11:19:45.649714 18 server.cc:138] failed to enable peer access for some device pairs
trt-gpu-serving-zxold-210-2003    | E0528 11:19:45.660432 18 model_repository_manager.cc:1519] instance group coarse_lung_seg_0 of model coarse_lung_seg specifies invalid or unsupported gpu id of 6. The minimum required CUDA compute compatibility is 6.000000

**Comment by deadeyegoodwin** [comment]
When you set:
export CUDA_VISIBLE_DEVICES=6,7

Only GPU 6 and 7 are visible to Triton, but they appear as GPU 0 and GPU 1 (that is just how CUDA_VISIBLE_DEVICES works). So you must use 0 and 1 in your model configuration. The error message could be clearer so we will look into improving that.
