### ISSUE TITLE
docker run triton-inference-server error when I replace the models with my own.

### ISSUE THREAD

**Issue by HeyMrYu** [NVIDIA/triton-inference-server#1588]
when I  use my models, and run the following code:
` nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p 8000:8000 -p 8001:8001 -p 8002:8002 -v /model/path/triton-inference-server/docs/examples/model_repository:/models 10.9.1.196/nvidia/tensorrtserver:19.08-py3 trtserver --model-store=/models`

I got error:
`trtserver: engine.cpp:1104: bool nvinfer1::rt::Engine::deserialize(const void*, std::size_t, nvinfer1::IGpuAllocator&, nvinfer1::IPluginFactory*): Assertion `size >= bsize && "Mismatch between allocated memory size and expected size of serialized engine."' failed.`

Looking forward to your reply. Thank you

**Comment by deadeyegoodwin** [comment]
19.08 is an old release, I recommend you update. But in any case you need to make sure that the version of TensorRT you used to create the model matches the version of TensorRT used by Triton (you can find that in the Triton release notes).

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if you still have an issue when using a version of TensorRT that matches what Triton uses.
