### ISSUE TITLE
Problems using Pyrthon API to access the triton server

### ISSUE THREAD

**Issue by andrey999333** [NVIDIA/triton-inference-server#1593]
**Description**

The python api produce error:

`tritongrpcclient.utils.InferenceServerException: [StatusCode.UNIMPLEMENTED] `

**Triton Information**

tritonserver:20.03-py3
tritongrpcclient 1.12.0

**Are you using the Triton container or did you build it yourself?

Container from the official image

**To Reproduce**
I have created a small toy model in pytorch, saved it in the necessary format (using torch.jit.save()) and mapped the volumes as described in the documentation. Also added config file in the form:

```
name: "model1"
platform: "pytorch_libtorch"
max_batch_size: 8
input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 1, 28, 28 ]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]
```

The server with this model looks working fine. I checked it out with request: 

`curl localhost:8000/api/status`

The response is as expected:

```
id: "inference:0"
version: "1.12.0"
uptime_ns: 11513516322
model_status {
  key: "model1"
  value {
    config {
      name: "model1"
      platform: "pytorch_libtorch"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      max_batch_size: 8
      input {
        name: "INPUT__0"
        data_type: TYPE_FP32
        dims: 1
        dims: 28
        dims: 28
      }
      output {
        name: "OUTPUT__0"
        data_type: TYPE_FP32
        dims: 10
      }
      instance_group {
        name: "model1"
        count: 1
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "model.pt"
      optimization {
        input_pinned_memory {
          enable: true
        }
        output_pinned_memory {
          enable: true
        }
      }
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
        ready_state_reason {
        }
      }
    }
  }
}
ready_state: SERVER_READY

```
Then i tried to use python api as following:

```
from tritongrpcclient.core import InferenceServerClient
client = InferenceServerClient('localhost:8001')
client.is_server_ready()
```

and i've got an error message:

`tritongrpcclient.utils.InferenceServerException: [StatusCode.UNIMPLEMENTED]
`

**Expected behavior**

get a message (in this case boolean True) indicating that server is ready.

**Comment by deadeyegoodwin** [comment]
It is good that you are using the new Triton clients, but you need to do the following:
- Use the just released 20.03.1 version of triton. It is on the same NGC registry, look under "Tags" for 20.03.1-py3: https://ngc.nvidia.com/catalog/containers/nvidia:tritonserver/tags
- When launching the server use --api-version=2 flag.

Note that this is a beta release of the new triton clients. In 20.06 release the --api-version=2 flag will not be needed.
