### ISSUE TITLE
Release dates 20.05 and 20.06

### ISSUE THREAD

**Issue by lindaterlouw** [NVIDIA/triton-inference-server#1598]
For a project I would like to replace a custom inference engine with Triton. I see you are currently migrating from V1 to V2 and I would like skip V1 :-). Do do have any idea when 20.05 and 20.06 will be released? In the documentation I see that 20.05 is on track for late May, but it does not seem to be release yet.

Thanks for your excellent work!

**Comment by deadeyegoodwin** [comment]
You are right to move directly to V2. We just had the 20.03.1 that includes V2 support (equivalent to what was talked about for 20.05 release, for non-Triton reasons we needed to rename the release). If you follow the project I believe you will get emails about releases. Read the Roadmap section of the README on the 20.03.1 branch to learn more.

I see that the master branch README needs updating... I will do that now.

**Comment by rithd** [comment]
https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/index.html

Could you update the doc for new release V2 image, so that I can get more new feature for the V2 Triton :)

**Comment by deadeyegoodwin** [comment]
Doc update is in progress: https://github.com/NVIDIA/triton-inference-server#documentation

**Comment by deadeyegoodwin** [comment]
Master documentation has been updated and it includes V2-based content: https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/index.html
