### ISSUE TITLE
Is triton inference server same with TRTIS?

### ISSUE THREAD

**Issue by jusonn** [NVIDIA/triton-inference-server#1621]
I could not find document about the difference between trtis and triton.
Is there any difference? or not?

If there is a doc, sorry for didn't find it carefully.
please reply that link.

**Comment by nphilou** [comment]
Hi, I guess so, TRTIS was for TensorRT Inference Server but they changed to Triton to avoid confusion since it not only supports TensorRT but many backends. (can't find the exact link about that)

**Comment by deadeyegoodwin** [comment]
The description was on the master branch README for some time. That readme is now updated but you can still see the TRTIS -> Triton description on the 20.03.1 README. https://github.com/NVIDIA/triton-inference-server/tree/r20.03.1#roadmap
