### ISSUE TITLE
/opt/tritonserver/nvidia_entrypoint.sh: line 93: exec: --: invalid option

### ISSUE THREAD

**Issue by globalmaster** [NVIDIA/triton-inference-server#1632]
**Description**
I run:   docker pull nvcr.io/nvidia/tritonserver:20.03.1-py3
then run:   nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/home/hezhiming/triton-inference-server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:20.03.1-py3 --model-repository=/models
I got this error:   /opt/tritonserver/nvidia_entrypoint.sh: line 93: exec: --: invalid option

How can I solve this error?

**Comment by nieksand** [comment]
In between these two parts:
`nvcr.io/nvidia/tritonserver:20.03.1-py3 --model-repository=/models`

You need to specify the binary name.  It used to be `trtserver`.  The latest release may have switched it to `tritonserver`
