### ISSUE TITLE
Distribute model across multiple GPUs

### ISSUE THREAD

**Issue by whillas** [NVIDIA/triton-inference-server#1644]
We have multiple sets of models with each set having over 100 models each. Say the total of Set1 is around 10GiB and the total of another is 20GiB. Up until recently (yesterday) we could put each set of models into their own bucket and run one Triton server per GPU (as the model sets were fitting on one GPU each) but the number and size of the models has increased and so this is no longer possible as the GPU RAM is limited.

I know Triton tries to run all the models on all the GPUs if you give it more than one GPU. What we need is for it to run just 1 copy of each model _across_ all the GPUs we give it. Ideally with some ability to fine tune i.e. round robin, or fill up 1 GPU before moving to the next, or just balance the models so the GPUs are as equally full as possible.

Right now we're going to have to write some complicated script to take all the models group them into buckets and run them across multiple Triton servers, 1 per GPU on the same inference machine. Not fun. The other alternative is to keep buy larger GPUs which is already 

I don't know if this is a common problem when doing inference in production.

**Comment by deadeyegoodwin** [comment]
I don't think you are asking about the mechanics of how to have Triton place certain models only on certain GPUs, but just in case.... you can do that with instance_group setting in the model config: https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/model_configuration.html#instance-groups

I think you are generally asking about what we call "model orchestration". That is the problem of having:
* a large number of (potentially changing) models
* a latency and throughput requirement for each model (also potentially changing dynamically)
* a set of systems with GPUs to run the models

The problem is how to map the models onto the systems/GPUs so that the latency and throughput requirements are met, dynamically changing the mapping as necessary. There are simple, manual solutions for some cases (as you have described) but you are asking for a more general solution. Is that your question?

**Comment by yasirofficial** [comment]
@deadeyegoodwin what's the general solution to achieve "model orchestration"? 
The instance-group setting (as far as I know) are static. How to make those dynamic, changing as per the needs on runtime?

**Comment by whillas** [comment]
Yeah, a more general solution. we looked at the `instance_group` solution but we're taking advantage of the auto configuration for models without `config.pbtxt`s since generating and updating these for hundreds of models is rather tedious and error prone (also, how do you automate tests for that?)

Ideally we could just give Triton all the models (around 230) and some scaling schema and it would run at least one of each on _a_ GPU which is what we really need.

A bonus would be if it scaled (up & down) the number of models based on load as we know some models are needed for every inference and are slower than other which are less popular. But at the moment that's a "nice to have" atm. (I guess you'd also need to make sure popular models are not all on the same GPU)

**Comment by deadeyegoodwin** [comment]
Here's a high-level doc of how Triton thinks about the problem of "model orchestration": https://docs.google.com/document/d/1iM0GMiO_ysAWEjk-9WGIYLxuBDXR2dcy09jI8YgYtsc/edit

Triton itself is not the entire solution. There need to be components around it to manage the models and to decide which models should be mapped to which systems (and therefore GPUs) over time.

You should look at the KFServing project. Triton is active in that project and they are working on a model orchestration system that will address both CPUs and GPUs (as well as other accelerators): https://github.com/kubeflow/kfserving

**Comment by whillas** [comment]
Looking at building a custom solution now but having to generate a set of `config.pbtxt` for each model which are going to be site/deployment specific as its based on the number of GPUs available. So on premise there might be 4 but on a cloud instance there might be 1 or 2 or 10 etc. Also, if we want role back of model version we ether have to delete the version(s) we don't want or update the config.pbtxt. This kind of makes deploying from a bucket impossible if the models are shared from there (which is the point of using a bucket).

**Comment by deadeyegoodwin** [comment]
Depending on your other requirements and restrictions, it is likely better to virtually partition your "datacenter" into 1 GPU nodes and have a Triton running on each of the virtual nodes. That way the default behavior of having 1 model per GPU is what you want and you use node auto-scaling (which can be driven by metrics) to increase of decrease the number of nodes that hold a model. As an example the following setup can be used with a system like Kubernetes (of KFServing which is built on kubernetes). It greatly simplifies the model orchestration problem by not grouping together different models on a GPU (so it can be wasteful of GPUs if there are models that get only a small number of requests):

1. For each model generating the config.pbtxt is part of preparing the model for deployment and so must be done once. The primary things to consider is the appropriate dynamic batching and instance group settings needed to get the individual model to have the desired performance on the deployment GPU (see optimization section of docs).
2. Each model is deployed in its own, scale-to-zero cluster composed of single-GPU nodes. Kubernetes (or KFServing) manages the scale-up/down of each cluster based on model demand.
3. Models are removed from datacenter by removing the corresponding cluster.
