### ISSUE TITLE
instance_group and --concurrency-range

### ISSUE THREAD

**Issue by globalmaster** [NVIDIA/triton-inference-server#1661]
**Description**
The instance-group setting can be used to place multiple execution instances of a model on every GPU or on only certain GPUs by using parameters "count" and "gpus".  perf_client  --concurrency-range can be used to set the outstanding inference requests. What is the relationship and difference between instance_group "count" and perf_client  "--concurrency-range"  ?

**Triton Information**
1.13.0 pulled from NGC

**Comment by globalmaster** [comment]
@sublee @dougn @swarren @aaronp24

**Comment by swarren** [comment]
@globalmaster I'm now a member of this project, but simply a repo admin. Please never @ mention people when filing bugs. The appropriate people are always contacted automatically. Thanks.

**Comment by GuanLuo** [comment]
They are separated concepts, "instance group" is on the server side, "concurrency range" is on the client side. "Concurrency range" controls the rate of requests to be produced and sent to the server, while "instance group" controls how many instances of the model are used to consume those requests.
