### ISSUE TITLE
Fine grained Division

### ISSUE THREAD

**Issue by globalmaster** [NVIDIA/triton-inference-server#1662]
Can we specify GPU Memory and utilization rate of GPU(the utilization rate of CUDA Core) in triton?

**Comment by globalmaster** [comment]
@sublee @dougn @swarren @aaronp24

**Comment by sublee** [comment]
@globalmaster I'm not a core contributor to this project. Please do not mention me in arbitrary issues.

**Comment by deadeyegoodwin** [comment]
Triton is a CUDA application. In general, you cannot arbitrarily partition the GPU memory and compute across CUDA applications. That said, you should look into CUDA MPS as it may have some features you are interested in. Also, looking forward, the recently announced Ampere MIG also provides GPU partitioning capabilities: https://www.nvidia.com/en-us/data-center/nvidia-ampere-gpu-architecture/
