### ISSUE TITLE
GRPC v2 low bandwidth

### ISSUE THREAD

**Issue by cloudhan** [NVIDIA/triton-inference-server#1665]
**Description**
I am testing grpc v2 api on r20.05 branch. And observe severe performance degeneration when couple v2 api with tf model

![image](https://user-images.githubusercontent.com/1279292/84723571-75989a80-afb8-11ea-9f7e-bb4fbad14a41.png)

In the above sheet, `preprocess` is tf graphdef model generated with script listed below. I use both python grpc stub generated directly from `.proto` files. They are both single instance single thread request client, and the bandwith is as listed. The v1 is much faster than v2. The performance is extremely low when using v2 api with a tf model, the onnx `cnn` is not much affected but the peak bandwidth is only half of v1's.

**Triton Information**
What version of Triton are you using?
branch r20.05

Are you using the Triton container or did you build it yourself?

I build it myself

**To Reproduce**
Steps to reproduce the behavior.
use the following `preprocess` generator:
```python
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("output_dir")
parser.add_argument("output_name")
parser.add_argument("--hw", required=True, type=str)
parser.add_argument("--means", default="[0., 0., 0.,]", type=str, help="RGB, 0-255")
parser.add_argument("--stds", default=None, help="RGB, 0-255")
args = parser.parse_args()

# import tensorflow as tf
import tensorflow.compat.v1 as tf

decoded_image_hwc_rgb = tf.placeholder(tf.uint8, shape=(None, None, None, 3), name="image_hwc_rgb")
# with tf.device('/gpu:0'):
with tf.device('/cpu:0'):
    # only float and double is supported on GPU
    decoded_image_hwc_rgb = tf.cast(decoded_image_hwc_rgb, tf.float32)
    new_height, new_width = eval(args.hw)
    resized = tf.image.resize(decoded_image_hwc_rgb, (new_height, new_width))
    resized = tf.image.resize(resized, (25, 25)) # resize again to avoid response message overhead during testing.

    shifted = resized - tf.constant(eval(args.means), dtype=tf.float32)

    if args.stds is not None:
        normalized = shifted / tf.constant(eval(args.stds), dtype=tf.float32)
    else:
        normalized = shifted

    # normalized = tf.expand_dims(normalized, 0)
    nchw = tf.transpose(normalized, [0, 3, 1, 2])
    nchw = tf.identity(nchw, name="nhwc")

    with tf.Session() as sess:
        import numpy as np
        import tqdm
        data = np.ones((2, 500,500,3), dtype=np.uint8)
        with tqdm.tqdm(mininterval=0.1) as pbar:
            for i in range(1500):
                pbar.update(1)
                result = sess.run(nchw, {decoded_image_hwc_rgb: data})
        print(result.shape)

    gdef = nchw.graph.as_graph_def()
    tf.io.write_graph(gdef, args.output_dir, args.output_name, as_text=False)
```
and you can generate the model with 
`python generator.py . model.graphdef --hw '(224, 224)' --means='[123.0, 117.0, 104.0]'`

Model configuration is as following:
```pbtxt
name: "preprocess224"
platform: "tensorflow_graphdef"
max_batch_size: 128
dynamic_batching {
  preferred_batch_size: [ 16, 4, 1 ]
  max_queue_delay_microseconds: 50
}
optimization {
  input_pinned_memory: { enable: false }
#   output_pinned_memory: { enable: false }
}
input [
  {
    name: "image_hwc_rgb"
    data_type: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [ -1, -1, 3 ]
  }
]
output [
  {
    name: "nhwc"
    data_type: TYPE_FP32
    dims: [ 3, 25, 25 ]
  }
]
instance_group [
  {
    count: 4
    kind: KIND_GPU
  }
]
```

for the `cnn`, I am sorry I cannot provide it with you, it is a onnx model converted from mxnet. ResNet archtectured.

```pbtxt
name: "cnn"
platform: "onnxruntime"
max_batch_size: 128
dynamic_batching {
  preferred_batch_size: [ 16, 4, 1 ]
  max_queue_delay_microseconds: 50
}
input [
  {
    name: "data"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 3, 224, 224 ]
  }
]
output [
  {
    name: "l2normalization0"
    data_type: TYPE_FP32
    dims: [ 128 ]
  }
]
instance_group [
  {
    count: 4
    kind: KIND_GPU
  }
]
```

**Expected behavior**

GRPC v2 API should match v1 API bandwidth and inference time.

**Comment by deadeyegoodwin** [comment]
You should not use the 20.05 branch, it was never released. I'm not sure how you are even building it since it requires dependencies fro nvcr.io that don't even exist. You can try the V2 API using the 20.03.1 release or build from the master branch (there is also the 20.06 release coming up in a couple of weeks). V2 is still  in beta and we have fixed some performance issues and turing is ongoing. It would be most helpful for us if you use the master branch and report any unexpected slowdowns compared to V1.

**Comment by cloudhan** [comment]
OK, I will test it in a few days and will report back the performance.

In terms of building, once you have source code and its dependent libraries, you can always build it ;)

**Comment by cloudhan** [comment]
The performace characteristic on master is basically the same as on branch r20.05

**Comment by cloudhan** [comment]
For a single trace with input image (500*500*3, batchsize=40),

```
    {
        "id": 8,
        "timestamps": [{
            "name": "GRPC_WAITREAD_START",
            "ns": 17125842648608115
        }]
    },
    {
        "id": 8,
        "timestamps": [{
            "name": "GRPC_WAITREAD_END",
            "ns": 17125844332704508
        }]
    },
    {
        "id": 8,
        "timestamps": [{
            "name": "InferGRPCToInput_START",
            "ns": 17125844333173848
        }]
    },
    {
        "id": 8,
        "timestamps": [{
            "name": "InferGRPCToInput_END",
            "ns": 17125844473501102
        }]
    },
    {
        "id": 8,
        "timestamps": [{
            "name": "GRPC_SEND_START",
            "ns": 17125844513748500
        }]
    },
    {
        "id": 8,
        "model_name": "preprocess224",
        "model_version": 1
    },
    {
        "id": 8,
        "timestamps": [{
            "name": "REQUEST_START",
            "ns": 17125844473611421
        }]
    },
    {
        "id": 8,
        "timestamps": [{
            "name": "QUEUE_START",
            "ns": 17125844473617338
        }]
    },
    {
        "id": 8,
        "timestamps": [{
            "name": "COMPUTE_START",
            "ns": 17125844473678141
        }]
    },
    {
        "id": 8,
        "timestamps": [{
            "name": "COMPUTE_INPUT_END",
            "ns": 17125844481867342
        }]
    },
    {
        "id": 8,
        "timestamps": [{
            "name": "COMPUTE_OUTPUT_START",
            "ns": 17125844513508930
        }]
    },
    {
        "id": 8,
        "timestamps": [{
            "name": "COMPUTE_END",
            "ns": 17125844513719432
        }]
    },
    {
        "id": 8,
        "timestamps": [{
            "name": "REQUEST_END",
            "ns": 17125844514000289
        }]
    },
    {
        "id": 8,
        "timestamps": [{
            "name": "GRPC_SEND_END",
            "ns": 17125844514028232
        }]
    }
```
`GRPC_WAITREAD` takes unexpected long time

Summary shows 
```
File: trace.json
Summary for preprocess224 (1): trace count = 7
GRPC infer request (avg): 1877143.714857143us
        Wait/Read (avg): 1689574.475us
        Send (avg): 315.4407142857143us
        Overhead (avg): 142368.94271428572us

        Handler (avg): 44884.85642857143us
                Overhead (avg): 304.45471428571426us
                Queue (avg): 110.24114285714286us
                Compute (avg): 44470.16057142857us
                        Input (avg): 12240.881428571429us
                        Infer (avg): 32040.36542857143us
                        Output (avg): 188.9137142857143us
```
Wait/Read takes 1.68s per request.

**Comment by cloudhan** [comment]
And `InferGRPCToInput` takes 140ms, which is also a huge overhead. (If you don't compare it to `GRPC_WAITREAD` :( )

**Comment by cloudhan** [comment]
I also notice low `extend` performance on request constructing 

```python
import time
import numpy as np
import grpc_service_pb2 as grpc_service_v2_pb2

def test_fill(length):
    img = np.zeros([length], dtype=np.uint8)

    request = grpc_service_v2_pb2.ModelInferRequest(model_name="preprocess224")
    request.inputs.add()

    f = img.flat
    start = time.time()
    request.inputs[0].contents.uint_contents.extend(f)
    end = time.time()

    print("Fill request with shape:", img.shape, "takes", end-start, "seconds")

for i in range(1, 4*1024*1024, 16*1024):
    test_fill(i)
```
![image](https://user-images.githubusercontent.com/1279292/85006074-3b7ff200-b18c-11ea-9cb2-c6e9c0a09386.png)

NOTE, this **will not** cause low bandwidth, since I construct a request in advance then repeatly use it of testing.

Might be related to https://github.com/protocolbuffers/protobuf/issues/1800

**Comment by deadeyegoodwin** [comment]
@tanmayv25 is looking into related issues.

**Comment by tanmayv25** [comment]
@cloudhan  Your observation of conforms with mine. The grpc is taking much longer time to read and parse the message with Version2 format. My guess is the nesting of the data content inside V2 protobuf message is having an adverse effect on the message reuse.

I have raised an issue with grpc and may be it will passed over to protobuf team.
https://github.com/grpc/grpc/issues/23231

@deadeyegoodwin As the performance of the new message format is so bad, should we add an extension to hold data in the top-level message ModelInferRequest similar to V2. We can better deal with the issue once we hear more from the gRPC team.

**Comment by deadeyegoodwin** [comment]
We may need to do that... or just change the GRPC design to be flatter so that it has better performance. There is no point in keeping the existing format if it has bad performance (and it is still in beta and so open to change).

**Comment by cloudhan** [comment]
Here is the profiling
![image](https://user-images.githubusercontent.com/1279292/85091471-0a4e0300-b21a-11ea-95f2-4b1b32142e59.png)

Deep in the call stack, there is a suspicious `ReadVarint32`. 
So I switched my request to
```python
    request = grpc_service_v2_pb2.ModelInferRequest(model_name="preprocess224")
    request.inputs.add()
    request.inputs[0].name = input_name
    request.inputs[0].datatype = "UINT8"
    request.inputs[0].shape.extend(img.shape)
    start = time.time()
    # request.inputs[0].contents.uint_contents.extend(img.flat)
    request.inputs[0].contents.raw_contents=img.tobytes()
    end = time.time()
    print("request fill time:", end - start)
    for i in range(30):
    # while True:
        print(i)
        start = time.time()
        response = grpc_stub.ModelInfer(request)
        print(time.time() - start)
    print(_repr.repr(response))
```

Using `raw_contents` instead of `uint_contents`, the bandwidth boost to 2Gbps. The cnn model is not affected (not that high impact like uint) by this due to using floating point input. This should be related with protobuf, it is doing encoding, see `https://developers.google.com/protocol-buffers/docs/encoding#structure`

**Comment by deadeyegoodwin** [comment]
So does using raw_contents resolve your issue? We are still looking onto the grpc/protobuf issue and may change the protocol to give higher performance.

**Comment by cloudhan** [comment]
I think this is just a walkaround. Free free to close this issue.
