### ISSUE TITLE
A shape problem

### ISSUE THREAD

**Issue by hcx1231** [NVIDIA/triton-inference-server#1682]
**Description**
I ran a tensorrt_plan model in trt server,and it was all OK.Then I wanted to add the image preprocess part into the trt server( libimagepreprocess.so was built from offical source), error showed: 
Invalid argument: in ensemble preprocess_ensemble, ensemble tensor preprocessed_image: inconsistent shape: [3,1280,1280] is inferred from model image_preprocess while [1,3,1280,1280] is inferred from model retinanet_plan.

As the  tensorrt_plan I used can not support dynamic batching,so I can not change the input shape in the config file of tensorrt_plan.And the output of preprocess can only support 3 dimensions,so I can not change the output shape in the config file of preprocess.
I added reshape:{shape:[1,3,1280,1280]} in the  output part in config file of preprocess,and it did not work.

all 3 config.pbtxt files was below:
1: image_preprocess
platform: "custom"
input {
  name: "INPUT"
  data_type: TYPE_STRING
  dims: 1
}
output {
  name: "OUTPUT"
  data_type: TYPE_FP32
  dims: 3
  dims: 1280
  dims: 1280
}
default_model_filename: "libimagepreprocess.so"
parameters {
  key: "format"
  value {
    string_value: "NCHW"
  }
}
parameters {
  key: "scaling"
  value {
    string_value: "INCEPTION"
  }
}

2: preprocess_ensemble
platform: "ensemble"
input {
  name: "INPUT"
  data_type: TYPE_STRING
  dims: 1
}
output {
  name: "scores"
  data_type: TYPE_FP32
  dims: 1
  dims: 100
  dims: 1
  dims: 1
}
output {
  name: "boxes"
  data_type: TYPE_FP32
  dims: 1
  dims: 400
  dims: 1
  dims: 1
}
output {
  name: "classes"
  data_type: TYPE_FP32
  dims: 1
  dims: 100
  dims: 1
  dims: 1
}
ensemble_scheduling {
  step {
    model_name: "image_preprocess"
    model_version: -1
    input_map {
      key: "INPUT"
      value: "INPUT"
    }
    output_map {
      key: "OUTPUT"
      value: "preprocessed_image"
    }
  }
  step {
    model_name: "retinanet_plan"
    model_version: -1
    input_map {
      key: "input.1"
      value: "preprocessed_image"
    }
    output_map {
      key: "boxes"
      value: "boxes"
    }
    output_map {
      key: "classes"
      value: "classes"
    }
    output_map {
      key: "scores"
      value: "scores"
    }
  }
}

3: retinanet_plan
platform: "tensorrt_plan"
input {
  name: "input.1"
  data_type: TYPE_FP32
  dims: 1
  dims: 3
  dims: 1280
  dims: 1280
}
output {
  name: "scores"
  data_type: TYPE_FP32
  dims: 1
  dims: 100
  dims: 1
  dims: 1
}
output {
  name: "boxes"
  data_type: TYPE_FP32
  dims: 1
  dims: 400
  dims: 1
  dims: 1
}
output {
  name: "classes"
  data_type: TYPE_FP32
  dims: 1
  dims: 100
  dims: 1
  dims: 1
}

**Comment by GuanLuo** [comment]
Dose your custom model also not support batching? Beside that, I think reshape should work, but note that for output, reshape specifies the shape produced by the model, and the dims for the output is the shape expected by Triton, so you should try the following for your custom model:
```
output {
name: "OUTPUT"
data_type: TYPE_FP32
dims: [1, 3, 1280, 1280]
reshape {
shape: [3, 1280, 1280]
}
}
```

**Comment by hcx1231** [comment]
> Dose your custom model also not support batching? Beside that, I think reshape should work, but note that for output, reshape specifies the shape produced by the model, and the dims for the output is the shape expected by Triton, so you should try the following for your custom model:
> 
> ```
> output {
> name: "OUTPUT"
> data_type: TYPE_FP32
> dims: [1, 3, 1280, 1280]
> reshape {
> shape: [3, 1280, 1280]
> }
> }
> ```

I tried this,and it showed :

E0619 00:57:32.671869 2133 dynamic_batch_scheduler.cc:252] Initialization failed for dynamic-batch scheduler thread 0: initialize error for 'image_preprocess': (7) expected single output with 3 dimensions, each dimension >= 1
I0619 00:57:32.672121 2133 custom_backend.cc:90] ~CustomBackend::Context image_preprocess_0_gpu0
E0619 00:57:32.673093 2133 model_repository_manager.cc:840] failed to load 'image_preprocess' version 1: Internal: Initialization failed for all dynamic-batch scheduler threads

**Comment by GuanLuo** [comment]
Is that the preprocess sample provided with Triton? That is a simple example of a specific use case and thus not really portable. You may want to modify the source code of the preprocess custom example to suit your need.

**Comment by hcx1231** [comment]
> Is that the preprocess sample provided with Triton? That is a simple example of a specific use case and thus not really portable. You may want to modify the source code of the preprocess custom example to suit your need.

OK,thank you
