### ISSUE TITLE
Broader input formatting supported

### ISSUE THREAD

**Issue by hugoperrin** [NVIDIA/triton-inference-server#1706]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hugoperrin** [comment]
In my workflow, I use pytorch and hugging face's transformer for NLP problems. As it works, it's easier to handle input dicts that get broadcasted to the model. For it to be straightforwardly usable with tensorrt, we would need to allow inputs to be themselves dicts, instead of anything else. Is there a specific reason why it's not possible? It seems conceivable that it can be translated into a transferable format, and I've tested the pytorch .pt, and it does support having INPUT__0 being a dict without much issue. I'm therefore struggling to get where the issue comes from to support such input formats of nested dicts, as long as the inputs end up being well defined for each keys with their sizes and types.

**Comment by deadeyegoodwin** [comment]
When you say "usable with tensorrt" are you trying to convert your model into a TensorRT model (https://developer.nvidia.com/tensorrt)?
Or are you just trying to run your torchscript (*.pt) model on Triton? Triton only supports tensor datatypes currently. We could expand it to support other datatypes but that would first require determining a standard binary format for the datatype that could be supported by as many frameworks as possible.

**Comment by hugoperrin** [comment]
I'm trying to run my torchscript model on triton, and it just so happens that for simplicity of use, it's easier to work with dict of tensors rather than having to unpack the dicts for namedparameters all the time, and makes for neater pipelines. Therefore my .pt model expects a single input being a dict of tensors. It would be therefore beneficial for workflows like mine using dict/list/tuples of tensors to be able to keep them as tensorrt inputs like this. Instead of having only dict of arrays, we would allow dict of dict/list/tuple of arrays as long as they keep a rather fixed structure.
Allowing those base python classes organizing tensors would be of great use, and does not seem that complex, as we already are sending a dict of numpy arrays, so nested dicts could be sent the same way. A simple workaround seems to be to send a shallow dict of each input alongside a mapping between those keys and the original structure. to sort of rebuild the structure. It shouldn't add too much overhead since it's basically changing references around to access underlying data differently, and allow for more flexibility for the models supported.
Am I missing something preventing from doing this? I haven't had time lately to look at the inference server code myself enough in depth, so I may have missed something.
Let me know if my use case is not yet clear.
It would be of great help to deploy more cleanly hugging face transformer models which are widely used.

**Comment by deadeyegoodwin** [comment]
The only difficulty is that Triton is not exclusively a pytorch inference server. It is designed to have a common, generic set of APIs that work across a range of frameworks and also a range of protocols (GRPC, HTTP/REST) and client programming languages. Triton is designed to be extensible in the input/output datatypes it supports, so something like you request can certainly be done... it just may require more generality.

Of course, you could also just create a python function that takes a dict of tensors and calls the appropriate Triton client APIs to pass them to Triton as individual named tensors. Then the rest of the code could continue to work with dicts.

**Comment by hugoperrin** [comment]
I guess anything I can specify properly as a json/protobuf neatly could be passed on as an input? If so I suppose the client programming language part of the equation requires the proto model not to be defined recursively, and there lies the tricky part of fitting to the generic side of things?

**Comment by deadeyegoodwin** [comment]
You can pass anything as a binary tensor, just serialize into bytes and them use a UINT8 [ -1 ] input tensor. Of course your model / custom backend on the other end needs to know how to deserialize that tensor appropriately.

**Comment by deadeyegoodwin** [comment]
Closed for inactivity. Reopen if additional information.
