### ISSUE TITLE
ONNX->TensorRT model fails supporting multiple batch sizes

### ISSUE THREAD

**Issue by FamousDirector** [NVIDIA/triton-inference-server#1707]
**Description**
I am using an ONNX model and using optimization to convert it to a TensorRT model with Triton. Whatever shape is sent first is the shape it builds. But then it throws an error: `tensorrtserver.api.InferenceServerException: [inference:0 10] onnx runtime error 11: Non-zero status code returned while running TRTKernel_0 node. Name:'TensorrtExecutionProvider_TRTKernel_0_0' Status Message: TensorRT EP Failed to Build Engine.`

**Triton Information**
I've using the tritonserver:20.03.1-py3 docker container. I am using a single Nvidia T4 and have several other models loaded.

**To Reproduce**
I use GRPC to send a request via the API with batch size X. Then I follow up with a request of batch size Y, which results in the error I mentioned above.
Here is the model config:

```
name: "osnet"
platform: "onnxruntime_onnx"
default_model_filename: "osnet.onnx"
dynamic_batching {
  max_queue_delay_microseconds: 500
  preserve_ordering: True
}
optimization {
  graph {
    level: 1   
  }
  execution_accelerators {
    gpu_execution_accelerator : 
    [{ 
      name : "tensorrt"
    }]
  }
}
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ -1,3,256,128 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1,512 ]
  }
]
```

**Expected behavior**
I would expect to be able to pass the model input with any batch size and have it work.

**Comment by deadeyegoodwin** [comment]
I assume you model runs correctly at all batch sizes if you turn off the tensorrt accelerator? Can you share the model?

**Comment by FamousDirector** [comment]
Correct. I can pass whatever size batch and it gives me the correct result. Obviously I want to use TensorRT to increase throughput speed. Here is a link to the model: [https://drive.google.com/file/d/1BSRT1ihj2FDi0qhFBGkDb1dqrMup--Pz/view?usp=sharing](model)

**Comment by FamousDirector** [comment]
Any update on this? I figured it was something wrong with my config... not a deeper rooted issue.

**Comment by deadeyegoodwin** [comment]
We haven't had a chance to look at it yet. It is likely some issue within the ONXX-TensorRT conversion being performed by the ONNX Runtime, but we need to repro before we can be sure.

**Comment by FamousDirector** [comment]
Thanks for the update. Let me know if I can assist.

**Comment by CoderHam** [comment]
@FamousDirector I downloaded your model and ran it with Tritonserver. I am able to run both ONNX and ONNX-TRT with different batch sizes. 

In the model config I do not see you specifying the max_batch_size. Without it Tritonserver does not support batch size >1. Your hack of changing input and output dims to make it variable is not the correct way to support batching. Additionally when I used the autofiller it set the max_batch_size = 1 and I had to override the same with a max batch size > 1. 

PS: You can use `--strict-model-config=false` with `--log-verbose=1` to see the config file generated by the autofiller. It is usually a good place to start.

This is the config file I used. 
```
name: "osnet"
platform: "onnxruntime_onnx"
max_batch_size: 8
input {
  name: "input"
  data_type: TYPE_FP32
  dims: [3, 256, 128]
}
output {
  name: "output"
  data_type: TYPE_FP32
  dims: [512]
}
dynamic_batching {
  max_queue_delay_microseconds: 500
  preserve_ordering: True
}
optimization {
  graph {
    level: 1   
  }
  execution_accelerators {
    gpu_execution_accelerator : 
    [{ 
      name : "tensorrt"
    }]
  }
}
```

**Comment by FamousDirector** [comment]
@CoderHam Thanks for looking into this. When I upgraded to the 20.06-v1 container the TensorRT is now working as expected with the `perf_client`. However now I seem to be getting this odd error: `ValueError: cannot reshape array of size 256 into shape (512,)`

This is my client side code:

```
#!/usr/bin/env python

from multiprocessing import Pool, set_start_method
import argparse
import numpy as np
import os
from builtins import range
from tensorrtserver.api import *

FLAGS = None

set_start_method('spawn')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action="store_true", required=False, default=False,
                        help='Enable verbose output')
    parser.add_argument('-u', '--url', type=str, required=False, default='localhost:8000',
                        help='Inference server URL. Default is localhost:8000.')
    parser.add_argument('-i', '--protocol', type=str, required=False, default='http',
                        help='Protocol ("http"/"grpc") used to ' +
                             'communicate with inference service. Default is "http".')
    parser.add_argument('-H', dest='http_headers', metavar="HTTP_HEADER",
                        required=False, action='append',
                        help='HTTP headers to add to inference server requests. ' +
                             'Format is -H"Header:Value".')

    FLAGS = parser.parse_args()
    protocol = ProtocolType.from_str(FLAGS.protocol)

    model_version = -1
    batch_size = 2

    model_name = "osnet"
    model_input_dims = (3, 256, 128)

    infer_contexts = []
    dummy_data = []

    # Create the inference context for the model.
    infer_ctx = InferContext(FLAGS.url, protocol, model_name, model_version,
                             http_headers=FLAGS.http_headers, verbose=FLAGS.verbose)
    # create dummy data the size of the input
    data = np.ones(shape=model_input_dims, dtype=np.float32)

    results = infer_ctx.run({'input': [data, data]},
                            {'output': InferContext.ResultFormat.RAW},
                            2)

    ctx_stats = infer_ctx.get_stat()

```

When I send a batch size of 4, I get a the same error but `128 into shape (512,)`. 

Please advise.

**Comment by CoderHam** [comment]
I'd recommend moving to the new V2 API since the V1 API will soon be deprecated. I will look into this and try to zero in on the issue. Did you use reshape in the config file?

**Comment by FamousDirector** [comment]
@CoderHam thanks for looking into this. I am not using a reshape; I’m using exactly what you posted for a config. 

We are planning to switch to V2, but it’s a bit further along in our roadmap. This would give us a nice boost in the meantime without having to rewrite all of our API calls. I’ll try and find some time to test it in V2.

**Comment by CoderHam** [comment]
Can you try to run this model outside Triton with onnxruntime natively? It appears that the model output is always 512 irrespective of the batch size. This is why the python client fails to create the array of shape [N, 512] since the result is always of size 512.

**Comment by FamousDirector** [comment]
I have run it in a native onnxruntime and I get proper results. I.e. When I pass 2 inputs I get 2 outputs. When I use the Triton config I first posted above, I also get the same number of results back as I pass to the model.

**Comment by CoderHam** [comment]
When you saw proper results you mean for an input of shape `[X, 3, 256, 128]` you get an output of shape `[X, 512]` ?

**Comment by FamousDirector** [comment]
@CoderHam yes that is what I mean.

**Comment by otherman16** [comment]
I have the same problem with dynamic batch-size.
I try to accelerate my ONNX model with tensorrt.

Model config:
```bash
name: "retinanet_onnx_gpu"
platform: "onnxruntime_onnx"
max_batch_size: 64
input [
    {
        name: "input__0"
        data_type: TYPE_FP32
        format: FORMAT_NCHW
        dims: [ 3, 640, 640 ]
    }
]
output [
    {
        name: "output__0"
        data_type: TYPE_FP32
        dims: [ 102300 ]
    },
    {
        name: "output__1"
        data_type: TYPE_FP32
        dims: [ 102300, 4 ]
    },
    {
        name: "output__2"
        data_type: TYPE_FP32
        dims: [ 102300, 10 ]
    }
]
instance_group [
    {
        count: 1
        kind: KIND_GPU
    }
]
dynamic_batching {
    preferred_batch_size: [ 2, 4, 8, 16, 24, 32, 40, 48, 56, 64 ]
    max_queue_delay_microseconds: 50000
    preserve_ordering: True
}
optimization {
    graph {
        level: 1
    }
    execution_accelerators {
        gpu_execution_accelerator : [ { name : "tensorrt" } ]
    }
}
version_policy: { all { } }
```

First (just after server starts) I infer batch of size 16 and everything is OK. But then all requests with batch_size != 16 return error:
```bash
tensorrtserver.api.InferenceServerException: [inference:0 15] in ensemble 'retinanet_ensemble_onnx_gpu', onnx runtime error 11: Non-zero status code returned while running TRTKernel_0 node. Name:'TensorrtExecutionProvider_TRTKernel_0_0' Status Message: TensorRT EP Failed to Build Engine.
```
and the error in TritIS log:
```bash
[W:onnxruntime:log, tensorrt_execution_provider.h:35 log] [2020-07-20 14:03:53   ERROR] Parameter check failed at: optimizationProfile.cpp::setDimensions::119, condition: std::all_of(dims.d, dims.d + dims.nbDims, [](int x) { return x > 0; })
[W:onnxruntime:log, tensorrt_execution_provider.h:35 log] [2020-07-20 14:03:53   ERROR] Parameter check failed at: optimizationProfile.cpp::setDimensions::119, condition: std::all_of(dims.d, dims.d + dims.nbDims, [](int x) { return x > 0; })
[W:onnxruntime:log, tensorrt_execution_provider.h:35 log] [2020-07-20 14:03:53   ERROR] Parameter check failed at: ../builder/BuilderConfig.cpp::addOptimizationProfile::149, condition: profile->isValid()
[W:onnxruntime:log, tensorrt_execution_provider.h:35 log] [2020-07-20 14:03:53   ERROR] Network has dynamic or shape inputs, but no optimization profile has been defined.
[W:onnxruntime:log, tensorrt_execution_provider.h:35 log] [2020-07-20 14:03:53   ERROR] Network validation failed.
```
TritIS V2 will solve my problem? What about V1?

**Comment by CoderHam** [comment]
@FamousDirector here is the V2 counterpart for your client. It works as expected with 20.06.

```
import argparse
import numpy as np
import tritonhttpclient
from tritonclientutils import InferenceServerException

FLAGS = None

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action="store_true", required=False, default=False,
                        help='Enable verbose output')
    parser.add_argument('-u', '--url', type=str, required=False, default='localhost:8000',
                        help='Inference server URL. Default is localhost:8000.')
    parser.add_argument('-i', '--protocol', type=str, required=False, default='http',
                        help='Protocol ("http"/"grpc") used to ' +
                             'communicate with inference service. Default is "http".')
    parser.add_argument('-H', dest='http_headers', metavar="HTTP_HEADER",
                        required=False, action='append',
                        help='HTTP headers to add to inference server requests. ' +
                             'Format is -H"Header:Value".')

    FLAGS = parser.parse_args()

    model_version = -1
    batch_size = 2

    model_name = "osnet"
    model_input_dims = (3, 256, 128)

    infer_contexts = []
    dummy_data = []

    data = np.ones(shape=(batch_size,) + model_input_dims, dtype=np.float32)

    triton_client = tritonhttpclient.InferenceServerClient(
                        url=FLAGS.url,
                        verbose=FLAGS.verbose)
    inputs = []
    inputs.append(tritonhttpclient.InferInput('input', [2, 3, 256, 128], "FP32"))

    # Initialize the data
    inputs[0].set_data_from_numpy(data, binary_data=True)

    outputs = []
    outputs.append(
        tritonhttpclient.InferRequestedOutput('output', binary_data=True))
    results = triton_client.infer(model_name,
                                  inputs,
                                  outputs=outputs)

    print(results.as_numpy('output').shape)

```

**Comment by CoderHam** [comment]
@otherman16 the issue here is specific to ONNX-TRT. The model for some reason cannot be converted to ONNX-TRT. You can use run the model with the Onnxruntime python API with the TRT execution provider to see that the issue is not specific to Triton. Maybe file a bug with Onnxruntime?

**Comment by otherman16** [comment]
@CoderHam  I'll try to run model with ONNX-TRT python API soon. Thanks.

I've found that error `Network has dynamic or shape inputs, but no optimization profile has been defined.` can be solved by setting flag `explicit_batch` (enabling dynamic shapes):
[ONNX-TRT Dynamic shapes](https://github.com/onnx/onnx-tensorrt#full-dimensions--dynamic-shapes)
```shell
import tensorrt
explicit_batch = 1 << (int)(tensorrt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
builder.create_network(explicit_batch)
```
Looks simple, but I really don't know how Triton do it inside. Seems that this flag haven't been set.

I'll try to run model with this ONNX-TRT python API soon.
