### ISSUE TITLE
S3 custom model load is not working

### ISSUE THREAD

**Issue by maondra** [NVIDIA/triton-inference-server#1718]
**Description**
I have a custom model in s3, and I want the model to be loaded by TRITON.
Local model repository works fine using mounting "-v" in docker.
Unfortunately, the model is not loaded when using s3://.... storage.

**Triton Information**
20.03.1

Are you using the Triton container or did you build it yourself?
Container

**To Reproduce**
custom model - image_preprocess_nchw_3x224x224_inception

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Error message:
E0626 13:43:39.147220 1 model_repository_manager.cc:891] failed to load 'image_preprocess_nchw_3x224x224_inception' version 1: Not found: unable to load custom library: s3://server:9000/inference/trtis/image_preprocess_nchw_3x224x224_inception/1/libimagepreprocess.so: cannot open shared object file: No such file or directory

**Expected behavior**
Load custom model.

**Comment by CoderHam** [comment]
We are in the process of adding S3 support for custom backend. It should come with the next release.

**Comment by deadeyegoodwin** [comment]
Fixed with #1469 and #1819 .

**Comment by deadeyegoodwin** [comment]
Fix will be in 20.08 release.
