### ISSUE TITLE
Loading of models from GCS is prohibitively slow

### ISSUE THREAD

**Issue by whillas** [NVIDIA/triton-inference-server#1733]
**Description**
We have many modes ~105 which are about 50MB each. We started to deploy them via a GCS bucket which solved a lot of problems but we're finding its taking around 2 hours to load all the models before its ready for inference. When we load the models from local disk it takes about 30 seconds.

**Triton Information**
Container 20.02 which is 1.11?
Using the pre-built number.

**To Reproduce**

Try loading over 100 models of about 50MB each from a GCS bucket

**Expected behaviour**
To be much faster. Should take 5 minutes to download the models off GCS and then 30 seconds to load them into Triton.

**Comment by whillas** [comment]
Any action on this ticket?

**Comment by deadeyegoodwin** [comment]
May be improved by #1824

**Comment by deadeyegoodwin** [comment]
Please try with #1824 fix (in 20.08 release). Reopen if you are still seeing the issue.
