### ISSUE TITLE
tensorrtserver.api.InferenceServerException: [ 0] status request did not return status

### ISSUE THREAD

**Issue by ruilongzhang** [NVIDIA/triton-inference-server#1749]
**Description**

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by ruilongzhang** [comment]
I run python3 image_client.py -m resnet50_netdef -s INCEPTION qa/images/mug.jpg
The reasons for this situation？

**Comment by GuanLuo** [comment]
What is your command for running the server? And what version of Triton are you using?

**Comment by deadeyegoodwin** [comment]
Closed for inactivity. Reopen if additional information.
