### ISSUE TITLE
Load onnx model error in trtis 19.09 container?

### ISSUE THREAD

**Issue by zxgm** [NVIDIA/triton-inference-server#1762]
There is a onnx model that was generated by use the torch.onnx.export interface,pytorch version is 1.3.0,my trtis image version is 19.09,and the error follow:
`I0708 02:37:22.406269 72 server.cc:110] Initializing TensorRT Inference Server
E0708 02:37:24.532915 72 logging.cc:43] ../rtSafe/coreReadArchive.cpp (31) - Serialization Error in verifyHeader: 0 (Magic tag does not match)
E0708 02:37:24.532988 72 logging.cc:43] INVALID_STATE: std::exception
E0708 02:37:24.532997 72 logging.cc:43] INVALID_CONFIG: Deserialize the cuda engine failed.
`
I find the explains that from https://forums.developer.nvidia.com/t/tensorrt-error-rtsafe-corereadarchive-cpp-31-serialization-error-in-verifyheader-0-magic-tag-does-not-match/81872 , Why use the onnx model to predict result that use tensorRT engine and tensorRT?

**Comment by zxgm** [comment]
I have opened the verbose option,got the message:
`I0708 07:20:51.406790 87 ensemble_backend_factory.cc:47] Create EnsembleBackendFactory
I0708 07:20:51.407844 87 autofill.cc:138] TensorFlow SavedModel autofill: Internal: unable to autofill for 'NoName', unable to find savedmodel directory
I0708 07:20:51.407868 87 autofill.cc:149] TensorFlow GraphDef autofill: Internal: unable to autofill for 'NoName', unable to find graphdef file named 'model.graphdef'
I0708 07:20:51.407887 87 autofill.cc:162] PyTorch autofill: Internal: unable to autofill for 'NoName', unable to find PyTorch file named 'model.pt'
I0708 07:20:51.407905 87 autofill.cc:175] Caffe2 NetDef autofill: Internal: unable to autofill for 'NoName', unable to find netdef files: 'model.netdef' and 'init_model.netdef'
I0708 07:20:51.426046 87 autofill.cc:198] ONNX autofill: Internal: onnx runtime error 10: This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (51) of operator (ReduceSum) in node () is invalid.
E0708 07:21:16.162082 87 logging.cc:43] ../rtSafe/coreReadArchive.cpp (31) - Serialization Error in verifyHeader: 0 (Magic tag does not match)
E0708 07:21:16.177306 87 logging.cc:43] INVALID_STATE: std::exception
E0708 07:21:16.177378 87 logging.cc:43] INVALID_CONFIG: Deserialize the cuda engine failed.
I0708 07:21:16.177433 87 autofill.cc:211] TensorRT autofill: Internal: unable to autofill for 'NoName', unable to create TensorRT runtime and engine
I0708 07:21:16.177464 87 model_config_utils.cc:203] autofilled config: name: "NoName"
max_batch_size: 128
instance_group {
  count: 1
  gpus: 0
  kind: KIND_GPU
}

E0708 07:21:16.177596 87 main.cc:943] error: creating server: INVALID_ARG - must specify platform for model 'NoName'
`
And found ReduceSum does not support tensor(bool) as per the ONNX spec.https://github.com/microsoft/onnxruntime/issues/2848

**Comment by zxgm** [comment]
I have opened the verbose option,got the message:
`I0708 07:20:51.406790 87 ensemble_backend_factory.cc:47] Create EnsembleBackendFactory
I0708 07:20:51.407844 87 autofill.cc:138] TensorFlow SavedModel autofill: Internal: unable to autofill for 'NoName', unable to find savedmodel directory
I0708 07:20:51.407868 87 autofill.cc:149] TensorFlow GraphDef autofill: Internal: unable to autofill for 'NoName', unable to find graphdef file named 'model.graphdef'
I0708 07:20:51.407887 87 autofill.cc:162] PyTorch autofill: Internal: unable to autofill for 'NoName', unable to find PyTorch file named 'model.pt'
I0708 07:20:51.407905 87 autofill.cc:175] Caffe2 NetDef autofill: Internal: unable to autofill for 'NoName', unable to find netdef files: 'model.netdef' and 'init_model.netdef'
I0708 07:20:51.426046 87 autofill.cc:198] ONNX autofill: Internal: onnx runtime error 10: This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (51) of operator (ReduceSum) in node () is invalid.
E0708 07:21:16.162082 87 logging.cc:43] ../rtSafe/coreReadArchive.cpp (31) - Serialization Error in verifyHeader: 0 (Magic tag does not match)
E0708 07:21:16.177306 87 logging.cc:43] INVALID_STATE: std::exception
E0708 07:21:16.177378 87 logging.cc:43] INVALID_CONFIG: Deserialize the cuda engine failed.
I0708 07:21:16.177433 87 autofill.cc:211] TensorRT autofill: Internal: unable to autofill for 'NoName', unable to create TensorRT runtime and engine
I0708 07:21:16.177464 87 model_config_utils.cc:203] autofilled config: name: "NoName"
max_batch_size: 128
instance_group {
  count: 1
  gpus: 0
  kind: KIND_GPU
}

E0708 07:21:16.177596 87 main.cc:943] error: creating server: INVALID_ARG - must specify platform for model 'NoName'
`
And found ReduceSum does not support tensor(bool) as per the ONNX spec.https://github.com/microsoft/onnxruntime/issues/2848

**Comment by deadeyegoodwin** [comment]
So the model is invalid it seems.
