### ISSUE TITLE
Wrong output for my triton segmentation model

### ISSUE THREAD

**Issue by bartmch** [NVIDIA/triton-inference-server#1764]
Hi, I'm trying to use image_client.py to create a segmentation client which is calling onnx segmentation model with the following config.pbtxt:

`name: "lungmask"
platform: "onnxruntime_onnx"
max_batch_size: 20
input [{
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 1, 256, 256 ]}]
output [{
    name: "output"
    data_type: TYPE_FP32
    dims: [ 3, 256, 256 ]}]`

The original model expects [20,1,256,256] and returns [20,3,256,256] with the 1st dimension being the batch_size. While running the code the inferencing seems to work but I'm unable to get the output.

`    for response in responses:
        if FLAGS.protocol.lower() == "grpc":
            this_id = response.get_response().id
        else:
            this_id = response.get_response()["id"]
        print("Request {}, batch size {}".format(this_id, FLAGS.batch_size))
        postprocess(response, output_name, FLAGS.batch_size, max_batch_size > 0)`

Using grpcs, my response in postprocess isn't getting the right results:

![image](https://user-images.githubusercontent.com/10415569/86893758-2eaf4800-c113-11ea-9812-9a66c54fa6c2.png)

I'm getting **['-0.0000', '23560']** where I would expect a **batch_size * [3,256,256]** 3d volume.
My guess that retrieving the results is still being done as it was a classifier (orginal code). **Can someone help me get the right output for my model?** Thank you!

**Comment by deadeyegoodwin** [comment]
You  need to request RAW output instead of classification output. You can look at the other python examples to see how this is done. For example: https://github.com/NVIDIA/triton-inference-server/blob/master-v1/src/clients/python/api_v1/examples/simple_client.py#L85

You should also consider using 20.06 release which contains the V2 clients and APIs.

**Comment by bartmch** [comment]
Hi @deadeyegoodwin thanks for the answer! I switched to V2. I assume if I want to use grpc then I'd need to use simple_grpc_infer_client.py.  Do I still need to follow `from tensorrtserver.api import *` and then get the raw values by running `infer_ctx.run(...'OUTPUT0' : InferContext.ResultFormat.RAW...)` or does this looks different in V2? Thank you!

**Comment by deadeyegoodwin** [comment]
The V2 client API is conceptually similar to V1 but the details are different. Look at the examples on the r20.06 or master branch in src/clients/python/examples and you will find many examples of how to send inference requests. The API is in the python API in the docs or just look at src/clients/python/library/grpcclient.py.
