### ISSUE TITLE
libevhtp patch step fails on sed: extra characters at the end of g command

### ISSUE THREAD

**Issue by guy4261** [NVIDIA/triton-inference-server#1766]
**Description**
Running the cmake build on OSX Catalina, configured with PyTorch support (`cmake -DTRITON_ENABLE_PYTORCH=ON`), I get the following error:

```bash
$ make -j1 server
...
[ 27%] Completed 'protobuf'
[ 33%] Built target protobuf
[ 44%] Built target prometheus-cpp
[ 46%] Performing patch step for 'libevhtp'
sed: 1: "/Users/grapaport/Docume ...": extra characters at the end of g command
make[3]: *** [libevhtp/src/libevhtp-stamp/libevhtp-patch] Error 1
make[2]: *** [CMakeFiles/libevhtp.dir/all] Error 2
make[1]: *** [CMakeFiles/server.dir/rule] Error 2
make: *** [server] Error 2
```

Not sure where is this patch coming from (tried to look it and fix the script/sed).

**Triton Information**
What version of Triton are you using?

Branch is `r20.06`, tag is `v2.0.0`, sha1 is `b5a252773bb098123248950964600bcc9f262962`.

Are you using the Triton container or did you build it yourself?

Trying to build it myself using cmake.

**To Reproduce**

```
$ cmake -DTRITON_ENABLE_PYTORCH=ON
$ mkdir -p ../builddir && cd ../builddir
$ make -j1
```

**Expected behavior**

Pass this build step.

**Comment by deadeyegoodwin** [comment]
Patch commands are run by cmake: https://github.com/NVIDIA/triton-inference-server/blob/master/build/CMakeLists.txt#L254

Be aware that we don't do any builds or testing on Mac, so you may run into a lot of issues...

**Comment by guy4261** [comment]
Thanks for letting me know! If Mac is not a testing target, then I will close and not bother you with that 👍🏻.
