### ISSUE TITLE
Mask RCNN TensorRT in Triton

### ISSUE THREAD

**Issue by MeghaGhosh** [NVIDIA/triton-inference-server#1778]
Hi, I have used TensorRT's sample uff Mask RCNN example to convert our model from h5 and create an engine file. I have loaded this engine onto the Triton server and used the --strict-model-config=false flag to generate the config.pbtxt. The server is started successfully on the HTTP and gRPC ports. What I need help with is using the C++ API to write the inference code. Not sure which client examples to follow. Any lead or direction of how to go about this or which particular example to follow would really help! A bit short on time hence putting this here. Thank you.

**Comment by deadeyegoodwin** [comment]
You should use 20.06 release and the V2 APIs. On the 20.06 branch look in src/clients/c++/examples and you will find a number of examples showing how to use the C++ library for both GRPC and HTTP/REST. The basic inference ones are simple_http_infer_client.cc and simple_grpc_infer_client.cc (and there are async versions as well).

The C++ library headers are in src/clients/c++/library
