### ISSUE TITLE
CUDA out of memory during inference, not during model loading

### ISSUE THREAD

**Issue by bartmch** [NVIDIA/triton-inference-server#1787]
**Description**
Loading of my (non-ensemble) 3 pytorch_libtorch models work fine. The inference of the last model gives CUDA out of memory. I was expecting for all (non-TF) loaded model to take the GPU memory space they needed, and not during inference.

**Triton Information** 20.06 by running downloaded Triton docker
**To Reproduce** Unfortunately I cannot share the models. Load multiple models:
`docker run --gpus=4 --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p9000:8000 -p9001:8001 -p9002:8002 -v/home/bart/model_repo:/models nvcr.io/nvidia/tritonserver:20.06-py3 tritonserver --model-repository=/models  --log-verbose=1`
One example model repository (the one that causes CUDA out of memory):
```
name: "seg"
platform: "pytorch_libtorch"
max_batch_size: 128
input [{
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 3, 512, 512 ]}]
output [{
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 2, 512, 512 ]}]
```
When I run my client script for all three models and the third model having a batch size bigger than 8, I get the following error in the Triton log:
![image](https://user-images.githubusercontent.com/10415569/87271128-57ed2100-c4e3-11ea-92f7-3718bd7988b0.png)
[triton_log.txt](https://github.com/NVIDIA/triton-inference-server/files/4910618/triton_log.txt)

The weird thing is that I allocated 4 GPUs but it seems that everything is loaded on the first GPU - As shown in the screenshot all 3 GPUs stay at 1977MiB, GPU0 is the only being used. I was hoping Triton would spread models/data over all available GPUs, but it looks like I would need to configure this somewhere?
![image](https://user-images.githubusercontent.com/10415569/87270920-b06fee80-c4e2-11ea-87cb-abd2bcea82e7.png)

**Expected behavior** I would like for Triton to upload all models and handle a higher batch size by using all available GPUs. The next step is to add all these 3 models into an ensemble model.

**Comment by deadeyegoodwin** [comment]
I think only TensorRT allocates all memory at loadtime. The other frameworks have dynamic allocation at inference time. See #1507 for some discussion.

As far as using multiple GPUs, by default Triton will put one copy of each model on each available GPU and then (roughly) round robin inference requests to those model copies. But you can control it more precisely using instance_groups: https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/model_configuration.html#instance-groups
