### ISSUE TITLE
Clip to predictions in ensembles

### ISSUE THREAD

**Issue by rsnk96** [NVIDIA/triton-inference-server#1790]
**Is your feature request related to a problem? Please describe.**
In an ensemble, it would be nice to be able to perform tensor operations / clip to boxes after an input has passed through one model before it is fed to the next model. Sample use case: Object Detection followed by classification

**Describe the solution you'd like**
Some way of defining tensor operations in an ensemble, especially cropping to prediction boxes between two models in an ensemble

**Describe alternatives you've considered**
One alternative is to use Deepstream for this, they have a parameter "PROCESS_MODE_CLIP_OBJECTS" that can be set for this. However, using Deepstream for my requirements would be over-designing at this stage

**Comment by anvuongb** [comment]
I'm facing the same problem with my models. I'm thinking about doing something like this, but have no idea if it would work. Basically something like this
![triton](https://user-images.githubusercontent.com/36110407/87626243-14e6b400-c756-11ea-9a6f-6b253653b1a2.png)


```
input {
  name: "INPUT_IMAGE"
  data_type: TYPE_FP32
  dims: ...
}

output {
  name: "OBJECT_ATTRIBUTES"
  data_type: TYPE_INT32
  dims: ...
}
ensemble_scheduling {
 step {
    model_name: "preprocess"
    model_version: -1
    input_map {
      key: "INPUT_IMAGE_PREP"
      value: "INPUT_IMAGE"
    }
    output_map {
      key: "PROCESSED_IMAGE"
      value: "INPUT_IMAGE_PREP"
    }    
  }
  step {
    model_name: "detection"
    model_version: -1
    input_map {
      key: "IMAGE_DETECTION"
      value: "PROCESSED_IMAGE"
    }
    output_map {
      key: "BOX"
      value: "BBOX"
    }
  }
  step {
    model_name: "CLASSIFICATION"
    model_version: -1
    input_map {
      key: "INPUT_BBOX"
      value: "BOX"
    }
    input_map {
      key: "IMAGE_RAW"
      value: "INPUT_IMAGE"
    }
    output_map {
      key: "CLASS"
      value: "OBJECT_ATTRIBUTES"
    }
  }
```

**Comment by deadeyegoodwin** [comment]
@anvuongb Based on your diagram you should be able to implement the ensemble.

@rsnk96 Currently there are no operations of any kind "built in" to ensembles. You would need to make a custom backend that does the clipping you want and then insert that backend at the appropriate place in the ensemble.
