### ISSUE TITLE
Auto switching between GPU and CPU for production environment?

### ISSUE THREAD

**Issue by luvwinnie** [NVIDIA/triton-inference-server#1793]
**Is your feature request related to a problem? Please describe.**
I have a triton inference server for  my production, however I have to prepare GPU and CPU version of config.pbtxt separately for my production environment. It's quite troublesome to build different docker images.

**Describe the solution you'd like**
I hope that from the config.pbtxt can use an option to allow the model to serve GPU but if GPU not available , it will try to serve the model with CPU for docker purpose.

**Comment by deadeyegoodwin** [comment]
Generally, you should not need to have different configuration for GPU node and CPU-only node. By default Triton will use GPUs if they are present and use CPUs if no GPU is present. See https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/model_configuration.html#instance-groups.

And the specific model configuration documentation is: https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/protobuf_api/model_config.proto.html#_CPPv4N6nvidia15inferenceserver18ModelInstanceGroupE
