### ISSUE TITLE
Unable to load model config with zero/random data warm up

### ISSUE THREAD

**Issue by drwaltman** [NVIDIA/triton-inference-server#1795]
**Description**

Hi, I am seeing the following error when I try to add warm up settings to my model config.  It happens when either `zero_data` or `random_data` are set.

```
E0715 01:27:39.808251 1 model_repository_manager.cc:970] failed to load 'efficientdet_graphdef' version 3: Invalid argument: expected 1 inputs but got 0 inputs for model 'efficientdet_graphdef'
```

**Triton Information**

I am using Triton v2.0.0.
I built the Triton container locally (only change was setting the Triton minimum compute capability to 3.7).

**Model Config**

```
name: "efficientdet_graphdef"
platform: "tensorflow_graphdef"
max_batch_size: 1
input [
    {
        name: "image_arrays"
        data_type: TYPE_UINT8
        format: FORMAT_NHWC
        dims: [ -1, -1, 3 ]
    }
]
output [
    {
        name: "detections"
        data_type: TYPE_FP32
        dims: [ -1, 7 ]
    }
]
instance_group [
    {
        kind: KIND_GPU
        count: 1
        gpus: [ 0 ]
    }
]
model_warmup [
    {
        name: "warmup_zero_512"
        batch_size: 1
        inputs: {
            key: "input"
            value: {
                data_type: TYPE_UINT8
                dims: [ 512, 512, 3 ]
                zero_data: true
            }
        }
    }
]
```

**Repro Steps**

1. Add `model_warmup` settings to model config.
2. Run triton for model config.

I can load my model and send Triton inference requests fine without the warm up settings added to the model config, so it isn't clear to me that this error is related to the model I am using.

**Expected behavior**

I expect the model warmup settings to not fail to be read by Triton when specified in the model config.

Does it look like there is a mistake in my model config?  I followed the docs [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/protobuf_api/model_config.proto.html#_CPPv4N6nvidia15inferenceserver11ModelWarmupE), and I also tried the example posted in https://github.com/NVIDIA/triton-inference-server/issues/708#issuecomment-627158079, but that resulted in the same error.

**Comment by GuanLuo** [comment]
The key for inputs should be the name of your inputs, which is "image_arrays" in this case.

**Comment by drwaltman** [comment]
Ah I didn't realize that at all, thanks!
