### ISSUE TITLE
Invalid argument: warmup setting expects n bytes

### ISSUE THREAD

**Issue by drwaltman** [NVIDIA/triton-inference-server#1796]
**Description**

Hi, I am trying to set up some warm up input files for my TensorFlow model, but I am running into the following error:

```
E0715 02:08:56.141822 1 model_repository_manager.cc:970] failed to load 'efficientdet_graphdef' version 3: Invalid argument: warmup setting expects 6220800 bytes, but the data provided from img.pngonly has 4080549 bytes
```

Is it necessary for the file size of the image to be the same as the product of the dims specified in the model config?

This is the image I am trying to send for warm up:
https://user-images.githubusercontent.com/11736571/77320690-099af300-6d37-11ea-9d86-24f14dc2d540.png

**Triton Information**

I am using Triton v2.0.0.
I built the Triton container locally (only change was setting the Triton minimum compute capability to 3.7).

**Model Config**

```
name: "efficientdet_graphdef"
platform: "tensorflow_graphdef"
max_batch_size: 1
input [
    {
        name: "image_arrays"
        data_type: TYPE_UINT8
        format: FORMAT_NHWC
        dims: [ -1, -1, 3 ]
    }
]
output [
    {
        name: "detections"
        data_type: TYPE_FP32
        dims: [ -1, 7 ]
    }
]
instance_group [
    {
        kind: KIND_GPU
        count: 1
        gpus: [ 0 ]
    }
]
model_warmup [
    {
        name: "warmup_file"
        batch_size: 1
        inputs: {
            key: "input"
            value: {
                data_type: TYPE_UINT8
                dims: [ 1080, 1920, 3 ]
                input_data_file: "img.png"
            }
        }
    }
]
```

**Comment by GuanLuo** [comment]
As stated [here](https://github.com/NVIDIA/triton-inference-server/blob/r20.07/src/core/model_config.proto#L1115-L1116), the file must contain raw data for the inputs. Base on the config you provided, it is data for UINT8 matrix with shape [1080, 1920, 3], but the file you provided is a png file, you should preprocess your image to the desired form

**Comment by drwaltman** [comment]
Ah that wasn't clear to me, thanks!

**Comment by masguit42** [comment]
@GuanLuo what's the correct way to create such file?
I'm stucked.

**Comment by GuanLuo** [comment]
@masguit42 What is the error message that you received? And do you mind to create a separate issue for your questions?

**Comment by masguit42** [comment]
@GuanLuo 
done:
https://github.com/triton-inference-server/server/issues/4285
