### ISSUE TITLE
Python API async_infer http callback

### ISSUE THREAD

**Issue by Mattadore** [NVIDIA/triton-inference-server#1803]
**Is your feature request related to a problem? Please describe.**
I cannot use standard async patterns without a callback on tritonhttpclient.async_infer() unless, it seems, I want to rewrite my client using gevent. The only way the documentation lists being able to get the result of an execution is to do a blocking get_result() call. I am currently using standard asyncio syntax which can work with a callback like the one provided in the python gRPC client, except the gRPC client has a fixed maximum message size.

**Describe the solution you'd like**
I would like a callback, or better standard asyncio support.

**Describe alternatives you've considered**
I have considered using gRPC, which has a callback, but the limited message lengths break things.

**Additional context**
It seems weird that the API, which is otherwise mostly mirrored between gRPC and http, varies in this way.

**Comment by deadeyegoodwin** [comment]
The HTTP API reflects the underlying implementation in a way that attempts to introduce minimal overhead. If you want a different API have you tried wrapping it? For example, you could try wrapping the blocking calls and then invoking a callback yourself. As in https://stackoverflow.com/questions/41063331/how-to-use-asyncio-with-existing-blocking-library

**Comment by Mattadore** [comment]
This does not work, gevent is required to run in the main thread and it breaks if you try to put it in a thread pool because it expects to be used in its own event loop, as they are competing implementations. As it stands, the inference client itself seems to rely on Greenlets for almost all calls, all of which break if run in a thread pool with an executor as described.

**Comment by Mattadore** [comment]
Specifically I get:
`greenlet.error: cannot switch to a different thread`

**Comment by tanmayv25** [comment]
@Mattadore Yes. I observed the same behavior when tried to invoke requesting greenlet in separate thread pool inside python client library. For cooperative multitasking using geventhttpclient it is necessary for main thread to yield.. without which the greenlet will never get to run.

> I am currently using standard asyncio syntax which can work with a callback like the one provided in the python gRPC client, except the gRPC client has a fixed maximum message size.
PR #1799 has increased the limitation on maximum message size. The change is available in the master an will be released in 20.08.

**Comment by deadeyegoodwin** [comment]
We'll consider making a asyncio/aiohttp -based python client to go along with the gevent-based client we currently have.

**Comment by whillas** [comment]
**asyncio/aiohttp**-based please! Since this _is_ a server and all calls to it will be I/O bound.

**Comment by Tandon-A** [comment]
@deadeyegoodwin Is there any update on this?

**Comment by deadeyegoodwin** [comment]
No, it is still on our backlog. If you want to make your own asyncio/aiohttp based client you can still leverage all the request formatting and response parsing code in the tritonclient. See https://github.com/triton-inference-server/server/blob/main/qa/L0_sagemaker/sagemaker_test.py#L106 and following functions in the file as an example that uses regular "requests" module to send the requests.
