### ISSUE TITLE
TensorFlow 2 support

### ISSUE THREAD

**Issue by drwaltman** [NVIDIA/triton-inference-server#1804]
Hi,

I am trying to deploy a TensorFlow graphdef model on Triton 2.0.0.  I have noticed that inference times in TensorFlow are much slower when the model is exported using v1.15.2 (~1.1s) instead of v2.2.0 (~0.11s).  When I tested both exports on Triton, I noticed that the TF2.2.0 export loses its performance advantage and is about the same speed as the TF1.15.2 export (~1.1s).  My assumption is that TF2.2.0 is responsible for this inference time difference since Triton uses TF1.15.2, and that allowing Triton to serve TF2.2.0 models would result in better inference times for my use case.

I tried building a custom image from the base [Dockerfile](https://github.com/NVIDIA/triton-inference-server/blob/v2.0.0/Dockerfile#L33) with the TensorFlow image arg updated.

Here is what I set the arg to (replaced `tf1` with `tf2` after seeing it was an option in the tf [docs](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/running.html#running)):

```
ARG TENSORFLOW_IMAGE=nvcr.io/nvidia/tensorflow:20.06-tf2-py3
```

But it looks like the TF2 TRTIS lib doesn't exist because I get this copy failure:

```
Step 39/124 : COPY --from=trtserver_tf      /usr/local/lib/tensorflow/libtensorflow_trtis.so.1      /opt/tritonserver/lib/tensorflow/
COPY failed: stat /var/lib/docker/aufs/mnt/92c0ea40c2eebfb2675728f6de9f6123c63d1dc1a93fb6455e28905720d95d53/usr/local/lib/tensorflow/libtensorflow_trtis.so.1: no such file or directory
```

Is it possible to build Triton so that it can serve models with TensorFlow 2, or is there an ETA on when it will be supported?

Thanks

**Comment by deadeyegoodwin** [comment]
Unfortunately, the TF C APIs that Triton depends on are incomplete and so Triton has to patch and build its own version of TF. That means that you can't just drop in a different version of TF and have it work. The build documentation details this and you can do the patching yourself, but it is a complicated process.
But we are working on TF2 support right now, and we hope to have it in the 20.08 release. So was might just want to wait for that.

**Comment by drwaltman** [comment]
Ah ok, ill wait for the 20.08 release then, thanks for the quick response!

**Comment by roarjn** [comment]
Hi @deadeyegoodwin, Is TF2.x support added in 20.08 release?

**Comment by deadeyegoodwin** [comment]
Yes, it was announced in the release: https://github.com/triton-inference-server/server/releases/tag/v2.2.0
