### ISSUE TITLE
E0720 03:43:07.419723 1 main.cc:1099] error: creating server: INTERNAL - failed to load all models

### ISSUE THREAD

**Issue by GeneralJing** [NVIDIA/triton-inference-server#1808]
E0720 03:42:54.944486 1 model_repository_manager.cc:810] failed to load 'hrnet_libtorch' version 1: Internal: load failed for libtorch model -> 'hrnet_libtorch': 
Unknown type name '__torch__.torch.nn.modules.module.___torch_mangle_312.Module':
at code/__torch__/torch/nn/modules/module/___torch_mangle_460.py:5:13
op_version_set = 1
class Module(Module):
  __parameters__ = []
  training : bool
  base_net : __torch__.torch.nn.modules.module.___torch_mangle_312.Module
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  bu_dec_l1 : __torch__.torch.nn.modules.module.___torch_mangle_340.Module
  bu_dec_l2 : __torch__.torch.nn.modules.module.___torch_mangle_368.Module
  bu_dec_l3 : __torch__.torch.nn.modules.module.___torch_mangle_396.Module
  bu_dec_l4 : __torch__.torch.nn.modules.module.___torch_mangle_420.Module
  merge_enc_dec_l2 : __torch__.torch.nn.modules.module.___torch_mangle_430.Module
  merge_enc_dec_l3 : __torch__.torch.nn.modules.module.___torch_mangle_440.Module
  merge_enc_dec_l4 : __torch__.torch.nn.modules.module.___torch_mangle_450.Module
  bu_br_l2 : __torch__.torch.nn.modules.module.___torch_mangle_453.Module
  bu_br_l3 : __torch__.torch.nn.modules.module.___torch_mangle_456.Module
Compiled from code.
any suggestion?

**Comment by CoderHam** [comment]
Which version of Triton and PyTorch are you using? 
Is there a specific reason you are building from source instead of using the released container?

**Comment by CoderHam** [comment]
@GeneralJing waiting on your revert

**Comment by deadeyegoodwin** [comment]
Closed for inactivity. Reopen if additional information.

**Comment by GeneralJing** [comment]
sorry, problem already solved. thank you all.
