### ISSUE TITLE
OpenVINO unsupported operation

### ISSUE THREAD

**Issue by otherman16** [NVIDIA/triton-inference-server#1809]
**Description**
I am trying to accelerate my PyTorch-ONNX model with OpenVINO.
There is warning message in Triton-Inference-Server logs:
`[W:onnxruntime:log, openvino_execution_provider.cc:546 GetCapability] [OpenVINO-EP] Rejecting as graph has unsupported operations.Operation is not supported by OpenVINO` and then `[V:onnxruntime:, inference_session.cc:639 TransformGraph] All nodes have been placed on [CPUExecutionProvider].`

So TritIS tell me that it can't convert some layers from ONNX I think. But server starts anyway. Moreover, there is an performance increase in graph computation (1.5-2.0 times).

I am discouraged.

Questions:
1. How can I determine which operations exactly OpenVINO rejects?
2. Despite the warning performance has increased. It is a kind of magic or Iv'e interpret TritIS logs in wrong way?

**Triton Information**
What version of Triton are you using?
tritonserver:v.1.13.0

Are you using the Triton container or did you build it yourself?
I have build container by myself on branch r20.03.1.

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Detection model with ResNet50 backbone and FPN.

**Comment by deadeyegoodwin** [comment]
The log is saying that some part of your model can't convert to openVINO and so ONNXRuntime is instead just going to use the normal CPU execution mode for the model. Note that the log message is just a warning (the 'W' at the beginning) and so Triton goes ahead.

Triton itself is relying on ONNX Runtime for ONNX and ONNX-OpenVINO support. If you want to understand why your model is failing to convert or if there are plans to support the missing operation (which you don't show in your log snippet). https://github.com/microsoft/onnxruntime
