### ISSUE TITLE
How to send binary tensor data to ensemble model by HTTP request?

### ISSUE THREAD

**Issue by xiaofei-du** [NVIDIA/triton-inference-server#1822]
I am using Triton 20.06 and created an ensemble model `my_ensemble_model` which combines the preprocessing custom model and a ResNet50 model.

**I was trying to send binary data to the model for inference.** 

Following the [Binary Tensor Data Extension example](https://github.com/NVIDIA/triton-inference-server/blob/master/docs/protocol/extension_binary_data.md#examples), I am confused how to send the binary data with the JSON object.

>The binary data for a tensor is delivered in the HTTP body after the JSON object (see Examples).

I tried to directly append the binary data to the JSON object as the [example](https://github.com/NVIDIA/triton-inference-server/blob/master/docs/protocol/extension_binary_data.md#examples) suggested, but got `400` request error
```
{
    "error": "failed to parse the request JSON buffer: The document root must not be followed by other values. at 418"
}
``` 

I wonder what is the correct way to send the binary data with the JSON object in the HTTP body?

**Comment by deadeyegoodwin** [comment]
It looks like perhaps you didn't specify the Inference-Header-Content-Length header or it has the wrong value.

**Comment by xiaofei-du** [comment]
Hi @deadeyegoodwin, sorry for not being clear. 
After fixing a typo, it worked now. This is what I have done.

I have an image `dog.png` (`445,623` bytes) to feed to the ensemble model.
- prefix the `dog.png` image with a 4 byte unsigned integer giving the size of the image, and convert into a binary object (`445,627` bytes)
- define a JSON object as below 
```
{
        'inputs': [
            {
                "name": "INPUT",
                "shape": [1, 1],
                "datatype": "BYTES",
                "parameters": {
                    "binary_data_size": 445627
                }
            }
        ],
        "outputs": [
            {
                "name": "OUTPUT",
                "parameters": {
                    'classification': 1,
                    "binary_data": False
                }
            }
        ]
    }
```
- get the size of the JSON object (`187` bytes)
- pack the JSON object and the binary object together into a binary file (`445,814` bytes).

- send using CURL
```
curl 'localhost:8000/v2/models/preprocess_resnet50_ensemble/versions/1/infer' \
--header 'Inference-Header-Content-Length: 187' \
--header 'Content-Type: application/octet-stream' \
--data-binary '@request_dog'
``` 

and got `200` response
```
{
    "model_name": "preprocess_resnet50_ensemble",
    "model_version": "1",
    "outputs": [
        {
            "name": "OUTPUT",
            "datatype": "BYTES",
            "shape": [1,1],
            "data": ["16.722591:187:YORKSHIRE TERRIER"]
        }
    ]
}
```
