### ISSUE TITLE
new v2 api embeds nvidia.inferenceserver as package name in .proto

### ISSUE THREAD

**Issue by jeffgriffith** [NVIDIA/triton-inference-server#1827]
**Description**

v2 is intended to enable portable clients to be written according to the kubeflow serving spec (docs/protocol/grpc_core_service.proto). The overall service definition in src/core/grpc_service.proto, however, embeds the "nvidia.inferenceserver" as its package name which appears to couple the grpc client to triton. We attempted to remove these from the .proto and rebuild but we get StatusCode.UNIMPLEMENTED from Triton which would seem to make sense given the mismatch.

**Triton Information**

**20.06-py3**

Are you using the Triton container or did you build it yourself?  **Triton container**

**To Reproduce**
Removed 'package nvidia.inferenceserver' from our .proto and attempted to do inference with the new version.

**Expected behavior**

To make this work, should the package name be removed? Or replaced with something to express the open source nature of the protocol? (e.g. kubeflow.inferenceserver?)

**Comment by deadeyegoodwin** [comment]
i think we will just change the package name to "triton".

**Comment by jeffgriffith** [comment]
that wouldn't remove the coupling though, would it Dave?

**Comment by deadeyegoodwin** [comment]
Actually that won't work since it is an open protocol. Likely we will just remove the package specification.

**Comment by deadeyegoodwin** [comment]
Removing the package entirely is not a great idea... it causes lots of name conflicts with local class, functions, etc. How about just using "inference" as the package. Seems related but generic.
