### ISSUE TITLE
Error in request.raw_input_contents.extend([input_bytes])

### ISSUE THREAD

**Issue by Rathna21** [NVIDIA/triton-inference-server#1832]
System:
TritonInferenceServer:20.6 - nvcr.io/nvidia/tritonserver:20.06-py3
whl file for grpc client - tritongrpcclient-2.0.0-py3-none-any.whl

Hello, 

```
    def prepare_request(self, img):

        request = grpc_service_pb2.ModelInferRequest()
        request.model_name = self._MODEL_NAME
        request.model_version = self._MODEL_VERSION
        output = grpc_service_pb2.ModelInferRequest().InferRequestedOutputTensor()
        output.name = "vgg0_dense2_fwd"
        request.outputs.extend([output])

        input = grpc_service_pb2.ModelInferRequest().InferInputTensor()
        input.name = "data"
        input.shape.extend([1, 3, self._IMAGE_HEIGHT, self._IMAGE_WIDTH])
        request.inputs.extend([input])

        image_data = []
        image_data.append(self.vgg16_preprocess(img))
        input_bytes = image_data[0].tobytes()
        request.raw_input_contents.extend([input_bytes])

        return request
```

I am trying to prepare a request object and pass the input_bytes to the request object as follows
**request.raw_input_contents.extend([input_bytes])**

I am getting **Attribute error : raw_input_contents** 

I looked into the file https://github.com/NVIDIA/triton-inference-server/blob/master/src/core/grpc_service.proto but I am not able to use it. 

Please let me know how I can resolve this error?

**Comment by tanmayv25** [comment]
`raw_input_contents` was added recently into the master with PR #1812.  r20.6 gRPC service proto([link](https://github.com/NVIDIA/triton-inference-server/blob/r20.06/src/core/grpc_service.proto)) doesn't have raw_input_contents, but a nested raw_contents field inside InferTensorContents message. Please refer to [this](https://github.com/NVIDIA/triton-inference-server/blob/r20.06/src/clients/python/examples/grpc_image_client.py) example for writing clients for 20.06.

The more performant message format will be available in our 20.08 release.
