### ISSUE TITLE
Perf client output

### ISSUE THREAD

**Issue by JungukCho** [NVIDIA/triton-inference-server#1834]
**Description**

1. I am not sure why the output from perf client is different.
Below is the measured number. The request counts in Client and Server are different.
What makes this difference?
It seems the server's output is collected from trtis server prometheus metric(8002/metrics) in perf_client. 
Is it right?  How does perf client collect Server's statistics?

2. What is this message?
Failed to obtain stable measurement within 1 measurement windows for concurrency 1. 
Please try to increase the --measurement-interval.
-> Do I need to adjust --measurement-interval if I just want to measure baseline performance of trtis?

$ ../install/bin/perf_client -m 1 -s INCEPTION -u 172.17.0.2:8000 --concurrency-range 1:1 -p 10000 -r 1
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 10000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client:
    **Request count: 1162**
    Throughput: 116.2 infer/sec
    Avg latency: 8604 usec (standard deviation 443 usec)
    p50 latency: 8608 usec
    p90 latency: 9185 usec
    p95 latency: 9264 usec
    p99 latency: 9492 usec
    Avg HTTP time: 8608 usec (send/recv 301 usec + response wait 8307 usec)
  Server:
    **Request count: 1393**
    Avg request latency: 5635 usec (overhead 73 usec + queue 49 usec + compute 5513 usec)

Failed to obtain stable measurement within 1 measurement windows for concurrency 1. Please try to increase the --measurement-interval.
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 116.2 infer/sec, latency 8604 usec

**Triton Information**
What version of Triton are you using?
1. I am using TRTIS 19.03-py3  and tritonserver:20.03.1-py3-clientsdk.

Are you using the Triton container or did you build it yourself?
1. Use the container from ngc

**To Reproduce**
Steps to reproduce the behavior.
1. Run Trtis (or Triton) on docker and use perf_client to send requests to the Trtis.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

1. framework : tensorrt
2. inputs and outputs from perf client

**Expected behavior**
1. Intuitively, output in Client and Server side should have the same.

**Comment by tanmayv25** [comment]
>   1. I am using TRTIS 19.03-py3 and tritonserver:20.03.1-py3-clientsdk.

TRTIS 19.03 is very old, you must use the identical version.

> I am not sure why the output from perf client is different.
> Below is the measured number. The request counts in Client and Server are different.
> What makes this difference?

The difference is expected. The execution of requests on the server is completely independent from the perf_client side measurements.  More details below.

> It seems the server's output is collected from trtis server prometheus metric(8002/metrics) in perf_client.
> Is it right? How does perf client collect Server's statistics?

No, the server keeps accumulating the number of inferences for each of the loaded model. These statistics can be queried from the client side. See how the perf_client does that in [this ](https://github.com/NVIDIA/triton-inference-server/blob/r20.03.1/src/clients/c%2B%2B/perf_client/inference_profiler.cc#L561-L591) block. 

The requests count reported on the client are the ones that were started and ended within the measurement period. The above function points the same. So, it is expected to be client side count to be less than the server side counts. 

> 
> What is this message?
> Failed to obtain stable measurement within 1 measurement windows for concurrency 1.
> Please try to increase the --measurement-interval.
> -> Do I need to adjust --measurement-interval if I just want to measure baseline performance of trtis?

This means that with the given measurement window, the latency/throughput were highly variable... you can operate the client in verbose mode(using -v flag) to see the output. If the variability looks good then you can increase the `--stability-percentage` as per your use case.

**Comment by JungukCho** [comment]
Thank you for reply.
I have some following questions.

TRTIS 19.03 is very old, you must use the identical version.
-> I knew trtis 19.03 is old, but some reason I need to run experiments on this version.
Is there significant problem to use this version?
In addition is there problems to use different version of trtis and client? 
It seems it supports backward-compatibility.

No, the server keeps accumulating the number of inferences for each of the loaded model. These statistics can be queried from the client side. See how the perf_client does that in this block.
-> To be clear, here server is "trtis". client side is "perf_client". is it right?
So, perf_client queries statistics to trtis by using different interface (not metrics exposed 
 via 8002/metrics (https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/metrics.html). 
Is it right?
Would you please point the logic for these statistics in triton or trtis code?

In this case, if I run multiple trtis instances (in other words, multiple dockers to run multiple trtis instances) with one load balancer, I need to rely on client side metrics since the perf_client only contacts one trtis server to get these statistics.
Is it correct?

The requests count reported on the client are the ones that were started and ended within the measurement period. The above function points the same. So, it is expected to be client side count to be less than the server side counts.
-> Oh, I see. So, it may lose the response after measurement period.
In my experiment, as you saw, I used 10 secs measurement period with one trial with these options( -p 10000 -r 1).
So, in this case, if the client gets responses after 10 secs (it seems 12 secs based on code), it does not count  them.

**Comment by tanmayv25** [comment]
> Is there significant problem to use this version? In addition is there problems to use different version of trtis and client?

Triton Inference Server has evolved quite a bit from last year. Our testing and benchmarking script uses the server and client from identical release. Even though the project tries to maintain backwards compatibility there can be some slip-ups. If for some reason you are stuck with r19.03, then I would recommend using the perf_client present in that [release](https://github.com/NVIDIA/triton-inference-server/blob/r19.03/src/clients/c%2B%2B/perf_client.cc). 

> To be clear, here server is "trtis". client side is "perf_client". is it right?

Yes

> Would you please point the logic for these statistics in triton or trtis code?

Look for `ServerStatusManager::UpdateServerStat` [here](https://github.com/NVIDIA/triton-inference-server/blob/r19.03/src/core/server_status.cc) and the protobuf message returned to the client [here](https://github.com/NVIDIA/triton-inference-server/blob/r19.03/src/core/server_status.proto). You can further read into how the status is returned to the client.

>In this case, if I run multiple trtis instances (in other words, multiple dockers to run multiple trtis instances) with one load >balancer, I need to rely on client side metrics since the perf_client only contacts one trtis server to get these statistics.
>Is it correct?

Right.
