### ISSUE TITLE
Installation of Triton Server with helm chart 

### ISSUE THREAD

**Issue by svetlanadataper** [NVIDIA/triton-inference-server#1835]
**Description**
Hi,

I am trying to install the Triton Inference Server on Kubernates cluster. I am getting the following error:

`helm install --generate-name . `
                   
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext`

**Triton Information**
Using master branch, I see the deployment.yaml is the same on most latest branches. 

**Expected behavior**
Deployment fails, expecting to create a deployment on Kubernetes.

Thank you

Svetlana

**Comment by deadeyegoodwin** [comment]
What version of k8s are you using?

**Comment by svetlanadataper** [comment]
> What version of k8s are you using?

Hi,

The version is below:

kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:45:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Thank you

Svetlana

**Comment by deadeyegoodwin** [comment]
Can you try using a 1.15.x version of k8s as mentioned here: https://github.com/NVIDIA/triton-inference-server/tree/master/deploy/single_server#kubernetes-deploy-triton-inference-server-cluster

Otherwise you likely need to update the helm charts because in 1.16 I believe k8s deprecated some things that they currently depend on.

**Comment by svetlanadataper** [comment]
My deployments are on this version, I would have to setup another node to install a lower version.

What do you mean by updating the helm charts? Do you mean modifying the charts to comply with the new version?

Thank you for your response

Svetlana

**Comment by deadeyegoodwin** [comment]
Yes, I believe k8s made some non-backwards-compatible changes moving from v1beta to v1. The Triton charts currently use v1beta API so need to be updated as well. It would be a great contribution if you were able to update them.

**Comment by svetlanadataper** [comment]
> Yes, I believe k8s made some non-backwards-compatible changes moving from v1beta to v1. The Triton charts currently use v1beta API so need to be updated as well. It would be a great contribution if you were able to update them.

Thank you once again for the feedback. I was able to get it running by removing 'fsGroup', so now my deployment.yaml looks like this:

` securityContext:
            runAsUser: 1000`

I also encountered another issue:

`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"`

Looking at 'service.yaml' it has this block:

`apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "triton-inference-server-metrics-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "triton-inference-server-metrics-monitor.name" . }}
    chart: {{ template "triton-inference-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "triton-inference-server-metrics.name" . }}
  endpoints:
  - port: metrics
    interval: 15s`

I had to remove it to get it working, I am assuming Grafana will not work now. Question is am I missing something? Do I need to install 'kube-prometheus'?

Regards

Svetlana

**Comment by deadeyegoodwin** [comment]
You don't need to use the Triton metrics, or prometheus, if you don't want to.

**Comment by svetlanadataper** [comment]
> You don't need to use the Triton metrics, or prometheus, if you don't want to.

Sounds good thank you. I guess I will need to install it if I want to use it. Maybe its good to mention it in the README that it must be already installed.

**Comment by svetlanadataper** [comment]
> You don't need to use the Triton metrics, or prometheus, if you don't want to.

I managed to get the Triton Inference Server to run on Kubernetes 1.18. Maybe its worth updating the helm yaml files. I also added configuration in deployment.yaml to be able to use a local /model-repository, which is really useful if you don't want to add your models to gs.

**Comment by deadeyegoodwin** [comment]
It would be great if you could put your changes into a PR so we can see what you did and adopt them for our next version of the charts.

**Comment by svetlanadataper** [comment]
> It would be great if you could put your changes into a PR so we can see what you did and adopt them for our next version of the charts.

Sure I can do that!

**Comment by Lydia-Lv** [comment]
> > You don't need to use the Triton metrics, or prometheus, if you don't want to.
> 
> I managed to get the Triton Inference Server to run on Kubernetes 1.18. Maybe its worth updating the helm yaml files. I also added configuration in deployment.yaml to be able to use a local /model-repository, which is really useful if you don't want to add your models to gs.



> > You don't need to use the Triton metrics, or prometheus, if you don't want to.
> 
> I managed to get the Triton Inference Server to run on Kubernetes 1.18. Maybe its worth updating the helm yaml files. I also added configuration in deployment.yaml to be able to use a local /model-repository, which is really useful if you don't want to add your models to gs.

Hi, my k8s is 1.17 and i use a local model repository, but failed.  So, can you tell me what did you do in detail? Thx

**Comment by xiaofei-du** [comment]
> > > You don't need to use the Triton metrics, or prometheus, if you don't want to.
> > 
> > 
> > I managed to get the Triton Inference Server to run on Kubernetes 1.18. Maybe its worth updating the helm yaml files. I also added configuration in deployment.yaml to be able to use a local /model-repository, which is really useful if you don't want to add your models to gs.
> 
> > > You don't need to use the Triton metrics, or prometheus, if you don't want to.
> > 
> > 
> > I managed to get the Triton Inference Server to run on Kubernetes 1.18. Maybe its worth updating the helm yaml files. I also added configuration in deployment.yaml to be able to use a local /model-repository, which is really useful if you don't want to add your models to gs.
> 
> Hi, my k8s is 1.17 and i use a local model repository, but failed. So, can you tell me what did you do in detail? Thx

You can use [`hostPath`](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) to mount your local model repository into your pod: 
```yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  ...
  template:
    ...
    spec:
      volumes:
      - name: triton-volume
        hostPath:
          # Directory location on host
          path: {{ .Values.image.modelRepositoryPath }}
          type: Directory
      containers:
          ...
          volumeMounts:
          - mountPath: /models
            name: triton-volume
            ...
          args: ["tritonserver", "--model-store=/models"]
          ...
```
Just be aware `hostPath` is not recommended to be used ([Kubernetes Storage Lingo 101](https://youtu.be/uSxlgK1bCuA?t=368)) since it breaks the k8s principle: workload portability.

**Comment by Lydia-Lv** [comment]
@xiaofei-du Thank you very much!It really works.

**Comment by naveengogineni** [comment]
> > You don't need to use the Triton metrics, or prometheus, if you don't want to.
> 
> I managed to get the Triton Inference Server to run on Kubernetes 1.18. Maybe its worth updating the helm yaml files. I also added configuration in deployment.yaml to be able to use a local /model-repository, which is really useful if you don't want to add your models to gs.

Can you let me know the configuration in deployment.yaml to be able to use local model-repository?

**Comment by svetlana41** [comment]
> > > You don't need to use the Triton metrics, or prometheus, if you don't want to.
> > 
> > 
> > I managed to get the Triton Inference Server to run on Kubernetes 1.18. Maybe its worth updating the helm yaml files. I also added configuration in deployment.yaml to be able to use a local /model-repository, which is really useful if you don't want to add your models to gs.
> 
> Can you let me know the configuration in deployment.yaml to be able to use local model-repository?

Hi,

I have this in 'values.yaml' with the model repository path:

`
replicaCount: 1

image:
  imageName: nvcr.io/nvidia/tritonserver:20.03-py3
  pullPolicy: IfNotPresent
  modelRepositoryPath: /models
  numGpus: 1

service:
  type: LoadBalancer`


And this in deployment.yaml:

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "triton-inference-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "triton-inference-server.name" . }}
    chart: {{ template "triton-inference-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "triton-inference-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "triton-inference-server.name" . }}
        release: {{ .Release.Name }}

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imageName }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          resources:
            limits:
              nvidia.com/gpu: {{ .Values.image.numGpus }}

          args: ["trtserver", "--model-store={{ .Values.image.modelRepositoryPath }}"]`

This is a partial file. 

Svetlana
