### ISSUE TITLE
The useage of GPU memory in TRT environment is pretty more than Python environment for a torch scripte model.

### ISSUE THREAD

**Issue by zhangfan2018** [NVIDIA/triton-inference-server#1839]
**Description**
I trained a torch scripte model in python environment, the useage of GPU memory is 6GB in inference session for an input shape of [256, 256, 256]. While the useage of GPU memory is more than 11GB when I deployed it in TRT environment by C++.

**Triton Information**
TRT version:20.03 Torch:1.5.1
For the input shape of [256, 256, 256], the CUDA is out of memory.

**To Reproduce**
I designed the normalization and resample operation as a layer in pytorch model, so the input shape is uncertion. And it's a UNet segmentation model. The first layer is as flows:
class Input(nn.Module):
    def __init__(self):
        super(Input, self).__init__()

    def forward(self, x):
        x = F.interpolate(x, size=(256, 256, 256), mode='trilinear', align_corners=True)
        x = torch.clamp(x, min=-1200, max=1200)
        mean = torch.mean(x)
        std  = torch.std(x)
        x = (x - mean) / (1e-5 + std)

        return x
As mentioned above, I also restricted the input shape below the [256, 256, 256]. The useage of GPU memory is less than 6 GB when it inferences in Python environment, while the useage of GPU memory is more than 11GB in TRT enviroment. I have kown that the TRT server will optimize model layer by defalut, the usage of GPU memory may increase a lot. But the increased useage of GPU memory is unbearable. I have tried to set the model optimization policy down by specifying the optimization policy/setting in the config file as flows:
optimization {  graph { level: -1 } } 
But it doesn't work.

**Expected behavior**
I want to know the cause of the increased useage of GPU memory, Why?
How can I set the optimization policy down?
How can the usage of GPU memory  in Python and TRT environment will be no difference?
What method can lower the usage of GPU memory besides the reduced precision inference and model optimization?

**Comment by deadeyegoodwin** [comment]
The size of the TensorRT model is a function of the TensorRT model generation and runtime. A primary contributor will be the maximum batch size that you set when creating that model. To get TensorRT help you should ask your question on the TensorRT issues at https://github.com/NVIDIA/TensorRT.

**Comment by zhangfan2018** [comment]
> The size of the TensorRT model is a function of the TensorRT model generation and runtime. A primary contributor will be the maximum batch size that you set when creating that model. To get TensorRT help you should ask your question on the TensorRT issues at https://github.com/NVIDIA/TensorRT.

The model is running on triton-inference-server rather than TensorRT. Why the usage of GPU memory will increased a lot in triton-inference-server enviorment?

**Comment by deadeyegoodwin** [comment]
You said TRT multiple times in your question so I assumed you were running both a TensorRT model and a Pytorch model and comparing them. Do not use TRT to refer to Triton... they are entirely different things.
Are you running the exact same torchscript model in Triton and using direct pytorch APIs?

**Comment by zhangfan2018** [comment]
> You said TRT multiple times in your question so I assumed you were running both a TensorRT model and a Pytorch model and comparing them. Do not use TRT to refer to Triton... they are entirely different things.
> Are you running the exact same torchscript model in Triton and using direct pytorch APIs?

Yes, I runned the same torchscript model in Triton and Python environment, but the useage of GPU memory is pretty difference. What cause this difference?
