### ISSUE TITLE
Understanding more about triton

### ISSUE THREAD

**Issue by nyanmn** [NVIDIA/triton-inference-server#1844]
May I know triton server allows user to run their own customized deep learning model in the server?
What is the cost model for the user?
Is it subscription-based or usage?
Since we can run our models at other available clouds, what is triton's outstanding features compared to other clouds?

**Comment by DonnieKim411** [comment]
I think it is best for you to actually read the README.rst and see what this package is about...

Also check here: https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/index.html

But if you are short on time, imo, 1 video is always better than 1000 words: https://www.youtube.com/watch?v=1DUqD3zMwB4
