### ISSUE TITLE
Inference with 20.06 using curl

### ISSUE THREAD

**Issue by taylanates24** [NVIDIA/triton-inference-server#1845]
Hello, 

I want to do inference using curl command with triton inference server release 20.06. The inference using image_client.py is successful. However, I cannot do inference by using curl. I followed the instructions on kubeflow/kfserving - Predict Protocol - Version 2. All the commands were successful except one.

my successful commands are:

`curl -X GET localhost:8000/v2/health/live`

`curl -X GET localhost:8000/v2/health/ready`

`curl -X GET localhost:8000/v2/models/resnet50_netdef/versions/1`

`curl -X GET localhost:8000/v2/models/resnet50_netdef/versions/1/ready`

The following command returns 400 Bad Request error:

`curl -X POST localhost:8000/v2/models/resnet50_netdef/versions/1/infer`

It also gives 
{"error":"failed to parse the request JSON buffer: Invalid value. at 0"}

I want to do inference using a classification model and curl. 
Is there any documentation about the inference using curl, the headers, data type and so on? I though, I should use a command something like:

`curl -X POST localhost:8000/v2/models/resnet50_netdef/versions/1/infer -v -H "Content-Type: application/octet-stream" -H 'NV-InferRequest: batch_size: 1 input { name: "gpu_0/data" data_type: TYPE_FP32 format: FORMAT_NCHW dims: [ 3, 224, 224 ] } output { name: "gpu_0/softmax" data_type: TYPE_FP32 dims: [ 1000 ] label_filename: "resnet50_labels.txt }' -v --data "@data.npy"`

the "data.npy" is the pre-processed image which is used in "image_client.py" code.

However, I don't know the right headers and data type, if there is a documentation about this, it will be very helpful for me.
Thank you in advance.

**Comment by deadeyegoodwin** [comment]
Docs are reachable from the github README.
https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/http_grpc_api.html

You can use the -v flag with the HTTP client examples to see the HTTP requests that are generated.
