### ISSUE TITLE
Are the Triton clients thread safe?

### ISSUE THREAD

**Issue by phuotran** [NVIDIA/triton-inference-server#1856]
Hello,

Are the C++ and Python Triton clients thread safe? 

According to the [documentation](https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/cpp_api/classnvidia_1_1inferenceserver_1_1client_1_1InferenceServerHttpClient.html?highlight=thread#_CPPv4N6nvidia15inferenceserver6client25InferenceServerHttpClientE), the C++ HTTP client is not thread safe. But I haven't found any mention of it for 
- the C++ gRPC client
- the Python HTTP client
- the Python gRPC client

My application sends requests to a Triton server from multiple threads. So I'm wondering if I should instantiate a client in each thread or if I can instantiate the client once and let all threads use the same client.

**Comment by tanmayv25** [comment]
See the PR #1858 which documents the thread-safety of the clients. Let us know if you come across any bugs.

**Comment by phuotran** [comment]
Thanks!

**Comment by ghost** [comment]
Hi @tanmayv25 I got 1 error cuda 900 when warmup triton with multiple thread, I have to set `--model-load-thread-count 1` to workaround . 
my repository have model with onnx backend, python backend, tensorflow backend.
