### ISSUE TITLE
String field 'nvidia.inferenceserver.ModelInferResponse.InferOutputTensor.ParametersEntry.key' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

### ISSUE THREAD

**Issue by MeghaGhosh** [NVIDIA/triton-inference-server#1871]
Hi, I am trying to serve TensorRT MaskRCNN model in Triton. The model is loaded and the client is successfully communicating with it. However, I'm facing an issue with appending the preprocessed image values to the Triton input. My data is in float and the  AppendRaw() function expects a byte vector or array. This is a part of the preprocess code that has been adapted from https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleUffMaskRCNN/sampleUffMaskRCNN.cpp

mPPMs.resize(batchSize);
mOriginalPPMs.resize(batchSize);
// assert(mPPMs.size() <= imageList.size());
for (int i = 0; i < batchSize; ++i)
{
	MaskRCNNUtils::readPPMFile(imagefilepath, mOriginalPPMs[i]);
	MaskRCNNUtils::preprocessPPM(mOriginalPPMs[i], mPPMs[i], inputH, inputW);
}
float pixelMean[3]{123.7, 116.8, 103.9};
std::vector <float > image_data;

for (int i = 0, volImg = inputC * inputH * inputW; i < batchSize; ++i)
    {
        for (int c = 0; c < inputC; ++c)
        {
            // The color image to input should be in RGB order
            for (unsigned j = 0, volChl = inputH * inputW; j < volChl; ++j)
            {
                image_data.push_back(float(mPPMs[i].buffer[j * inputC + c]) - pixelMean[c]);
            }
        }
    }

std::vector<uint8_t> byteVec(sizeof(image_data));
memcpy(byteVec.data(), &image_data, sizeof(image_data));
}

Then I'm appending byteVec to the input_ptr as follows:

input_ptr->AppendRaw(byteVec);

When I run this I'm getting the error: [libprotobuf ERROR /workspace/build/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:603] String field 'nvidia.inferenceserver.ModelInferResponse.InferOutputTensor.ParametersEntry.key' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

How can I correctly append my preprocessed data to the input pointer?

**Comment by deadeyegoodwin** [comment]
So image_data is a std::vector<float>? You just need to give the raw data to AppendRaw so there is no need to use byteVec (and that code is incorrect because you are sizing byteVec wrong). Remove the byteVec code and use:

input_ptr->AppendRaw(image_data.data(), image_data.size() * sizeof(float))

You then just need to make sure that image_data's lifetime is at least as long as input_ptr because you are appending the data by reference, it is not copied.

**Comment by MeghaGhosh** [comment]
Hey, thanks for the advice. However when I'm appending the std::vector as input_ptr->AppendRaw(image_data.data(), image_data.size() * sizeof(float)), I'm getting the following error:

/workspace/build/client/../../src/clients/c++/library/common.h:259:9: note: candidate: nvidia::inferenceserver::client::Error nvidia::inferenceserver::client::InferInput::AppendRaw(const uint8_t*, size_t)
   Error AppendRaw(const uint8_t* input, size_t input_byte_size);
         ^~~~~~~~~
/workspace/build/client/../../src/clients/c++/library/common.h:259:9: note:   no known conversion for argument 1 from 'float*' to 'const uint8_t* {aka const unsigned char*}'

**Comment by MeghaGhosh** [comment]
In the previous comment, image_data is initalised as std::vector <float> but the float doesn't show up in the comment because of formatting.

**Comment by MeghaGhosh** [comment]
Hi @deadeyegoodwin I've been stuck on this for a week. Any help would be really appreciated.

**Comment by deadeyegoodwin** [comment]
That error seems to be coming from something set in a parameter field. Can you provide a complete example that we can compile and use to reproduce. Please provide all the server and client commands we need to repro.

**Comment by MeghaGhosh** [comment]
So I have built and saved my engine file in the same GPU and then mounted it onto tritonserver:20.03.1-py3 container. (20.06 did not work and gave some errors) I run the server container with the following command. My engine file is stored in **models -> mrcnn -> 1 -> mrcnn_nchw.engine**

_docker run --gpus=1 --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/home/tonkabi/model:/models nvcr.io/nvidia/tritonserver:20.03.1-py3 tritonserver --min-supported-compute-capability=5.2 --log-verbose=1 --strict-model-config=false --model-repository=/models --api-version=2 --allow-http=True --http-port=8080 --allow-grpc=True --grpc-port=8082 --grpc-infer-allocation-pool-size=0  --trace-file=/tmp/tritonserver_trace.json --trace-rate=1000 --trace-level=MAX --tf-allow-soft-placement=True_

The model is loaded successfully and grpc and http services are started. I then run the 20.06-py3-clientsdk container with this command:

_docker run --gpus=1 -it --rm --net=host <container ID>_

Then using _docker cp_ I copy my mrcnn_client.cc and updated CMakeLists.txt file into /workspace/src/clients/c++/examples/ and build the client using the Ubuntu commands given here: https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/client_library.html

The example is compiled successfully and creates the mrcnn_client executable. I then create a directory images inside /workspace/build/client/install/bin and copy my image into it. (The image path is hardcoded in mrcnn_client)

Finally, when I run ./mrcnn_client I get the following error:

**[libprotobuf ERROR /workspace/build/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:603] String field 'nvidia.inferenceserver.ModelInferResponse.InferOutputTensor.ParametersEntry.key' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
error: unable to run model: No message returned for unary request**

I am attaching both mrcnn_client.cc (as a text file) and CMakeLists.txt here.

[CMakeLists.txt](https://github.com/NVIDIA/triton-inference-server/files/5057053/CMakeLists.txt)
[mrcnn_client.txt](https://github.com/NVIDIA/triton-inference-server/files/5057059/mrcnn_client.txt)

**Comment by tanmayv25** [comment]
The V2 API are not yet stabilized and are still under active development. This means that different releases are not necessarily compatible with one another as we change with evolving set of requirements. The [parameters](https://github.com/NVIDIA/triton-inference-server/blob/b5a252773bb098123248950964600bcc9f262962/src/core/grpc_service.proto#L703) map was added in 20.06 but is missing in 20.03.1 from the `InferOutputTensor`.  As in the 20.03, key 4 is content instead of map of InferParameters, you are seeing this error. 

Can you give `nvcr.io/nvidia/tritonserver:20.03.1-py3-clientsdk` a try instead?

**Comment by MeghaGhosh** [comment]
Yes, that worked. Thank you.
