### ISSUE TITLE
Typo in the v2.0.0 release notes - Jetson Jetpack Support  

### ISSUE THREAD

**Issue by penolove** [NVIDIA/triton-inference-server#1872]
**Is your feature request related to a problem? Please describe.**

https://github.com/NVIDIA/triton-inference-server/releases/tag/v2.0.0
in the Jetson Jetpack Support section having a typo for `lib64-dev` I think it should be `libb64-dev`

**Comment by CoderHam** [comment]
Fixed! Thank you for bringing this to our attention
