### ISSUE TITLE
Question on perf_client (both client and server version at 20.06)

### ISSUE THREAD

**Issue by DonnieKim411** [NVIDIA/triton-inference-server#1878]
According to `perf_client.rst` doc on github: https://github.com/NVIDIA/triton-inference-server/blob/master/docs/perf_client.rst, the throughput is defined as:

`perf_client reports latency and throughput as seen from the client (that is, as seen by perf_client) and also the average request latency on the server.`

so say i called the following:

`# perf_client -m my_model -u localhost:8000 -b 8  --concurrency-range 8`

with the following results:

```
*** Measurement Settings ***
  Batch size: 8
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 8
  Client:
    Request count: 1292
    Throughput: 2067.2 infer/sec
    Avg latency: 30970 usec (standard deviation 771 usec)
    p50 latency: 30860 usec
    p90 latency: 31886 usec
    p95 latency: 32252 usec
    p99 latency: 33116 usec
    Avg HTTP time: 30891 usec (send/recv 160 usec + response wait 30731 usec)
  Server:
    Inference count: 12440
    Execution count: 1554
    Successful request count: 1554
    Avg request latency: 28419 usec (overhead 6 usec + queue 24611 usec + compute input 35 usec + compute infer 3756 usec + compute output 11 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 8, throughput: 2067.2 infer/sec, latency 30970 usec
```

For the completeness sake, here is my dynamic batch config:

```
name: "my_model"
platform: "tensorflow_savedmodel"
max_batch_size: 8
dynamic_batching {
    preferred_batch_size: [ 4, 8 ]
    max_queue_delay_microseconds: 1000
}
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
```

So questions:

1. ~~this throughput number 2067.2 infer/sec is seen by the perf_client. But perf_client sends 8 requests at a time since I requested concurrency of 8. So, the number 2067.2 infer/sec is not an individual request perspective, but as a whole...? What I ultimately would like to know is that once the inference server is up, can a cohort of users/clients concurrently request the model inference service. And if so, what is the throughput per client's perspective.~~

I just realized how the throughput number came out. There were 1292 requests in 5 sec but 8 concurrency, hence 1292/5*8 = 2067.2 infer/sec. So my assumption is correct. The throughput is seen by the whole (8 clients).

2. I made a batch size to be 8 on perf_client calll. So for 2067.2 infer/sec, that is inference of 8 points of data, correct? hence 16k data pts can be inferred per sec.

3. On the server side, it has inference count of 12440, execution count of 1554. I assume the inference count number is calculated as execution count * number of concurrency? or the batch size? (1554 * 8 gives 12432, not 12440.... so it can't be number of concurrency). Also, why is the execution count different from the request count (1292 requests vs 1554 execution count)?

4. Lastly, this is more of a design question that I want to know. So I have 4 clients who share the same HPC cluster and I plan to assign one client-sdk docker for them to share. The clients can request the model server service randomly such that it is possible that all those 4 would request simultaneously. Does `perf_client` simulate such use case?

Many thanks in advance!

**Comment by tanmayv25** [comment]
1. It is wrong to think of concurrency parameter as the number of clients. In fact, concurrency is not used in any of the calculations. The concurrency of N just means that perf_client will try to keep N number of requests in-flight. So, after sending N requests, perf_client will send a new request only if one of the last N requests completes. It is control parameter for the server load. You might see higher throughput on increasing the concurrency as it pipelines the different stages of the request that add latencies. (See here: https://github.com/NVIDIA/triton-inference-server/blob/master/docs/perf_client.rst)

2. The batch size  is already factored in the reported throughput. (See here: https://github.com/NVIDIA/triton-inference-server/blob/master/src/clients/c%2B%2B/perf_client/inference_profiler.cc#L717-L718)

3. It is not the number of concurrency but the batch size. With dynamic batcher the server, will combine some of the requests into a single batch. The execution of this batch will be counted as 1 execution, but BatchSize Inference. For the difference in the counts look here : https://github.com/NVIDIA/triton-inference-server/issues/1834

4. perf_client is created as a testing framework and has some restriction on the way it generates the load. You can have four different invocations of the client and study different options available for the perf_client.

**Comment by DonnieKim411** [comment]
Okay cool. I think I have a better understanding of perf_client usage now. Thank you! I am closing this issue.
