### ISSUE TITLE
Config.pbtxt Issue

### ISSUE THREAD

**Issue by chiehpower** [NVIDIA/triton-inference-server#1889]
**Description**
Hi everyone, I was trying to let the onnx model and trt model which can be implemented on TRTIS. I took the model which was successfully implemented TRT and did inference on local. (i.e., by normally run TRT way) 

Hence, I took this onnx into the TRTIS's model repository.  However, I met an issue about the config.pbtxt.

Here is my content of config.pbtxt. 
```
name: "test_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 1

input [
  {
    name: "input.1"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 512, 512 ] 
    reshape { shape: [ 1, 3, 512, 512 ] }
  }
]

output [
  {
    name: "508"
    data_type: TYPE_FP32
    dims: [ 1, 128, 128 ]
    reshape { shape: [ 1, 1, 128, 128 ] }
  },
  {
    name: "511"
    data_type: TYPE_FP32
    dims: [ 2, 128, 128 ]
    reshape { shape: [ 1, 2, 128, 128 ] }
  },
    {
    name: "514"
    data_type: TYPE_FP32
    dims: [ 2, 128, 128 ]
    reshape { shape: [ 1, 2, 128, 128 ] }
  }
]

instance_group [
  {
    count: 2
    kind: KIND_GPU
  }
]
```

However, I got this error. 
```
failed to load 'test_onnx' version 1: Invalid argument: unable to load model 'test_onnx', model configuration supports batching but first dimension of tensor 'input.1' expected by framework is not a variable-size batch dimension: [1,3,512,512] whereas model configuration shape is: [1,3,512,512]
```

Let me show the information which was generated by Netron tool.
![Screenshot at 16-28-35](https://user-images.githubusercontent.com/32332200/89764232-9a2b7180-db26-11ea-988c-760d242be0e3.png)

Is there any idea about this?
How can I fix it? 
Thank you so much!

**Triton Information**
I was on `r19.08` branch. 
The command to implement TRTIS is below.
```
docker run --runtime nvidia \                                                                                                                        
    --rm --shm-size=1g \
    --ulimit memlock=-1 \
    --ulimit stack=67108864 \
    -p 8000:8000 -p 8001:8001 -p 8002:8002 \
    --name trt_serving \
    -v $model_path:/models \
    nvcr.io/nvidia/tensorrtserver:19.10-py3 \
    trtserver --model-store=/models
```

**Expected behavior**
I expected it can show the word like this :
```
successfully loaded 'test_onnx' version 1
```

Thank you again!

**Comment by GuanLuo** [comment]
Please try the following config, note that the `max_batch_size` and `dims` are different as your model doesn't support batching (first dimension is not dynamic dimension). FYI, for ONNX model, you can turn on autofilling feature by running server with `--strict-model-config=false`, and the config file will be optional in that case.
```
name: "test_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 0

input [
  {
    name: "input.1"
    data_type: TYPE_FP32
    dims: [ 1, 3, 512, 512 ] 
  }
]

output [
  {
    name: "508"
    data_type: TYPE_FP32
    dims: [ 1, 1, 128, 128 ]
  },
  {
    name: "511"
    data_type: TYPE_FP32
    dims: [ 1, 2, 128, 128 ]
  },
    {
    name: "514"
    data_type: TYPE_FP32
    dims: [ 1, 2, 128, 128 ]
  }
]

instance_group [
  {
    count: 2
    kind: KIND_GPU
  }
]
```

**Comment by chiehpower** [comment]
Hi @GuanLuo ,

Thanks for your information and solution!
It is useful and I I can successfully run it! 

BR,
Chieh
