### ISSUE TITLE
No error or warnings when underlying models of ensemble model request doesn't succeed

### ISSUE THREAD

**Issue by FamousDirector** [NVIDIA/triton-inference-server#1900]
**Description**
The reported Prometheus stats for the inference success rate of the ensemble mode are 100%. The 2 models that are used within the model are showing much lower success rates (~30% and ~50%). There are no clear errors/warnings in the verbose output (`--log-verbose`). 

Because of the constant retrying the throughput of my model is reduced to a crawl.

**Triton Information**
I'm using the 20.06 V2 container and clients.

**To Reproduce**
Have an ensemble model and two underlying models. I don't think the config matters here, I just want error output.

**Expected behavior**
I would expect to see errors or warnings when inference fails. I need to know why it's failing.

**Comment by GuanLuo** [comment]
Can you share a minimum repro? The error from the underlying models should be propagated to the ensemble

**Comment by FamousDirector** [comment]
I found the cause of my issue. I was misinterpreting the values I was getting from Prometheus. No errors were actually occuring. Closing & thanks.
