### ISSUE TITLE
How is the concurrent model execution support feature performs?  Is there any benchmark data?

### ISSUE THREAD

**Issue by jeshxxx** [NVIDIA/triton-inference-server#1902]

**Comment by nieksand** [comment]
https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/optimization.html#perf-client

**Comment by deadeyegoodwin** [comment]
There are too many variables to have a simple answer to that questions. The link in the previous comment describes how to run perf_client, so you can load up the models you are interested in and try it out under the conditions that match your use-case.
