### ISSUE TITLE
Support for XGBoost

### ISSUE THREAD

**Issue by ellistarn** [NVIDIA/triton-inference-server#358]
XGBoost is a commonly used ML framework. It supports multiple saved model formats like .bst and .joblib. There does not currently exist a performant XGBoost server for inferencing.

It would be great to have TensorRT support for XGBoost models for both CPU and GPU. Unfortunately I don't have any real models other than our toy models. but TensorRT should work on everything XGBoost has to offer.

https://xgboost.readthedocs.io/en/latest/gpu/

**Comment by deadeyegoodwin** [comment]
Marking as enhancement.

**Comment by pablete** [comment]
Also look into FIL Forest Inference Library, part of cuML part of rapids.asi
https://rapidsai.github.io/projects/cuml/en/0.9.0/api.html#cuml.ForestInference
https://medium.com/rapids-ai/rapids-forest-inference-library-prediction-at-100-million-rows-per-second-19558890bc35

**Comment by JohnZed** [comment]
Hi, @ellis-bigelow - I work on the forest inference library (FIL) mentioned above, which provides GPU acceleration for XGBoost models. (See our blog post: https://medium.com/rapids-ai/rapids-forest-inference-library-prediction-at-100-million-rows-per-second-19558890bc35)
 I'd be happy to talk sometime about how you can fit FIL into your pipeline in a manner similar to TensorRT. It's meant to be an easy drop in with about 2 functions necessary in the API (load_model, then infer).

**Comment by saifrahmed** [comment]
@JohnZed and @pablete we also tried out FIL with very similar [breathtaking] inference speeds! Thanks for the above link/write-up on this, that was all we needed to get going.

**Comment by sijopkd** [comment]
@JohnZed Can you please provide resources on how FIL can fit into the pipeline? For instance, I have prepared a XGBoost model using cuML. Everything is in the notebook phase now. I would like to know how to take into production. How to fit it into the pipeline as we do with TensorRT? 


Thank you so much!

**Comment by JohnZed** [comment]
Hi, @sijopkd - please stay tuned for updates in the next few weeks on upcoming plans for Triton+FIL! The Triton backend is not available today, but we will update here when we have the schedule formalized.
