### ISSUE TITLE
Support specifying host header in example clients grpc?

### ISSUE THREAD

**Issue by JungukCho** [NVIDIA/triton-inference-server#643]
Hi, I have a similar requirements which was resolved in "Support specifying host header in example clients #386", but for grpc.
Is it possible to specify  a host name in example clients using grpc?

**Comment by deadeyegoodwin** [comment]
Can you point us to a grpc example or documentation showing which grpc feature you want to be exposed in the clients?

**Comment by tanmayv25** [comment]
The support for providing custom headers has been added to the version 2 of the gRPC python client. Look [here ](https://github.com/NVIDIA/triton-inference-server/blob/master/src/clients/python/experimental_api_v2/examples/simple_grpc_v2_infer_client.py#L76-L79) for example.

We will be soon adding V 2 C++ clients for the same.

**Comment by BorisPolonsky** [comment]
> The support for providing custom headers has been added to the version 2 of the gRPC python client. Look [here ](https://github.com/NVIDIA/triton-inference-server/blob/master/src/clients/python/experimental_api_v2/examples/simple_grpc_v2_infer_client.py#L76-L79) for example.
> 
> We will be soon adding V 2 C++ clients for the same.

I'm also seeking document for this feature, however the linked page mentioned above is gone.

**Comment by tanmayv25** [comment]
This is a very old issue hence broken link was to be expected.
We document most of the functionality in our client library files:
https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/grpc/__init__.py#L1271-L1273

All the network APIs should have the header specification.

See here for example: https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_infer_client.py#L126-L132.
Note `headers={'test': '1'}`
